### ISSUE TITLE
Build javacv for arm64 : got problem ""

### ISSUE THREAD

**Issue by calluschen** [bytedeco/javacpp-presets#344] opened 2016-12-28 01:29 UTC
Hi ,
I followed the steps and try to build javacv for arm64 platform w/ command:
:~/javacpp-presets$]>ANDROID_NDK=~/Android/android-ndk/android-ndk-r13b bash cppbuild.sh -platform android-arm64 install

But, the build step was interrupted w/ error below.
---------------------------------------------------------------------------------
tesseract-3.04.01/wordrec/wordrec.h
Error: Platform "android-arm64" is not supported
~/javacpp-presets
Installing "caffe"
~/javacpp-presets/caffe/cppbuild ~/javacpp-presets
Error: Platform "android-arm64" is not supported
~/javacpp-presets
Installing "cuda"
~/javacpp-presets/cuda/cppbuild ~/javacpp-presets
Error: Platform "android-arm64" is not supported
~/javacpp-presets
Installing "mxnet"
~/javacpp-presets/mxnet/cppbuild ~/javacpp-presets
Error: Platform "android-arm64" is not supported
~/javacpp-presets
Installing "tensorflow"
~/javacpp-presets/tensorflow/cppbuild ~/javacpp-presets
Downloading https://github.com/tensorflow/tensorflow/archive/v0.11.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   130    0   130    0     0    146      0 --:--:-- --:--:-- --:--:--   194
100 8038k    0 8038k    0     0   909k      0 --:--:--  0:00:08 --:--:-- 1402k
Decompressing archives
已讀取位元組總數: 40386560 (39MiB, 90MiB/s)
patching file util/python/python_config.sh
Error: Platform "android-arm64" is not supported

How to solve it?

**Comment by saudet** [comment] 2016-12-28 03:53
Like I said, we need to add support for the android-arm64 platform.

**Comment by calluschen** [comment] 2016-12-28 04:56
Thanks for quickly responding.
For android-arm64 platform supporting , are there any plans/schedule for implementation?

**Comment by saudet** [comment] 2017-01-19 23:54
Marking as duplicate of #54

**Closed by saudet** 2017-01-19 23:54 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2018-02-27 03:09
64-bit builds for Android (as the "android-arm64" and "android-x86_64" platforms) are now available, so please give it a try! Binaries for 1.4.1-SNAPSHOT can be downloaded from the snapshot repository: http://bytedeco.org/builds/
