### ISSUE TITLE
Missing macosx arm64 JARs for leptonica, tesseract

### ISSUE THREAD

**Issue by singingwolfboy** [bytedeco/javacpp-presets#1347] opened 2023-04-28 13:23 UTC
I'm trying to install [Audiveris](https://audiveris.github.io/audiveris/) on my M1 Macbook Pro. The [installation guide](https://audiveris.github.io/audiveris/_pages/install/sources/) explains that Gradle should automatically pull in Tesseract and Leptonica, but on my computer, it fails. This seems to be because [the Maven repository](https://repo.maven.apache.org/maven2/org/bytedeco/javacpp-presets/leptonica/1.73-1.3/) does not include JAR files for macosx-arm64 for these two projects.

Is there some way to build these JARs and put them in the Maven repository? I don't know how to do it myself, unfortunately -- but I'm happy to help if I can!

**Comment by saudet** [comment] 2023-04-28 14:10
Please upgrade to 1.5.8.

**Comment by saudet** [comment] 2023-04-28 14:11
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1069

**Closed by saudet** 2023-04-28 14:11 UTC
Labels: duplicate, enhancement
