### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path in macos snapshot of ffmpeg

### ISSUE THREAD

**Issue by jfehr67** [bytedeco/javacpp-presets#1138] opened 2022-01-26 19:22 UTC
I pulled a fresh snapshot this morning, and got the same error:

```
    java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
        at java.lang.Runtime.loadLibrary0(Runtime.java:872)
...
        Caused by:
        java.lang.UnsatisfiedLinkError: /Volumes/TB3/Users/john.fehr/.javacpp/cache/ffmpeg-5.0-1.5.7-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/ffmpeg/macosx-x86_64/libjniavutil.dylib: dlopen(/Volumes/TB3/Users/john.fehr/.javacpp/cache/ffmpeg-5.0-1.5.7-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/ffmpeg/macosx-x86_64/libjniavutil.dylib, 0x0001): Library not loaded: /usr/local/opt/libx11/lib/libX11.6.dylib
          Referenced from: /Volumes/TB3/Users/john.fehr/.javacpp/cache/ffmpeg-5.0-1.5.7-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/ffmpeg/macosx-x86_64/libavutil.57.dylib
          Reason: tried: '/usr/local/opt/libx11/lib/libX11.6.dylib' (no such file), '/usr/lib/libX11.6.dylib' (no such file)
            at java.lang.ClassLoader$NativeLibrary.load(Native Method)
            at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
```

Took a look at dependencies, and this is what it showed:

```
(base) Johns-iMac:t john.fehr$ otool -L ~/.javacpp/cache/ffmpeg-5.0-1.5.7-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/ffmpeg/macosx-x86_64/libjniavutil.dylib
/Volumes/TB3/Users/john.fehr/.javacpp/cache/ffmpeg-5.0-1.5.7-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/ffmpeg/macosx-x86_64/libjniavutil.dylib:
	libjniavutil.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libavutil.57.dylib (compatibility version 57.0.0, current version 57.17.100)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
(base) Johns-iMac:t john.fehr$ otool -L ~/.javacpp/cache/ffmpeg-5.0-1.5.7-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/ffmpeg/macosx-x86_64/libavutil.57.dylib 
/Volumes/TB3/Users/john.fehr/.javacpp/cache/ffmpeg-5.0-1.5.7-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/ffmpeg/macosx-x86_64/libavutil.57.dylib:
	@rpath/libavutil.57.dylib (compatibility version 57.0.0, current version 57.17.100)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/libx11/lib/libX11.6.dylib (compatibility version 11.0.0, current version 11.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
	/System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.2.0, current version 1.5.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1069.24.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
(base) Johns-iMac:t john.fehr$ 

```

Not sure why I didn't see this  yesterday, maybe I had my own build cached. (Cleared all my caches before doing a fresh build of my own code today.) Should i open a new issue for this or should I reopen this?

_Originally posted by @jfehr67 in https://github.com/bytedeco/javacpp-presets/issues/1136#issuecomment-1022457801_

**Comment by saudet** [comment] 2022-01-27 03:52
Duplicate of #1136

**Closed by saudet** 2022-01-27 03:52 UTC
Labels: bug, duplicate

**Comment by jfehr67** [comment] 2022-01-27 04:02
Shouldn't this have been fixed in the latest snapshot? I'm still getting the X11 error...
