### ISSUE TITLE
Failed to load for opencv_videoio343 in Windows 7

### ISSUE THREAD

**Issue by helppass** [bytedeco/javacpp-presets#731] opened 2019-05-23 04:53 UTC
Failed to load for opencv_videoio343 in windows 7
include 3.4.0-1.4、3.4.1-1.4.1、3.4.2-1.4.2、3.4.3-1.4.3、……
but it's ok in windows 10。
and use 3.2.0-1.3, it's work well in windows 7 and windows 10

the Loader's log:
……
2019-05-23 10:07:32.328 DEBUG org.bytedeco.javacpp.Loader sche-1 Creating symbolic link to C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\opencv_imgproc343.dll
2019-05-23 10:07:32.336 DEBUG org.bytedeco.javacpp.Loader sche-1 Creating symbolic link to C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\opencv_imgcodecs343.dll
2019-05-23 10:07:32.343 DEBUG org.bytedeco.javacpp.Loader sche-1 Loading C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\opencv_videoio343.dll
2019-05-23 10:07:32.910 DEBUG org.bytedeco.javacpp.Loader sche-1 Failed to load C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\opencv_videoio343.dll: java.lang.UnsatisfiedLinkError: C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\opencv_videoio343.dll: Can't find dependent libraries
2019-05-23 10:07:32.933 DEBUG org.bytedeco.javacpp.Loader sche-1 Loading C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\opencv_videoio343.dll
2019-05-23 10:07:32.933 DEBUG org.bytedeco.javacpp.Loader sche-1 Failed to load C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\opencv_videoio343.dll: java.lang.UnsatisfiedLinkError: C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\opencv_videoio343.dll: Can't find dependent libraries
2019-05-23 10:07:32.957 DEBUG org.bytedeco.javacpp.Loader sche-1 Loading C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\opencv_videoio343.dll
2019-05-23 10:07:32.957 DEBUG org.bytedeco.javacpp.Loader sche-1 Failed to load C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\opencv_videoio343.dll: java.lang.UnsatisfiedLinkError: C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\opencv_videoio343.dll: Can't find dependent libraries
2019-05-23 10:07:32.957 DEBUG org.bytedeco.javacpp.Loader sche-1 Loading library opencv_videoio343
2019-05-23 10:07:32.980 DEBUG org.bytedeco.javacpp.Loader sche-1 Failed to load for opencv_videoio343: java.lang.UnsatisfiedLinkError: no opencv_videoio343 in java.library.path
2019-05-23 10:07:32.980 DEBUG org.bytedeco.javacpp.Loader sche-1 Loading C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jniopencv_videoio.dll
2019-05-23 10:07:33.004 DEBUG org.bytedeco.javacpp.Loader sche-1 Failed to load C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jniopencv_videoio.dll: java.lang.UnsatisfiedLinkError: C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jniopencv_videoio.dll: Can't find dependent libraries
2019-05-23 10:07:33.004 DEBUG org.bytedeco.javacpp.Loader sche-1 Loading C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jniopencv_videoio.dll
2019-05-23 10:07:33.004 DEBUG org.bytedeco.javacpp.Loader sche-1 Failed to load C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jniopencv_videoio.dll: java.lang.UnsatisfiedLinkError: C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jniopencv_videoio.dll: Can't find dependent libraries
2019-05-23 10:07:33.004 DEBUG org.bytedeco.javacpp.Loader sche-1 Loading C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jniopencv_videoio.dll
2019-05-23 10:07:33.027 DEBUG org.bytedeco.javacpp.Loader sche-1 Failed to load C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jniopencv_videoio.dll: java.lang.UnsatisfiedLinkError: C:\Users\ChengFan\.javacpp\cache\opencv-3.4.3-1.4.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jniopencv_videoio.dll: Can't find dependent libraries
2019-05-23 10:07:33.027 DEBUG org.bytedeco.javacpp.Loader sche-1 Loading library jniopencv_videoio
2019-05-23 10:07:33.027 DEBUG org.bytedeco.javacpp.Loader sche-1 Failed to load for jniopencv_videoio: java.lang.UnsatisfiedLinkError: no jniopencv_videoio in java.library.path
……

**Comment by saudet** [comment] 2019-05-23 05:58
Could you try again with the latest version?

**Comment by helppass** [comment] 2019-05-23 06:53
> 
> Could you try again with the latest version?

"4.0.1-1.4.4" is ok in windows 7

**Comment by helppass** [comment] 2019-05-23 07:13
"4.01-1.5" windows-x86_64 
code:
byte[] data……
Mat matData = new Mat(data);

throw a exception:

java.lang.UnsatisfiedLinkError: Platform "windows-x86_64" not supported by class org.bytedeco.opencv.opencv_core.AbstractArray

**Comment by saudet** [comment] 2019-05-24 08:31
I've just double checked, and this sample code works just fine on my installation of Windows 10:
https://github.com/bytedeco/javacpp-presets/tree/1.5/opencv/samples
I can't fix what isn't broken! You'll need to provide more information about how to reproduce that.

**Comment by saudet** [comment] 2019-05-24 08:40
Duplicate of #606

**Closed by saudet** 2019-05-24 08:40 UTC
Labels: bug, duplicate
