### ISSUE TITLE
Unstaisfield link error while running javacv on raspberry pi 2 

### ISSUE THREAD

**Issue by PRCV** [bytedeco/javacpp-presets#60] opened 2015-06-23 05:31 UTC
I follow this installation as i need perticular version of opencv i.e 2.4.9

http://random-tinkering.rhcloud.com/?p=68

I ran the opencv example program successfully given on above link.

Then i tried to run sample javacv program provided on following link 

https://github.com/bytedeco/javacv

i add necessary jar files and libopencv_java249.so file to the sample project  

import static org.bytedeco.javacpp.opencv_core.*;
import static org.bytedeco.javacpp.opencv_imgproc.*;
import static org.bytedeco.javacpp.opencv_highgui.*;

public class Smoother {
    public static void smooth(String filename) { 
        IplImage image = cvLoadImage(filename);
        if (image != null) {
            cvSmooth(image, image);
            cvSaveImage(filename, image);
            cvReleaseImage(image);
        }
    }
}
it ran successfully on ubuntu 14 but giving this error on raspbian 
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1119)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:536)
    at org.bytedeco.javacpp.Loader.load(Loader.java:411)
    at org.bytedeco.javacpp.Loader.load(Loader.java:354)
    at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:340)
    at org.bytedeco.javacpp.Loader.load(Loader.java:386)
    at org.bytedeco.javacpp.Loader.load(Loader.java:354)
    at org.bytedeco.javacpp.opencv_highgui.<clinit>(opencv_highgui.java:13)
    at javacvproj.JavacvProj.main(JavacvProj.java:31)
Caused by: java.lang.UnsatisfiedLinkError: no tbb in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1119)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:536)
    at org.bytedeco.javacpp.Loader.load(Loader.java:402)
    ... 8 more
Java Result: 1

**Comment by saudet** [comment] 2015-06-23 05:48
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/37

**Closed by saudet** 2015-06-23 05:48 UTC
Labels: duplicate
