### ISSUE TITLE
Javacpp-presets for IOS ( especially ffmpeg )

### ISSUE THREAD

**Issue by eix128** [bytedeco/javacpp-presets#1159] opened 2022-03-04 13:37 UTC
hi , i  want to use javacpp-presets with RoboVM.
I cant use ffmpeg libraries.
Is there any way to use these libraries on IOS with RoboVM ?

**Comment by saudet** [comment] 2022-03-04 13:38
We just need to update the cppbuild.sh script. Please give it a try!

**Comment by saudet** [comment] 2022-03-05 01:49
Duplicate of #235

**Closed by saudet** 2022-03-05 01:49 UTC
Labels: duplicate, enhancement
