### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by a610569731** [bytedeco/javacpp-presets#52] opened 2015-05-09 14:34 UTC
Part of the mobile phone will appear  android  SDK ：15 

```
    AndroidRuntime   java.lang.ExceptionInInitializerError
#8765   05-09 21:52:17.710  12329   E   AndroidRuntime           at com.qd.recorder.FFmpegFrameRecorder.(FFmpegFrameRecorder.java:179)
#8766   05-09 21:52:17.710  12329   E   AndroidRuntime           at com.qd.recorder.RecordActivity2.initRecorder(RecordActivity2.java:314)
#8767   05-09 21:52:17.710  12329   E   AndroidRuntime           at com.qd.recorder.RecordActivity2.startRecording(RecordActivity2.java:346)
#8768   05-09 21:52:17.710  12329   E   AndroidRuntime           at com.qd.recorder.RecordActivity2.initLayout(RecordActivity2.java:288)
#8769   05-09 21:52:17.710  12329   E   AndroidRuntime           at com.qd.recorder.RecordActivity2.onCreate(RecordActivity2.java:182)
#8770   05-09 21:52:17.710  12329   E   AndroidRuntime           at android.app.Activity.performCreate(Activity.java:4470)
#8771   05-09 21:52:17.710  12329   E   AndroidRuntime           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
#8772   05-09 21:52:17.710  12329   E   AndroidRuntime           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1929)
#8773   05-09 21:52:17.710  12329   E   AndroidRuntime           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1990)
#8774   05-09 21:52:17.710  12329   E   AndroidRuntime           at android.app.ActivityThread.access$600(ActivityThread.java:124)
#8775   05-09 21:52:17.710  12329   E   AndroidRuntime           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1148)
#8776   05-09 21:52:17.710  12329   E   AndroidRuntime           at android.os.Handler.dispatchMessage(Handler.java:99)
#8777   05-09 21:52:17.710  12329   E   AndroidRuntime           at android.os.Looper.loop(Looper.java:137)
#8778   05-09 21:52:17.710  12329   E   AndroidRuntime           at android.app.ActivityThread.main(ActivityThread.java:4451)
#8779   05-09 21:52:17.710  12329   E   AndroidRuntime           at java.lang.reflect.Method.invokeNative(Native Method)
#8780   05-09 21:52:17.710  12329   E   AndroidRuntime           at java.lang.reflect.Method.invoke(Method.java:511)
#8781   05-09 21:52:17.710  12329   E   AndroidRuntime           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
#8782   05-09 21:52:17.710  12329   E   AndroidRuntime           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
#8783   05-09 21:52:17.710  12329   E   AndroidRuntime           at dalvik.system.NativeStart.main(Native Method)
#8784   05-09 21:52:17.710  12329   E   AndroidRuntime   Caused by: java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
#8785   05-09 21:52:17.710  12329   E   AndroidRuntime           at org.bytedeco.javacpp.Loader.load(Loader.java:388)
#8786   05-09 21:52:17.710  12329   E   AndroidRuntime           at org.bytedeco.javacpp.Loader.load(Loader.java:354)
#8787   05-09 21:52:17.710  12329   E   AndroidRuntime           at org.bytedeco.javacpp.avcodec$AVPacket.(avcodec.java:1405)
#8788   05-09 21:52:17.710  12329   E   AndroidRuntime           ... 19 more
#8789   05-09 21:52:17.710  12329   E   AndroidRuntime   Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
#8790   05-09 21:52:17.710  12329   E   AndroidRuntime           at java.lang.Class.classForName(Native Method)
#8791   05-09 21:52:17.710  12329   E   AndroidRuntime           at java.lang.Class.forName(Class.java:217)
#8792   05-09 21:52:17.710  12329   E   AndroidRuntime           at org.bytedeco.javacpp.Loader.load(Loader.java:386)
#8793   05-09 21:52:17.710  12329   E   AndroidRuntime           ... 21 more
#8794   05-09 21:52:17.710  12329   E   AndroidRuntime   Caused by: java.lang.NoClassDefFoundError: org/bytedeco/javacpp/avutil
#8795   05-09 21:52:17.710  12329   E   AndroidRuntime           ... 24 more
#8796   05-09 21:52:17.710  12329   E   AndroidRuntime   Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
#8797   05-09 21:52:17.710  12329   E   AndroidRuntime           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
#8798   05-09 21:52:17.710  12329   E   AndroidRuntime           at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
#8799   05-09 21:52:17.710  12329   E   AndroidRuntime           at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
#8800   05-09 21:52:17.710  12329   E   AndroidRuntime           ... 24 more
```

**Comment by saudet** [comment] 2015-05-10 00:05
Please try to follow the instructions here:
https://github.com/bytedeco/javacpp-presets/#manual-installation

**Comment by a610569731** [comment] 2015-05-10 12:50
Ask how to solve

**Comment by saudet** [comment] 2015-05-10 12:52
Following the installation instructions should solve this issue. If they do not, then please provide more information about your device, etc.

**Comment by a610569731** [comment] 2015-05-10 13:10
x86 and arm
Or java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil  

MTK MT6732   ARMv8

**Comment by a610569731** [comment] 2015-05-10 13:11
I need your help on the line app

**Comment by saudet** [comment] 2015-05-10 13:20
Maybe it has something to do with ProGuard:
https://github.com/bytedeco/javacv/wiki/Configuring-Proguard-for-JavaCV

**Comment by a610569731** [comment] 2015-05-10 13:25
NO ProGuard   Can compile  android arm64-v8a     javacv-bin linux-x86_64  libavformat.so.56 android  Not recognized

**Comment by a610569731** [comment] 2015-05-10 13:38
dlopen("/data/app-lib/com.qd.videorecorder-1/libjniavutil.so") failed: dlopen failed: cannot locate symbol "av_fopen_utf8" referenced by "libjniavutil.so"...

**Comment by saudet** [comment] 2015-05-10 23:58
So you need ARM 64-bit binaries? Could you provide the necessary changes
for that? It would help a lot, thanks!

**Comment by a610569731** [comment] 2015-05-11 06:56
build  error [ERROR] Failed to execute JavaCPP Builder: Could not parse "libavutil/avutil.h": File does not exist  ubantu 64 How to compile

**Comment by saudet** [comment] 2015-05-11 11:10
You're going to need to modify and run `cppbuild.sh` too:
https://github.com/bytedeco/javacpp-presets#cppbuild-scripts
And also add a new android-arm64 or something platform to JavaCPP:
https://github.com/bytedeco/javacpp/tree/master/src/main/resources/org/bytedeco/javacpp/properties

**Comment by saudet** [comment] 2015-07-17 14:01
Could you try again with version 1.0 and let me know if you get the same error? Thanks!

**Comment by arvind-das** [comment] 2015-09-26 09:16
Hi Saudet, I am getting the same error. I am on version 1.0 
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:270)
	at org.bytedeco.javacpp.Loader.load(Loader.java:390)
	at org.bytedeco.javacpp.Loader.load(Loader.java:358)
	at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2539)
	at com.rrdtech.recorder.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:381)
	at com.rrdtech.recorder.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:375)
	at com.rrdtech.recorder.javacv.CustomFFmpegFileSystemRecorder.startRecord(CustomFFmpegFileSystemRecorder.java:49)
	at com.rrdtech.api.reordingapp.App.main(App.java:17)
Running on Raspberry Pi 2 with ubuntu installed on it. 

Any ideas ?
Thanks!

**Comment by saudet** [comment] 2015-09-26 11:21
@arvind-das see issue #37

**Comment by arvind-das** [comment] 2015-09-29 13:34
Thanks but no success here, looks like I need to spend more time one this as this seems to be the issue with most people. Will not make hurry now. After setting up, presets and installing opencv correctly , on building javacv, getting this error:

```[ERROR] Failed to execute goal on project javacv: Could not resolve dependencies for project org.bytedeco:javacv:jar:1.0: The following artifacts could not be resolved: org.bytedeco.javacpp-presets:ffmpeg:jar:linux-arm:2.7.1-1.0, org.bytedeco.javacpp-presets:flycapture:jar:linux-arm:2.7.3.19-1.0, org.bytedeco.javacpp-presets:libdc1394:jar:linux-arm:2.2.3-1.0, org.bytedeco.javacpp-presets:libfreenect:jar:linux-arm:0.5.2-1.0, org.bytedeco.javacpp-presets:videoinput:jar:linux-arm:0.200-1.0, org.bytedeco.javacpp-presets:artoolkitplus:jar:linux-arm:2.3.1-1.0, org.bytedeco.javacpp-presets:opencv:jar:linux-arm:3.0.0-1.0, org.bytedeco.javacpp-presets:flandmark:jar:linux-arm:1.07-1.0: Failure to find org.bytedeco.javacpp-presets:ffmpeg:jar:linux-arm:2.7.1-1.0 in http://repo.maven.apache.org/maven2```

**Comment by arvind-das** [comment] 2015-10-02 12:23
Hi @saudet , I successfully installed javacpp-presets. OpenCV-3.0.0 and javacv 1.0. The newly generated ffmpeg and other packages on the raspberry pi now contains above missing class "org.bytedeco.javacpp.avutil" . Here is the link to all those generated files residing in my pi's local mvn folder .m2 .
[link to files!]
(https://www.dropbox.com/sh/fo4avpmlijsxf4f/AACx7Y_I2E2UIkTm5PIBDIbMa?dl=0)

But javacv 1.0 is still not building saying the above error that it could not find dependencies .
![example_screenshot](https://cloud.githubusercontent.com/assets/1614392/10246300/8e7302b0-692d-11e5-8a22-8c6a001e0f28.png)

**Comment by saudet** [comment] 2015-10-03 02:08
There's still no file named `ffmpeg-2.7.1-1.0-linux-arm.jar`! You need a file named `ffmpeg-2.7.1-1.0-linux-arm.jar`.

**Comment by arvind-das** [comment] 2015-10-04 06:57
Okay, but isn't it that, required class files should be present in the jars for supporting execution. So what I did is, copied >ffmpeg-2.7.1-1.0.jar  to >ffmpeg-2.7.1-1.0-linux-arm.jar which makes it present there and javacv build on pi is a success , but the problem remains same,
>java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil

Please help me out!

**Comment by saudet** [comment] 2015-10-04 07:01
@arvind-das No that's not going to work. Like I said, see issue #37.

**Comment by arvind-das** [comment] 2015-10-04 07:17
@saudet Okay, but that is not helping either, I am not sure why these files are not getting generated even if everything compiled correctly. Looks like its time to Yoga, take a fresh breathe and come back for me. :)

**Comment by saudet** [comment] 2015-10-04 07:19
@arvind-das Ok, so what do your modifications to the `cppbuild.sh` file look like?

**Comment by arvind-das** [comment] 2015-10-04 07:29
>linux-x86)
        CC="gcc -m32" CXX="g++ -m32" $CMAKE -DCMAKE_INSTALL_PREFIX=.. -DENABLE_SSE3=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_JASPER=ON -DBUILD_JPEG=ON -DBUILD_WEBP=ON -DBUILD_OPENEXR=ON -DBUILD_PNG=ON -DBUILD_TIFF=ON -DBUILD_ZLIB=ON -DBUILD_opencv_java=OFF -DBUILD_opencv_python2=OFF -DENABLE_PRECOMPILED_HEADERS=OFF -DWITH_1394=OFF -DWITH_FFMPEG=OFF -DWITH_GSTREAMER=OFF -DWITH_OPENMP=ON -DWITH_CUDA=OFF -DWITH_OPENCL=OFF -DWITH_IPP=OFF # -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib-$OPENCV_VERSION/modules
        make -j4
        make install/strip
        ;;
    linux-arm)
        CC="gcc -m32" CXX="g++ -m32" $CMAKE -DCMAKE_INSTALL_PREFIX=.. -DENABLE_SSE3=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_JASP$
        make -j4
        make install/strip
        ;;

    linux-x86_64)
        CC="gcc -m64" CXX="g++ -m64" $CMAKE -DCMAKE_INSTALL_PREFIX=.. -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_JASPER=ON -DBUILD_JPEG=ON -DBUILD_WEBP=ON -DBUILD_OPENEXR=ON -DBUILD_PNG=ON -DBUILD_TIFF=ON -DBUILD_ZLIB=ON -DBUILD_opencv_java=OFF -DBUILD_opencv_python2=OFF -DENABLE_PRECOMPILED_HEADERS=OFF -DWITH_1394=OFF -DWITH_FFMPEG=OFF -DWITH_GSTREAMER=OFF -DWITH_OPENMP=ON -DWITH_CUDA=OFF -DWITH_OPENCL=OFF -DWITH_IPP=OFF # -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib-$OPENCV_VERSION/modules
        make -j4
        make install/strip
        ;;

**Comment by saudet** [comment] 2015-10-04 07:31
That's for OpenCV. You're trying to use FFmpeg. You need to do the same for FFmpeg's `cppbuild.sh` script file.

**Comment by arvind-das** [comment] 2015-10-04 07:34
Oops! my  bad, will do that right away, I thought I just need to fix with opencv , platform for rest will be detected automatically.

**Comment by saudet** [comment] 2015-10-12 03:10
If anyone would like to work on binaries for the `android-arm64`, please let me know! Thank you

**Comment by arvind-das** [comment] 2015-10-16 14:03
I am gaining some speed with installing cross tool compiler, no success yet but I can see the sun. Will update once my installation is done.

**Comment by saudet** [comment] 2015-10-18 06:12
Great, thanks!!

**Comment by lstjsuperman** [comment] 2015-10-26 09:29
I'm facing the same problem. Has anyone resolved this?
10-26 17:23:46.406 8833-8873/com.qd.videorecorder E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-26 17:23:46.406 8833-8873/com.qd.videorecorder E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
10-26 17:23:46.406 8833-8873/com.qd.videorecorder E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
10-26 17:23:46.406 8833-8873/com.qd.videorecorder E/AndroidRuntime:     at java.lang.Class.classForName(Native Method) 
10-26 17:23:46.406 8833-8873/com.qd.videorecorder E/AndroidRuntime:     at java.lang.Class.forName(Class.java:251) 
10-26 17:23:46.406 8833-8873/com.qd.videorecorder E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:390) 
10-26 17:23:46.406 8833-8873/com.qd.videorecorder E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:358) 
10-26 17:23:46.406 8833-8873/com.qd.videorecorder E/AndroidRuntime:     at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1407) 
10-26 17:23:46.406 8833-8873/com.qd.videorecorder E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149) 
10-26 17:23:46.406 8833-8873/com.qd.videorecorder E/AndroidRuntime:     at com.qd.recorder.FFmpegRecorderActivity.initVideoRecorder(FFmpegRecorderActivity.java:457) 
10-26 17:23:46.406 8833-8873/com.qd.videorecorder E/AndroidRuntime:     at com.qd.recorder.FFmpegRecorderActivity.access$900(FFmpegRecorderActivity.java:78) 
10-26 17:23:46.406 8833-8873/com.qd.videorecorder E/AndroidRuntime:     at com.qd.recorder.FFmpegRecorderActivity$2.doInBackground(FFmpegRecorderActivity.java:363) 
10-26 17:23:46.406 8833-8873/com.qd.videorecorder E/AndroidRuntime:     at com.qd.recorder.FFmpegRecorderActivity$2.doInBackground(FFmpegRecorderActivity.java:356) 
10-26 17:23:46.406 8833-8873/com.qd.videorecorder E/AndroidRuntime:     at android.os.AsyncTask$2.call(AsyncTask.java:288) 
10-26 17:23:46.406 8833-8873/com.qd.videorecorder E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
10-26 17:23:46.406 8833-8873/com.qd.videorecorder E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
10-26 17:23:46.406 8833-8873/com.qd.videorecorder E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
10-26 17:23:46.406 8833-8873/com.qd.videorecorder E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
10-26 17:23:46.406 8833-8873/com.qd.videorecorder E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:841)

**Comment by saudet** [comment] 2015-10-26 11:45
@lstjsuperman That looks like a problem with ProGuard. Make sure to disable ProGuard, and please post on the relevant threads, thank you.

**Comment by lilac** [comment] 2016-04-30 14:47
@saudet Is adding android-arm64 platform support to the cppbuild the only solution to this problem? Any easy workaround?

**Comment by saudet** [comment] 2016-05-02 11:44
64-bit Android works just fine with 32-bit binaries. There's nothing special you need to do.

**Comment by pradeep2929** [comment] 2016-11-04 15:19
I am getting crash in Android 5.1, Native platform armeabi-v7a,  CPU model MSM8916. The model suggests it should support 32 bit .so files. But it crashes. I downloaded the most recent javacpp release, it has armeabi support only. Is there a release package available for download for 64bit chips?

java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
	at org.bytedeco.javacv.FFmpegFrameFilter.startUnsafe(FFmpegFrameFilter.java:158)
	at org.bytedeco.javacv.FFmpegFrameFilter.start(FFmpegFrameFilter.java:154)

**Comment by viettanbkdn** [comment] 2016-12-07 02:48
Could not build android project:
Task: 

> :app:compileDevelopDebugJavaWithJavac

Error:

> error: cannot access avutil
>                 recorder.record(yuvImage);
>                         ^
>   class file for org.bytedeco.javacpp.avutil not found

App config:

> androidBuildToolsVersion = "25.0.1"
> androidMinSdkVersion = 19
> androidTargetSdkVersion = 25
> androidCompileSdkVersion = 25


>     compile project(':openCVLibrary310')
> 
>     compile files('libs/javacv-1.2.jar')
>     compile files('libs/javacpp-1.2.7.jar')
>     compile files('libs/opencv-3.1.0-1.2-android-arm.jar')
>     compile files('libs/opencv-3.1.0-1.2-android-x86.jar')
>     compile files('libs/ffmpeg-3.1.2-1.2-android-arm.jar')
>     compile files('libs/ffmpeg-3.1.2-1.2-android-x86.jar')

**Comment by saudet** [comment] 2016-12-07 08:38
@viettanbkdn You forgot to include:
```groovy
compile files('libs/opencv-3.1.0-1.2.jar')
compile files('libs/ffmpeg-3.1.2-1.2.jar')
```

**Comment by viettanbkdn** [comment] 2016-12-07 08:48
@saudet do we need to use 
```
compile files('libs/opencv-3.1.0-1.2-android-arm.jar')
compile files('libs/opencv-3.1.0-1.2-android-x86.jar')
compile files('libs/ffmpeg-3.1.2-1.2-android-arm.jar')
compile files('libs/ffmpeg-3.1.2-1.2-android-x86.jar')
```
if we use 
```
compile files('libs/opencv-3.1.0-1.2.jar')
compile files('libs/ffmpeg-3.1.2-1.2.jar')
```

**Comment by viettanbkdn** [comment] 2016-12-07 09:23
@saudet sorry but how can I fixed the issue: 

> "xxx" is 32-bit instead of 64-bit 

Tried to find the solution but got nothing. Could you please help me?

**Comment by saudet** [comment] 2016-12-07 09:25
@viettanbkdn It looks like for some reason you need 64-bit binaries. There isn't currently a build for that. Someone needs to work on that. If you could help with doing that, it would be great! Contributions are welcome.

**Comment by nickbernz** [comment] 2017-02-20 17:25
Salut,

As per today, what is the status with ffmpeg and arm64. I definitly needs them and how could I help?

merci

**Comment by saudet** [comment] 2017-02-21 07:16
@nickbernz Help is welcome!

**Comment by rubi-sharma** [comment] 2017-09-01 04:25
I need help to build .so files for android-arm64.

**Comment by saudet** [comment] 2018-02-27 03:08
64-bit builds for Android (as the "android-arm64" and "android-x86_64" platforms) are now available, so please give it a try! Binaries for 1.4.1-SNAPSHOT can be downloaded from the snapshot repository: http://bytedeco.org/builds/

**Comment by saudet** [comment] 2018-04-09 06:02
Artifacts have now been released as version 1.4.1. Enjoy and thanks for your patience!

**Closed by saudet** 2018-04-09 06:02 UTC
Labels: enhancement

**Comment by saudet** [comment] 2019-01-23 23:19
@girishnr1 HDF5 isn't supported on Android.

**Comment by girishnr1** [comment] 2019-01-24 00:41
The error is on windows machine ( windows 7).   
DL4J is setup using instructions under: 
https://deeplearning4j.org/docs/latest/deeplearning4j-quickstart
I see that javacpp-1.3.1.jar,  Is there an updated version that supports hdf5?

**Comment by saudet** [comment] 2019-01-24 00:46
@girishnr1 Please upgrade to the latest version, and if you're still having problems, please ask on the support channels of Deeplearning4j, not here.
