### ISSUE TITLE
[GSL] How to compile .so file for armeabi-v7a/ arm64-v8a?

### ISSUE THREAD

**Issue by houxg** [bytedeco/javacpp-presets#167] opened 2016-02-29 03:23 UTC
Thank you for your fantastic work!
I am trying to use gsl in android, however I only get the .so file for armeabi. Is there any way to compile it for armeabi-v7a/ arm64-v8a? I'm so sorry that I'm not familiar with make script otherwise I could do it by myself :(

**Comment by saudet** [comment] 2016-02-29 14:22
It's already compiled for armeabi-v7a, so you could use that. It also works for arm64.

**Comment by saudet** [comment] 2016-05-27 23:52
And w.r.t to arm64 binaries, marking as duplicate of #52. If interested in making a contribution, please continue the discussion there.

**Closed by saudet** 2016-05-27 23:52 UTC
Labels: duplicate, enhancement, question

**Comment by akhilc1** [comment] 2016-07-08 07:48
E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.a.a, PID: 3520
                                                               java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
                                                                   at org.bytedeco.javacpp.avutil.av_frame_alloc(Native Method)
                                                                   at org.bytedeco.javacv.FFmpegFrameFilter.startUnsafe(FFmpegFrameFilter.java:158)
                                                                   at org.bytedeco.javacv.FFmpegFrameFilter.start(FFmpegFrameFilter.java:154)

I am getting this crash on arm64 device moto x style running marshmallow, but not on nexus 5 arm 32 bit. I guess 32 bit binaries does not work on some 64 bit devices. @saudet

**Comment by saudet** [comment] 2018-02-27 03:11
64-bit builds for Android (as the "android-arm64" and "android-x86_64" platforms) are now available, so please give it a try! Binaries for 1.4.1-SNAPSHOT can be downloaded from the snapshot repository: http://bytedeco.org/builds/
