### ISSUE TITLE
FFmpeg without GPL module

### ISSUE THREAD

**Issue by tmurakam** [bytedeco/javacpp-presets#948] opened 2020-09-20 08:28 UTC
Current ffmpeg module is built with --enable-gpl flag, so it contains GPL module, and it is hard to use with closed source / proprietary software.

I hope non-GPL version of the FFmpeg presets.
I'm working on it and send a pull request later.

**Comment by saudet** [comment] 2020-09-20 08:32
Duplicate of #419

**Closed by saudet** 2020-09-20 08:32 UTC
Labels: duplicate, enhancement
