### ISSUE TITLE
How to define MacOS Universal2 builds in cppbuild.sh?

### ISSUE THREAD

**Issue by cansik** [bytedeco/javacpp-presets#1234] opened 2022-09-21 13:13 UTC
I am currently working on bringing my knowledge from [librealsense2 on Apple Silicon](https://github.com/cansik/pyrealsense2-macosx) to the Java world. It is already compiling by using XCode from the command line (https://github.com/cansik/javacpp-presets/commit/d1152f1ed61ce19136ec0c37ca084d8a09951e1f).

Now the question is how this can be included in the current build pipeline. As Github Actions do not have M1 runners yet, it would be possible to use a MacOS Intel runner and create an Universal2 binary (as my python lib does).

But how should this be implemented in the cppbuild.sh? Or how should this be solved?

**Comment by saudet** [comment] 2022-09-21 13:44
Duplicate of #1069

**Closed by saudet** 2022-09-21 13:44 UTC
Labels: duplicate, enhancement
