### ISSUE TITLE
Fatal signal 11 error

### ISSUE THREAD

**Issue by pedroSG94** [bytedeco/javacpp-presets#218] opened 2016-05-13 08:01 UTC
Hi.
I'm working with javacv and ffmpeg compiled with this guide:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments

When i try create a FFmpegFrameRecorder instance i get this error:
`A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 10239`
The app only crash with android6  when i test in android 4.4 and 5.0 this run good. I tried too with 2 device with android 6 and with avd but crash
I tried a solution found in internet but dont work for me:
-add this line in manifest:
android:hardwareAccelerated="false"

**Comment by saudet** [comment] 2016-05-13 08:06
Please try to use those binaries instead:
```
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp/1.2-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/ffmpeg/2.8.5-1.2-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacv/1.2-SNAPSHOT/
```
Duplicate of https://github.com/bytedeco/javacv/issues/245

**Closed by saudet** 2016-05-13 08:06 UTC
Labels: bug, duplicate

**Comment by pedroSG94** [comment] 2016-05-13 08:17
I get this error know:
```
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/bytedeco/javacpp/avfilter.class
```

build.gradle code:

```
dependencies{
compile files('libs/javacv-1.2-20160511.223725-4.jar')
  compile files('libs/javacpp-1.2-20160506.061834-10.jar')
  compile files('libs/ffmpeg-2.8.5-1.2-20160220.074737-2.jar')
  provided files('libs/ffmpeg-2.8.5-1.2-20160220.074737-2-android-arm.jar')
}
```

**Comment by pedroSG94** [comment] 2016-05-13 08:24
Dont work for me i tried with the binaries ffmpeg 2.8.5 and 3.0.1

**Comment by saudet** [comment] 2016-05-13 08:25
Well, it works for others, so please provide more details about your in bytedeco/javacv#245
