### ISSUE TITLE
Null Pointer exception in OpenCV mat.createIndexer() function

### ISSUE THREAD

**Issue by PatrickPenguinTurtle** [bytedeco/javacpp-presets#239] opened 2016-06-21 18:10 UTC
While trying to get an indexer for an org.bytedeco.javacpp.opencv_core.Mat a null pointer exception occurs. 
<img width="1145" alt="screen shot 2016-06-21 at 2 00 33 pm" src="https://cloud.githubusercontent.com/assets/16124010/16240747/8dab80f0-37b8-11e6-93ff-c1d015814cef.png">
A simplified (irrelevant lines of code removed) version of the code is: 
<img width="634" alt="screen shot 2016-06-21 at 2 04 05 pm" src="https://cloud.githubusercontent.com/assets/16124010/16240844/1065f110-37b9-11e6-8fde-ea4ad9e8716e.png">

System details Mac osx 10.11.5 with the most recent version of the library downloaded using gradle from the maven repository today, Tuesday June 21st 2016 at 2pm. 

I need to look at all channels of each pixel, one pixel at a time and know the location of that pixel (row,col). Speed is not particularly important and this was the simpler version of using an indexer that I saw. 

Edit: This probably belongs in the javacv project. Reposting in there.

**Comment by saudet** [comment] 2016-06-26 08:45
Duplicate of https://github.com/bytedeco/javacv/issues/437

**Closed by saudet** 2016-06-26 08:45 UTC
