### ISSUE TITLE
Unsatisfied link error when I try to run app build for arm64, x86_x64 while arm version is working fine.

### ISSUE THREAD

**Issue by faisal3413** [bytedeco/javacpp-presets#762] opened 2019-07-15 11:29 UTC
Hi Dears,

I am seeking for a help is there any convenient way to add support for arm64 and x86_x64 architectures via gradle dependencies. My app is working fine if I build only for arm (javacpp-presets) with javacv-platform version 1.4

Below is my gradle file.

```
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'io.fabric'

android {
    compileSdkVersion 28
    buildToolsVersion '28.0.3'

    defaultConfig {
        applicationId "com.qc.managementprojects"
        multiDexEnabled true
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 5
//        ndk {
//            abiFilters
//                    "armeabi-v7a"
//                    'x86'
//                    'x86_64'
//        }
    }

    buildTypes {
        release {
            minifyEnabled false  // worked on true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    lintOptions {
        abortOnError false        // true by default
        checkAllWarnings false
        checkReleaseBuilds false
        ignoreWarnings true       // false by default
        quiet true                // false by default
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'

        pickFirst 'lib/armeabi-v7a/libjniavformat.so'
        pickFirst 'lib/armeabi-v7a/libavcodec.so'
        pickFirst 'lib/armeabi-v7a/libpostproc.so'
        pickFirst 'lib/armeabi-v7a/libjniavutil.so'
        pickFirst 'lib/armeabi-v7a/libjnipostproc.so'
        pickFirst 'lib/armeabi-v7a/libswscale.so'
        pickFirst 'lib/armeabi-v7a/libavdevice.so'
        pickFirst 'lib/armeabi-v7a/libavutil.so'
        pickFirst 'lib/armeabi-v7a/libswresample.so'
        pickFirst 'lib/armeabi-v7a/libjniavcodec.so'
        pickFirst 'lib/armeabi-v7a/libjniswresample.so'
        pickFirst 'lib/armeabi-v7a/libjniavfilter.so'
        pickFirst 'lib/armeabi-v7a/libavformat.so'
        pickFirst 'lib/armeabi-v7a/libjniswscale.so'
        pickFirst 'lib/armeabi-v7a/libavfilter.so'
        pickFirst 'lib/armeabi-v7a/libjniavdevice.so'

//        pickFirst 'lib/x86_64/libjniavformat.so'
//        pickFirst 'lib/x86_64/libavcodec.so'
//        pickFirst 'lib/x86_64/libpostproc.so'
//        pickFirst 'lib/x86_64/libjniavutil.so'
//        pickFirst 'lib/x86_64/libjnipostproc.so'
//        pickFirst 'lib/x86_64/libswscale.so'
//        pickFirst 'lib/x86_64/libavdevice.so'
//        pickFirst 'lib/x86_64/libavutil.so'
//        pickFirst 'lib/x86_64/libswresample.so'
//        pickFirst 'lib/x86_64/libjniavcodec.so'
//        pickFirst 'lib/x86_64/libjniswresample.so'
//        pickFirst 'lib/x86_64/libjniavfilter.so'
//        pickFirst 'lib/x86_64/libavformat.so'
//        pickFirst 'lib/x86_64/libjniswscale.so'
//        pickFirst 'lib/x86_64/libavfilter.so'
//        pickFirst 'lib/x86_64/libjniavdevice.so'
//
//        pickFirst 'lib/arm64-v8a/libjniavformat.so'
//        pickFirst 'lib/arm64-v8a/libavcodec.so'
//        pickFirst 'lib/arm64-v8a/libpostproc.so'
//        pickFirst 'lib/arm64-v8a/libjniavutil.so'
//        pickFirst 'lib/arm64-v8a/libjnipostproc.so'
//        pickFirst 'lib/arm64-v8a/libswscale.so'
//        pickFirst 'lib/arm64-v8a/libavdevice.so'
//        pickFirst 'lib/arm64-v8a/libavutil.so'
//        pickFirst 'lib/arm64-v8a/libswresample.so'
//        pickFirst 'lib/arm64-v8a/libjniavcodec.so'
//        pickFirst 'lib/arm64-v8a/libjniswresample.so'
//        pickFirst 'lib/arm64-v8a/libjniavfilter.so'
//        pickFirst 'lib/arm64-v8a/libavformat.so'
//        pickFirst 'lib/arm64-v8a/libjniswscale.so'
//        pickFirst 'lib/arm64-v8a/libavfilter.so'
//        pickFirst 'lib/arm64-v8a/libjniavdevice.so'


//        exclude 'META-INF/services/javax.annotation.processing.Processor'
//        pickFirst 'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.properties'
//        pickFirst 'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.xml'
//        pickFirst 'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.properties'
//        pickFirst 'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.xml'
//        pickFirst 'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.xml'
//        pickFirst 'META-INF/maven/org.bytedeco.javacpp-presets/1.2/javacpp-presets-1.2.pom.xml'
//        pickFirst 'META-INF/maven/org.bytedeco.javacpp-presets/org.bytedeco.javacpp-presets-1.2.pom.xml'
    }
}


repositories {
    mavenCentral()
}

ext {
    versions = [
            'ffmpeg':  '4.0.1-1.4.2'                    //   '3.2.1-1.3'  '4.0.1-1.4.2'  ‎ 4.1.3-1.5.1 
    ]
}

dependencies {

    implementation files('libs/gson-2.3.1.jar')
    implementation files('libs/httpclient-4.3.6.jar')
    implementation files('libs/httpcore-4.3.3.jar')
    implementation files('libs/httpmime-4.3.6.jar')
    implementation files('libs/ksoap2-android-full-2.1.2.jar')
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'com.google.firebase:firebase-core:17.0.0'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'
    implementation 'com.getkeepsafe.relinker:relinker:1.3.1'


    implementation(group: 'org.bytedeco', name: 'javacv-platform', version: '1.5.1') {
        exclude group: 'org.bytedeco.javacpp-presets'
    }
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: versions.ffmpeg
   implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: versions.ffmpeg, classifier: 'android-arm'
  //  implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: versions.ffmpeg, classifier: 'android-arm64'
   // implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: versions.ffmpeg, classifier: 'android-x86_64'
}
apply plugin: 'com.google.gms.google-services'
```

App is working fine if I use

>  javacv-platform version 1.4

Error I got is if I compiled and run the app using 

>   implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: versions.ffmpeg, classifier: 'android-arm64'

>     implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: versions.ffmpeg, classifier: 'android-x86_64'

**Error is**

```
 Caused by: java.lang.NoClassDefFoundError: org.bytedeco.javacpp.avutil
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1103)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1036)
        at org.bytedeco.javacpp.avformat$Write_packet_Pointer_BytePointer_int.<clinit>(avformat.java:640)
        at com.qc.managementprojects.FFmpegFrameRecorder.<clinit>(FFmpegFrameRecorder.java:334)
        at com.qc.managementprojects.FFmpegRecorderActivity.initVideoRecorder(FFmpegRecorderActivity.java:408)
        at com.qc.managementprojects.FFmpegRecorderActivity.access$1700(FFmpegRecorderActivity.java:68)
        at com.qc.managementprojects.FFmpegRecorderActivity$2.doInBackground(FFmpegRecorderActivity.java:318)
        at com.qc.managementprojects.FFmpegRecorderActivity$2.doInBackground(FFmpegRecorderActivity.java:312)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.UnsatisfiedLinkError: No implementation found for long org.bytedeco.javacpp.avutil.AV_NOPTS_VALUE() (tried Java_org_bytedeco_javacpp_avutil_AV_1NOPTS_1VALUE and Java_org_bytedeco_javacpp_avutil_AV_1NOPTS_1VALUE__)
        at org.bytedeco.javacpp.avutil.AV_NOPTS_VALUE(Native Method)
        at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:266)
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1103)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1036)
        at org.bytedeco.javacpp.avcodec.<clinit>(avcodec.java:13)
        at org.bytedeco.javacpp.avcodec.avcodec_register_all(Native Method)
        at com.qc.managementprojects.FFmpegFrameRecorder.tryLoad(FFmpegFrameRecorder.java:124)
        at com.qc.managementprojects.FFmpegFrameRecorder.<clinit>(FFmpegFrameRecorder.java:142)
        at com.qc.managementprojects.FFmpegRecorderActivity.initVideoRecorder(FFmpegRecorderActivity.java:408) 
        at com.qc.managementprojects.FFmpegRecorderActivity.access$1700(FFmpegRecorderActivity.java:68) 
        at com.qc.managementprojects.FFmpegRecorderActivity$2.doInBackground(FFmpegRecorderActivity.java:318) 
        at com.qc.managementprojects.FFmpegRecorderActivity$2.doInBackground(FFmpegRecorderActivity.java:312) 
        at android.os.AsyncTask$2.call(AsyncTask.java:333) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

Sorry for rough gradle file, I just intended to show different approaches I tried.

**Comment by saudet** [comment] 2019-07-15 12:30
I'm afraid there's currently no easier way than adding the dependencies manually like you've been doing, so please keep doing that. To make it easier, we would need to create a plugin for Gradle, so I'll just mark this as a duplicate of issue https://github.com/bytedeco/javacpp/issues/65. Contributions in that sense are very welcome!

**Closed by saudet** 2019-07-15 12:30 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2019-07-16 01:32
If your question is about how to upgrade to 1.5.x though, you'll need to replace `org.bytedeco.javacpp-presets` with `org.bytedeco` as explained here: http://bytedeco.org/news/2019/04/11/beyond-java-and-cpp/

**Comment by faisal3413** [comment] 2019-07-16 08:03
@saudet sorry, my question is how can build for arm64 and x86_x64 to support 64 bit architectures? Like as I am adding a gradle dependency for simple arm/armeabi-v7a. I still did not get any idea from your above references to how to add support for 64 bit architectures  like arm64-v8 and x86_x64? 

If I need to add as jar/.so dependency where I can find corresponding .so/jar files ?
Please help.

**Comment by saudet** [comment] 2019-07-16 08:56
I see. I've added a section for that on this wiki page: https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies#including-binaries-only-for-mobile-platforms

**Comment by faisal3413** [comment] 2019-07-16 10:19
@saudet yes I exactly did the same way as mentioned on the wiki page, but I'm getting Unstaisfied link error when I added below

> implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: versions.ffmpeg, classifier: 'android-arm64'

>  implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: versions.ffmpeg, classifier: 'android-x86_64'

But It works perfectly when I compile with only 

>    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: versions.ffmpeg, classifier: 'android-arm'

Please have a look above on my issue description and guide me. 
Highly appreciating your quick responses :)

**Comment by faisal3413** [comment] 2019-07-16 10:34
Just realised that I forgot to update syntax from `'org.bytedeco.javacpp-presets'` to `'org.bytedeco'` in order to update to 1.5.x

i'll test and update.

**Comment by saudet** [comment] 2020-06-27 01:11
There is also now a plugin for Gradle to exclude by platform names:
https://github.com/bytedeco/gradle-javacpp#the-platform-plugin
If you try it out and find anything missing, please let me know!
