### ISSUE TITLE
Depthai version 2.14.1 crashes

### ISSUE THREAD

**Issue by Grumpy141** [bytedeco/javacpp-presets#1149] opened 2022-02-16 21:45 UTC
Depthai crashes the entire JVM while establishing communication to the device.  Tested on both Mac OS intel 64bit, and Linux armhf.   The crash was the same:    (Version 2.13.3. works fine)

Error Mesage On Mac:

Stack trace (most recent call last) in thread 123145447182336:
#2    Object "libsystem_platform.dylib", at 0x7ff8043f5e2c, in _sigtramp + 28
#1    Object "libdepthai-core.dylib", at 0x13941b16d, in backward::SignalHandling::sig_handler(int, __siginfo*, void*) + 13
#0    Object "libdepthai-core.dylib", at 0x13941b1dc, in backward::SignalHandling::sig_handler(int, __siginfo*, void*) + 124

Error Message On Linux armhf:

Stack trace (most recent call last) in thread 27821:
#2    Object "/lib/arm-linux-gnueabihf/libc.so.6", at 0xb6d5f12f, in 
#1    Object "/home/pi/.javacpp/cache/depthai-linux-armhf.jar/org/bytedeco/depthai/linux-armhf/libdepthai-core.so", at 0x158a7aef, in backward::SignalHandling::sig_handler(int, siginfo_t*, void*)
#0    Object "/home/pi/.javacpp/cache/depthai-linux-armhf.jar/org/bytedeco/depthai/linux-armhf/libdepthai-core.so", at 0x158a5d17, in backward::SignalHandling::handleSignal(int, siginfo_t*, void*)
Segmentation fault (Address not mapped to object [0x4])

**Comment by saudet** [comment] 2022-02-17 00:27
Let's not create a new thread for this, unless/until we know that we're dealing with a different issue.

**Comment by saudet** [comment] 2022-02-17 00:27
Duplicate of #1118

**Closed by saudet** 2022-02-17 00:27 UTC
Labels: bug, duplicate

**Comment by Grumpy141** [comment] 2022-02-17 00:44
It is a different issue.  I am running fine on depthai version 2.13.3, which is what issue #1118 was about.   So they can't be the same issue.

    On Wednesday, February 16, 2022, 05:27:15 PM MST, Samuel Audet ***@***.***> wrote:  
 
 


Let's not create a new thread for this, unless/until we know that we're dealing with a different issue.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by saudet** [comment] 2022-02-17 00:47
It could be the same issue, in C/C++ undefined behavior is undefined behavior, which means a bug does not necessarily affect everyone in the same way.
