### ISSUE TITLE
Trouble using presets/cuda-8.0-6.0-1.3 from clojure

### ISSUE THREAD

**Issue by cnuernber** [bytedeco/javacpp-presets#469] opened 2017-09-29 17:36 UTC
When using 8.0-1.2 version of presets/cuda and running lein deps I see it downloads the platform-specific bindings from maven-central:

Retrieving org/bytedeco/javacpp-presets/cuda/8.0-1.2/cuda-8.0-1.2-linux-x86_64.jar from central

I cannot seem to find these same bindings on maven central when running using lein repl if I upgrade my dependency to 8.0-6.0-1.3.  I was wondering if I am missing a define on the command line or of the platform-specific-binaries will no longer be uploaded to maven central or if this is some clojure-specific issue that I need to sort through.

**Comment by cnuernber** [comment] 2017-09-29 18:49
I found the fix is to use the platform dependency instead of the root dependency.  So concretely:

didn't work:
:dependencies [[org.bytedeco.javacpp-presets/cuda "8.0-6.0-1.3"]]

did work:
:dependencies [[org.bytedeco.javacpp-presets/cuda-platform "8.0-6.0-1.3"]]

**Comment by saudet** [comment] 2017-09-29 23:21
Yes, that should be clear from the README.md file or would you have
something to propose?

**Comment by saudet** [comment] 2017-09-30 08:14
Maybe we could add the necessary lines for Leiningen in the README.md?

**Comment by cnuernber** [comment] 2017-09-30 15:03
https://github.com/bytedeco/javacpp-presets/pull/470

**Comment by saudet** [comment] 2018-01-18 05:13
Closing as duplicate of pull #470. Let's get the pull request in shape for a merge! Thanks

**Closed by saudet** 2018-01-18 05:13 UTC
Labels: duplicate, enhancement
