### ISSUE TITLE
javacv records the camera stream，the console prints warning all the time

### ISSUE THREAD

**Issue by RivsDC** [bytedeco/javacpp-presets#461] opened 2017-09-05 09:37 UTC
new Thread(){
                    public void run() {
                        FrameGrabber grabber = null;
                        try {
                            grabber = FFmpegFrameGrabber.createDefault(cameraInfo.getRtspHD());
                        } catch (org.bytedeco.javacv.FrameGrabber.Exception e2) {
                            e2.printStackTrace();
                        }  
                        grabber.setOption("rtsp_transport", "tcp");
                        grabber.setImageHeight(576);
                        grabber.setImageWidth(720);
                        String path = getPath(cameraInfo.getId());
                        FrameRecorder recorder = null;
                        try {
                            recorder = FrameRecorder.createDefault(path, 720, 576);
                        } catch (org.bytedeco.javacv.FrameRecorder.Exception e2) {
                            e2.printStackTrace();
                        } 
                        recorder.setVideoOption("tune","zerolatency");
                        recorder.setVideoOption("preset","ultrafast");
                        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
                        recorder.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);
                        recorder.setVideoBitrate(400000);
                        recorder.setFormat("flv");  
                        recorder.setFrameRate(25);  
                        recorder.setGopSize(25); 
                        try {  
                            grabber.start();  
                        } catch (Exception e) {  
                            try {  
                                grabber.restart(); 
                            } catch (Exception e1) {  
                                e1.printStackTrace();;  
                            }  
                        }  
                        try {  
                            recorder.start();  
                        } catch (org.bytedeco.javacv.FrameRecorder.Exception e) {  
                            try {  
                                if(recorder!=null)  
                                {  
                                    recorder.stop();  
                                    recorder.start();  
                                }        
                            } catch (org.bytedeco.javacv.FrameRecorder.Exception e1) {  
                                e1.printStackTrace();
                            }  
                        } 
[swscaler @ 000000002b8cd2a0] deprecated pixel format used, make sure you  did set range correctly
[swscaler @ 00000000342a4d80] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 00000000339f3920] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0000000030a29060] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 000000002be31d60] deprecated pixel format used, make sure you did set range correctly

**Comment by saudet** [comment] 2017-09-06 03:28
Duplicate of https://github.com/bytedeco/javacv/issues/780

**Closed by saudet** 2017-09-06 03:28 UTC
Labels: duplicate
