### ISSUE TITLE
I want to reconstruct  implement the pytorch dataset in scala but meet error

### ISSUE THREAD

**Issue by mullerhai** [bytedeco/javacpp-presets#1272] opened 2022-11-29 13:05 UTC
HI, 
        I  think ,we need to do something for  origin  torch.data package implement, these day  I try do  some ,but meet error
I  just want to self defined the dataset and dataloader 
the scala code

macos 
pytorc  lastest
java  11 ,15 
scala 2.12.11

```
package org.bytedeco.pytorch

import org.bytedeco.javacpp._
import org.bytedeco.javacpp.annotation._
import org.bytedeco.pytorch.MNIST.Mode
import org.bytedeco.pytorch.global.torch._


/** The MNIST dataset. */
@Namespace("torch::data::datasets")
@NoOffset
@Properties(inherit = Array(classOf[org.bytedeco.pytorch.presets.torch]))
object MullerMNIST {
//  try Loader.load

  object Mode extends Enumeration {
    type Mode = Value
    //  val name:String
    val kTrain: Mode.Value =Value(0,"kTrain")
    val kTest: Mode.Value = Value(1, "kTest")
    //    var value: Int = 3
    //    def this(v: Int) {
    //      this()
    //      this.value = v
    //    }
    //    def this(e: Mode) {
    //      this()
    //      this.value = e.value
    //    }
    //    def intern: Mode = {
    //      for (e <- values) {
    //
    //        if (e.value == value)
    //          return e
    //      }
    //      this
    //    }
    //    override def toString: String = this.name
  }
  /** The mode in which the dataset is loaded. */

}

@Namespace("torch::data::datasets")
@NoOffset
@Properties(inherit = Array(classOf[org.bytedeco.pytorch.presets.torch]))
class MullerMNIST extends MullerMNISTDataSet(p: Pointer) {

  /** Pointer cast constructor. Invokes {@link Pointer# Pointer ( Pointer )}. */
  def this(p: Pointer) {
    this()
    //    super (p)
  }

  /** Returns the size of the dataset. */
  @ByVal
  @native
  override def size(): SizeTOptional

  def this(@StdString root: BytePointer, mode: Mode) {
    this()
    //    super (null.asInstanceOf[Pointer])
    allocate(root, mode)
  }

  def this(@StdString root: String, @Cast(Array("torch::data::datasets::MNIST::Mode")) mode: Int) {
    this()
    //    super (null.asInstanceOf[Pointer])
    allocate(root, mode)
  }


  def this(@StdString root: BytePointer) {
    this()
    //    super (null.asInstanceOf[Pointer])
    allocate(root)
  }



  def this(@StdString root: String) {
//    this()
    this(null.asInstanceOf[Pointer])
    allocate( root)
  }

  @native
  private def allocate(@StdString root: BytePointer, mode: Mode): Unit


  @native
  private def allocate(@StdString root: BytePointer): Unit


  @native
  private def allocate(@StdString root: String, @Cast(Array("torch::data::datasets::MNIST::Mode")) mode: Int): Unit


  @native
  private def allocate(@StdString root: String): Unit

  /** Returns the {@code Example} at the given {@code index}. */
  @ByVal
  @native
  override def get(@Cast(Array("size_t")) index: Long): Example



  /** Returns true if this is the training subset of MNIST. */
  // NOLINTNEXTLINE(bugprone-exception-escape)
  @Cast(Array("bool"))
  @NoException(true)
  @native
  def is_train: Boolean

  /** Returns all images stacked into a single tensor. */
  @Const
  @ByRef
  @native
  def images: Tensor

  /** Returns all targets stacked into a single tensor. */
  @Const
  @ByRef
  @native
  def targets: Tensor
}


@Name(Array("torch::data::datasets::Dataset<torch::data::datasets::MNIST,torch::data::Example<> >"))
@Properties(inherit = Array(classOf[org.bytedeco.pytorch.presets.torch]))
class MullerMNISTDataSet( val p: Pointer) extends MNISTBatchDataset(p) {
  /** Pointer cast constructor. Invokes {@link Pointer# Pointer ( Pointer )}. */

  /** Returns the example at the given index. */
  @ByVal
  @Cast(Array("torch::data::datasets::Dataset<torch::data::datasets::MNIST,torch::data::Example<> >::ExampleType*"))
  @native
  def get(@Cast(Array("size_t")) index: Long): Example

  @native
  @ByVal
  override def get_batch(@ByVal request: SizeTArrayRef): ExampleVector = super.get_batch(request)

  @ByVal
  override def size(): SizeTOptional = super.size()

  @ByVal
  override def map( @ByVal transform: ExampleStack): MNISTMapDataset = super.map(transform)
}


object MullerMNISTBatchDataset{
  Loader.load
}
//@Name(Array("torch::data::datasets::BatchDataset<torch::data::datasets::MNIST,std::vector<torch::data::Example<> >,at::ArrayRef<size_t> >"))
//@Properties(inherit = Array(classOf[org.bytedeco.pytorch.presets.torch]))
//class MullerMNISTBatchDataset(val p: Pointer) extends Pointer(p) {
//
//  def this() {
//    this(p)
//    Loader.load()
////    super (p)
//  }
//
//  @MemberGetter
//  @native
//  @Cast(Array("const bool"))
//  def is_stateful: Boolean
//  val _is_stateful: Boolean = is_stateful
//  /** Pointer cast constructor. Invokes {@link Pointer# Pointer ( Pointer )}. */
//  /** Returns a batch of data given an index. */
//  @ByVal
//  def get_batch(@ByVal request: SizeTArrayRef): ExampleVector
////  ={
////    new ExampleVector()
////  }
//  /** Returns the size of the dataset, or an empty optional if it is unsized. */
//  @ByVal
//  def size(): SizeTOptional
//
//  /** Creates a {@code MapDataset} that applies the given {@code transform} to this dataset. */
//  @ByVal
//  def map(@ByVal transform: ExampleStack): MNISTMapDataset
//}


object MullerMNISTRandomDataLoader{
  Loader.load()
}
/** A dataloader for stateless datasets.
 *
 * This dataloader follows the traditional PyTorch dataloader design, whereby a
 * (posssibly) stateful sampler produces *batch requests* for a stateless
 * dataset, which acts as a simple batch request to batch mapping. The batch
 * request will often be an array of indices, and if the dataset is a simple
 * image dataset, the dataset would produce the images at those indices. */
@Name(Array("torch::data::StatelessDataLoader<torch::data::datasets::MapDataset<torch::data::datasets::MNIST,torch::data::transforms::Stack<torch::data::Example<> > >,torch::data::samplers::RandomSampler>"))
@NoOffset
@Properties(inherit = Array(classOf[org.bytedeco.pytorch.presets.torch]))
class MullerMNISTRandomDataLoader extends MullerMNISTRandomDataLoaderBase(p: Pointer) {
  //  static {
  //    Loader.load()
  //  }

  /** Pointer cast constructor. Invokes {@link Pointer# Pointer ( Pointer )}. */
  def this(p: Pointer) {
    this()
    Loader.load()
    //    super (p)

    //    super(p)
  }

  /** Constructs the {@code StatelessDataLoader} from a {@code dataset}, a {@code sampler} and
   * some {@code options}. */
  def this(@ByVal dataset: MNISTMapDataset, @ByVal sampler: RandomSampler, @ByVal options: DataLoaderOptions) {
    this()
    //    super (null.asInstanceOf[Pointer])
    allocate(dataset, sampler, options)
  }

  @native
  private def allocate(@ByVal dataset: MNISTMapDataset, @ByVal sampler: RandomSampler, @ByVal options: DataLoaderOptions): Unit
}


@Name(Array("torch::data::DataLoaderBase<torch::data::datasets::MapDataset<torch::data::datasets::MNIST,torch::data::transforms::Stack<torch::data::Example<> > >,torch::data::Example<>,std::vector<size_t> >"))
@NoOffset
@Properties(inherit = Array(classOf[org.bytedeco.pytorch.presets.torch]))
class MullerMNISTRandomDataLoaderBase(val p: Pointer) extends Pointer(p) {

  @ByVal
  @native
  def begin: ExampleIterator

  /** Returns a special "sentinel" iterator that compares equal with a
   * non-sentinel iterator once the DataLoader is exhausted. */
  @ByVal
  @native
  def end: ExampleIterator

  /** Joins the DataLoader's worker threads and drains internal queues.
   * This function may only be invoked from the main thread (in which the
   * DataLoader lives). */
  @native
  def join(): Unit

  /** Returns the options with which the DataLoader was configured. */
  @Const
  @ByRef
  @native
  @NoException(true) def options: FullDataLoaderOptions
}




```

```
package layer

import org.bytedeco.pytorch.global.torch
import org.bytedeco.pytorch.LinearImpl
import org.bytedeco.javacpp._
import org.bytedeco.javacpp.annotation._
import org.bytedeco.pytorch.global.torch._
import org.bytedeco.pytorch._
import org.bytedeco.pytorch.Module
import org.bytedeco.pytorch.DataLoaderOptions
import org.bytedeco.pytorch.Example
import org.bytedeco.pytorch.ExampleIterator
import org.bytedeco.pytorch.ExampleStack
import org.bytedeco.pytorch.MNIST
import org.bytedeco.pytorch.MNISTMapDataset
import org.bytedeco.pytorch.MNISTRandomDataLoader
import org.bytedeco.pytorch.SGD
import org.bytedeco.pytorch.SGDOptions


class Net() extends Module { // Construct and register two Linear submodules.
  var fc1 = register_module("fc1", new LinearImpl(784, 64))
  var  fc2 = register_module("fc2", new LinearImpl(64, 32))
  var  fc3 = register_module("fc3", new LinearImpl(32, 10))

  // Implement the Net's algorithm.
  def forward(xs:Tensor): Tensor = { // Use one of many tensor manipulation functions.
    var x = xs
    x = relu(fc1.forward(x.reshape(x.size(0), 784)))
    x = dropout(x, /*p=*/ 0.5, /*train=*/ is_training)
    x = relu(fc2.forward(x))
    x = log_softmax(fc3.forward(x), /*dim=*/ 1)
    x
  }



  // Use one of many "standard library" modules.
  //  var fc1: LinearImpl = null
  //  var fc2: LinearImpl = null
  //  var fc3: LinearImpl = null
}
object example {



  @throws[Exception]
  def main(args: Array[String]): Unit = {
    /* try to use MKL when available */ System.setProperty("org.bytedeco.openblas.load", "mkl")

    // Create a new Net.
    val net = new Net
    //        torch.parameters_to_vector()
    // Create a multi-threaded data loader for the MNIST dataset.

    val path = "/Users/muller/Documents/gitcode/test_platfrom/src/main/resources/data"
//    val data_set = new MNIST(path).map(new ExampleStack)
//    val data_loader = new MNISTRandomDataLoader(data_set, new RandomSampler(data_set.size.get), new DataLoaderOptions(/*batch_size=*/ 64))

    val data_set = new MullerMNIST(path).map(new ExampleStack)
    val data_loader = new MullerMNISTRandomDataLoader(data_set, new RandomSampler(data_set.size.get), new DataLoaderOptions(/*batch_size=*/ 64))

    // Instantiate an SGD optimization algorithm to update our Net's parameters.
    val optimizer = new SGD(net.parameters, new SGDOptions(/*lr=*/ 0.01))
    for (epoch <- 1 to 100) {
      var batch_index = 0
      // Iterate the data loader to yield batches from the dataset.
      var it = data_loader.begin
      while ( {
        !(it == data_loader.end)
      }) {
        val batch = it.access
        // Reset gradients.
        optimizer.zero_grad()
        // Execute the model on the input data.
        val prediction = net.forward(batch.data)
        // Compute a loss value to judge the prediction of our model.
        val loss = nll_loss(prediction, batch.target)
        // Compute gradients of the loss w.r.t. the parameters of our model.
        loss.backward
        // Update the parameters based on the calculated gradients.
        optimizer.step
        // Output the loss and checkpoint every 100 batches.
        if ( {
          batch_index += 1; batch_index
        } % 100 == 0) {
          System.out.println("Epoch: " + epoch + " | Batch: " + batch_index + " | Loss: " + loss.item_float)
          // Serialize your model periodically as a checkpoint.
          val archive = new OutputArchive
          net.save(archive)
          archive.save_to("net.pt")
        }

        it = it.increment
      }
    }
  }
}



```

**Comment by mullerhai** [comment] 2022-11-29 13:06
throw new UnsatisfiedLinkError("no " + name +
                " in java.library.path: "  libiomp5md not found

**Comment by saudet** [comment] 2022-11-29 13:26
What is the error that you are encountering?

**Comment by mullerhai** [comment] 2022-11-29 13:48
> What is the error that you are encountering
 the libiomp5md.dylib  not found  , but  I think  it is  not the most import thing , I want to know   how to  constructure  other  dataset and dataloader  for  other data ? if for  iris or  boston house price dataset  or  the  other real log data or  more feature columns data? if  I do not use mnist dataset example ,
please give me  a  answer   or example? thanks

**Comment by saudet** [comment] 2022-11-29 13:54
As I mentioned previously in issue https://github.com/bytedeco/javacpp-presets/issues/623#issuecomment-846679169, ChunkDataReader seems to be most promising class to map since it comes with virtual functions that we should be able to implement easily in Java.

And please stop opening duplicates issues. Opening more issues with the same questions doesn't help.

**Comment by saudet** [comment] 2022-11-29 13:55
Duplicate of #1215

**Closed by saudet** 2022-11-29 13:55 UTC
Labels: duplicate, enhancement

**Comment by mullerhai** [comment] 2022-11-29 14:18
> #623 (comment)

Sorry ,I don't want to ask duplicate question ,because of without the normal pytorch dataset and dataloader, I don't know how to load the train data to the pytorch  neural network . it is make me fell nervous , as you say   ChunkDataReader and ChunkDataset  are the most  promising classes to map ,why the javacpp  not implement in java ?
