### ISSUE TITLE
couldn't find "libgnustl_static.so"

### ISSUE THREAD

**Issue by Huskera** [bytedeco/javacpp-presets#390] opened 2017-03-08 09:14 UTC
Hi,
When I run JavaCV-android-example on my device(HUWEI P8, Android 5.0). I got below exceptions. It occurred in FFmpegFrameRecorder.tryLoad(), is this issue the same as #386 ?

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.zekee.ls.livedemo-2/base.apk", zip file "/data/app/com.zekee.ls.livedemo-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.zekee.ls.livedemo-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.zekee.ls.livedemo-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.zekee.ls.livedemo-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.zekee.ls.livedemo-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.zekee.ls.livedemo-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.zekee.ls.livedemo-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.zekee.ls.livedemo-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.zekee.ls.livedemo-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.zekee.ls.livedemo-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.zekee.ls.livedemo-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.zekee.ls.livedemo-2/lib/arm64, /data/app/com.zekee.ls.livedemo-2/base.apk!/lib/arm64-v8a, /data/app/com.zekee.ls.livedemo-2/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.zekee.ls.livedemo-2/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.zekee.ls.livedemo-2/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.zekee.ls.livedemo-2/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.zekee.ls.livedemo-2/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.zekee.ls.livedemo-2/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.zekee.ls.livedemo-2/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.zekee.ls.livedemo-2/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.zekee.ls.livedemo-2/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.zekee.ls.livedemo-2/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.zekee.ls.livedemo-2/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libgnustl_static.so"

**Comment by saudet** [comment] 2017-03-08 09:19
No, but it is a duplicate of https://github.com/bytedeco/javacv/issues/617

This issue has been fixed.

**Closed by saudet** 2017-03-08 09:19 UTC
Labels: bug, duplicate
