### ISSUE TITLE
Numpy: Run error

### ISSUE THREAD

**Issue by penetest** [bytedeco/javacpp-presets#750] opened 2019-07-09 08:41 UTC
I try to run this code,
```   
System.setProperty("org.bytedeco.openblas.load", "mkl");

        Py_Initialize();
        String path = null;
        try {
            path = cachePackage().getAbsolutePath();
        } catch (IOException e) {
            e.printStackTrace();
        }
        PyList_Insert(PySys_GetObject("path"), 0, PyUnicode_FromString(path));
        if (_import_array() < 0) {
            System.err.println("numpy.core.multiarray failed to import");
            PyErr_Print();
            System.exit(-1);
        }
        PyObject globals = PyModule_GetDict(PyImport_AddModule("__main__"));

        int[] dimsx = {1, 2, 2, 3, 4, 3, 5};

        PyArrayObject input = new PyArrayObject(new PointerPointer(dimsx));

        PyDict_SetItemString(globals, "x", input);
//        PyDict_SetItemString(globals, "output", out);

        PyRun_StringFlags("import numpy as np; z = np.unique(np.array(x)); print(z)", Py_single_input, globals, globals, null);
        PyObject z = PyDict_GetItemString(globals, "z");
//        IntPointer data = new IntPointer(PyArray_BYTES(z)).capacity(PyArray_Size(z));
        System.out.println("z = " + z);
```

but show some error:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f3be113ed50, pid=1735, tid=0x00007f3ca2ab1700
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b03) (build 1.8.0_212-8u212-b03-2~deb9u1-b03)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b03 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libpython3.6m.so.1.0+0xf8d50]  PyType_IsSubtype+0x0
#
# Core dump written. Default location: /data/dataflow-cpython-numpy/core or core.1735
#
# An error report file with more information is saved as:
# /data/dataflow-cpython-numpy/hs_err_pid1735.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)
```

**Comment by saudet** [comment] 2019-07-09 23:02
Duplicate of #712

**Closed by saudet** 2019-07-09 23:02 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2019-07-09 23:03
Please try again with version 1.5.1. This has been fixed!
