### ISSUE TITLE
java.lang.UnsatisfiedLinkError `GOMP_4.0' Travis CI Using Java OpenCV library through Gradle

### ISSUE THREAD

**Issue by JLLeitschuh** [bytedeco/javacpp-presets#84] opened 2015-09-03 01:20 UTC
The issue is well detailed here:
http://stackoverflow.com/q/32361567/3708426

**Comment by JLLeitschuh** [comment] 2015-09-03 03:18
Found the reason for the problem.
GCC needs to be version 4.8 or higher. Versions 4.8 or lower have `GOMP_3.0`
This was solved thanks to this post: https://groups.google.com/forum/#!topic/javacpp-project/q3bWehnEzNY

If you could add something about this to the readme you could save some poor individual several hours of googling.

**Comment by saudet** [comment] 2015-09-03 03:25
Duplicate of #22 and #74

It is in the README file:
>[The JAR files] were built on Fedora 21, so they may not work on all distributions of Linux, especially older ones. 

- https://github.com/bytedeco/javacpp-presets/#manual-installation

BTW, I plan to use Docker to build against CentOS in the future, so this shouldn't happen with the next release.

**Closed by saudet** 2015-09-03 03:25 UTC
Labels: duplicate, enhancement
