### ISSUE TITLE
How to use FFmpeg in Android?

### ISSUE THREAD

**Issue by OmidNejadabbasi** [bytedeco/javacpp-presets#1416] opened 2023-09-17 13:30 UTC
I have added the following gradle deps to the build.gradle file but I can't import the classes in my android project:

```
implementation 'org.bytedeco:ffmpeg-platform-gpl:6.0-1.5.9'
```

Can you explain how to use it in Android/gradle

**Comment by saudet** [comment] 2023-09-17 17:22
Please try with the Platform Plugin of Gradle JavaCPP:   
https://github.com/bytedeco/gradle-javacpp#the-platform-plugin

**Comment by OmidNejadabbasi** [comment] 2023-09-17 18:05
> Please try with the Platform Plugin of Gradle JavaCPP: https://github.com/bytedeco/gradle-javacpp#the-platform-plugin

@saudet 
I did use the plugin but got another error. I opened an issue in that repo : https://github.com/bytedeco/gradle-javacpp/issues/32

**Comment by saudet** [comment] 2023-09-18 00:57
Duplicate of https://github.com/bytedeco/gradle-javacpp/issues/32

**Closed by saudet** 2023-09-18 00:57 UTC
Labels: duplicate, question
