### ISSUE TITLE
ERROR like [rtmp @ 0x7f1b147cbb40] Too short chunk size change packet (0), how can i catch it?

### ISSUE THREAD

**Issue by NacyLiu** [bytedeco/javacpp-presets#258] opened 2016-07-28 02:53 UTC
i have used class ffmpegGrabber and grabImages()

**Comment by saudet** [comment] 2016-07-28 03:43
Duplicate of https://github.com/bytedeco/javacv/issues/469

**Closed by saudet** 2016-07-28 03:43 UTC
Labels: question

**Comment by NacyLiu** [comment] 2016-07-28 03:45
e.. I am sorry, but there is no answer about this question ...
