### ISSUE TITLE
Error on Loader.load(avutil.class);

### ISSUE THREAD

**Issue by arthurpalves** [bytedeco/javacpp-presets#155] opened 2016-02-18 15:09 UTC
I was able to build the libs and get it running, however I must use `Loader.load(avutil.class);` before using `FFmpegFrameRecorder` and this is causing two very annoying issues on **Lollipop** and **Marshmallow** respectively:

**OBS.:** Not calling `Loader.load(avutil.class);` on **Marshmallow** will result in the same issue as below, but on **Lollipop** will simply get `UnsatisfiedLinkError: org.bytedeco.javacpp.avutil`.

**Lollipop**:
```
java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.debuggable-1/lib/arm/libjniavutil.so"
  at java.lang.Runtime.loadLibrary(Runtime.java:371)
  at java.lang.System.loadLibrary(System.java:989)
  at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:597)
  at org.bytedeco.javacpp.Loader.load(Loader.java:438)
  at org.bytedeco.javacpp.Loader.load(Loader.java:381)
  at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10)
  at java.lang.Class.classForName(Native Method)
  at java.lang.Class.forName(Class.java:308)
  at org.bytedeco.javacpp.Loader.load(Loader.java:413)
Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.debuggable-1/base.apk"],nativeLibraryDirectories=[/data/app/com.debuggable-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libgnustl_static.so"
  at java.lang.Runtime.loadLibrary(Runtime.java:366)
  at java.lang.System.loadLibrary(System.java:989)
  at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:597)
  at org.bytedeco.javacpp.Loader.load(Loader.java:429)
  at org.bytedeco.javacpp.Loader.load(Loader.java:381) 
  at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10) 
  at java.lang.Class.classForName(Native Method) 
  at java.lang.Class.forName(Class.java:308) 
  at org.bytedeco.javacpp.Loader.load(Loader.java:413)
```

**Marshmallow**:
```
W/linker: /data/app/com.debuggable-1/lib/arm/libjniavutil.so: unused DT entry: type 0x1d arg 0x19303
 W/linker: /data/app/com.debuggable-1/lib/arm/libjniavutil.so: is missing DT_SONAME will use basename as a replacement: "libjniavutil.so"
 E/javacpp: Error getting static method ID of org/bytedeco/javacpp/Loader/putMemberOffset
 A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NoSuchMethodError: no static method "Lorg/bytedeco/javacpp/Loader;.putMemberOffset(Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/Class;"
 A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String) (Runtime.java:-2)
 A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.String java.lang.Runtime.doLoad(java.lang.String, java.lang.ClassLoader) (Runtime.java:435)
 A/art: art/runtime/java_vm_ext.cc:410]   at void java.lang.Runtime.loadLibrary(java.lang.String, java.lang.ClassLoader) (Runtime.java:370)
 A/art: art/runtime/java_vm_ext.cc:410]   at void java.lang.System.loadLibrary(java.lang.String) (System.java:1076)
 A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.String org.bytedeco.javacpp.Loader.loadLibrary(java.net.URL[], java.lang.String) (Loader.java:597)
 A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.String org.bytedeco.javacpp.Loader.load(java.lang.Class) (Loader.java:438)
 A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.String org.bytedeco.javacpp.Loader.load() (Loader.java:381)
 A/art: art/runtime/java_vm_ext.cc:410]   at void org.bytedeco.javacpp.avutil.<clinit>() (avutil.java:10)
 A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Class java.lang.Class.classForName!(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
 A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:324)
 A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.String org.bytedeco.javacpp.Loader.load(java.lang.Class) (Loader.java:413)
 A/art: art/runtime/java_vm_ext.cc:410]   at void com.google.android.apps.watchme.recorder.ScreenRecorder.<init>(int, int, int, int, android.media.projection.MediaProjection, java.lang.String) (ScreenRecorder.java:116)
 A/art: art/runtime/java_vm_ext.cc:410]   at void com.recorder.Recorder.prepareMediaRecorder(boolean) (Recorder.java:496)
 A/art: art/runtime/java_vm_ext.cc:410]   at void com.recorder.Recorder.run() (Recorder.java:268)
 A/art: art/runtime/java_vm_ext.cc:410]   at void com.recorder.Recorder.cleanStart(com.recorder.RecordRequest) (Recorder.java:149)
 A/art: art/runtime/java_vm_ext.cc:410]   at void com.recorder.Recorder.<init>(com.recorder.RecordRequest, com.google.android.apps.watchme.StreamerService) (Recorder.java:139)
 A/art: art/runtime/java_vm_ext.cc:410]   at void com.view.activity.MainActivity.startRecording(java.lang.String) (MainActivity.java:331)
 A/art: art/runtime/java_vm_ext.cc:410]   at void com.view.activity.MainActivity.onActivityResult(int, int, android.content.Intent) (MainActivity.java:272)
 A/art: art/runtime/java_vm_ext.cc:410]   at void android.app.Activity.dispatchActivityResult(java.lang.String, int, int, android.content.Intent) (Activity.java:6428)
 A/art: art/runtime/java_vm_ext.cc:410]   at void android.app.ActivityThread.deliverResults(android.app.ActivityThread$ActivityClientRecord, java.util.List) (ActivityThread.java:3695)
 A/art: art/runtime/java_vm_ext.cc:410]   at void android.app.ActivityThread.handleSendResult(android.app.ActivityThread$ResultData) (ActivityThread.java:3742)
 A/art: art/runtime/java_vm_ext.cc:410]   at void android.app.ActivityThread.-wrap16(android.app.ActivityThread, android.app.ActivityThread$ResultData) (ActivityThread.java:-1)
 A/art: art/runtime/java_vm_ext.cc:410]   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1393)
 A/art: art/runtime/java_vm_ext.cc:410]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
 A/art: art/runtime/java_vm_ext.cc:410]   at void android.os.Looper.loop() (Looper.java:148)
 A/art: art/runtime/java_vm_ext.cc:410]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:5417)
 A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
 A/art: art/runtime/java_vm_ext.cc:410]   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:726)
 A/art: art/runtime/java_vm_ext.cc:410]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:616)
 A/art: art/runtime/java_vm_ext.cc:410] 
 A/art: art/runtime/java_vm_ext.cc:410]     in call to NewGlobalRef
 A/art: art/runtime/java_vm_ext.cc:410]     from java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String)
 A/art: art/runtime/java_vm_ext.cc:410] "main" prio=5 tid=1 Runnable
 A/art: art/runtime/java_vm_ext.cc:410]   | group="main" sCount=0 dsCount=0 obj=0x7302c2a0 self=0xb4df6500
 A/art: art/runtime/java_vm_ext.cc:410]   | sysTid=13705 nice=0 cgrp=default sched=0/0 handle=0xb6fc9b34
 A/art: art/runtime/java_vm_ext.cc:410]   | state=R schedstat=( 1158033535 229924998 1462 ) utm=99 stm=16 core=0 HZ=100
 A/art: art/runtime/java_vm_ext.cc:410]   | stack=0xbe05b000-0xbe05d000 stackSize=8MB
 A/art: art/runtime/java_vm_ext.cc:410]   | held mutexes= "mutator lock"(shared held)
 A/art: art/runtime/java_vm_ext.cc:410]   native: #00 pc 00370aa9  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::ArtMethod*, void*)+160)
 A/art: art/runtime/java_vm_ext.cc:410]   native: #01 pc 003503b7  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+150)
 A/art: art/runtime/java_vm_ext.cc:410]   native: #02 pc 0025a6fd  /system/lib/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+740)
 A/art: art/runtime/java_vm_ext.cc:410]   native: #03 pc 0025add5  /system/lib/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)+64)
 A/art: art/runtime/java_vm_ext.cc:410]   native: #04 pc 000fd1d1  /system/lib/libart.so (art::ScopedCheck::AbortF(char const*, ...)+32)
 A/art: art/runtime/java_vm_ext.cc:410]   native: #05 pc 001022e5  /system/lib/libart.so (art::ScopedCheck::Check(art::ScopedObjectAccess&, bool, char const*, art::JniValueType*) (.constprop.95)+5072)
 A/art: art/runtime/java_vm_ext.cc:410]   native: #06 pc 001146d1  /system/lib/libart.so (art::CheckJNI::NewGlobalRef(_JNIEnv*, _jobject*)+392)
 A/art: art/runtime/java_vm_ext.cc:410]   native: #07 pc 00348ff7  /system/lib/libart.so (art::Thread::SetClassLoaderOverride(_jobject*)+38)
 A/art: art/runtime/java_vm_ext.cc:410]   native: #08 pc 0025b393  /system/lib/libart.so (art::JavaVMExt::LoadNativeLibrary(_JNIEnv*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, _jobject*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)+1290)
 A/art: art/runtime/java_vm_ext.cc:410]   native: #09 pc 002d13af  /system/lib/libart.so (art::Runtime_nativeLoad(_JNIEnv*, _jclass*, _jstring*, _jobject*, _jstring*)+194)
 A/art: art/runtime/java_vm_ext.cc:410]   native: #10 pc 00212105  /data/dalvik-cache/arm/system@framework@boot.oat (Java_java_lang_Runtime_nativeLoad__Ljava_lang_String_2Ljava_lang_ClassLoader_2Ljava_lang_String_2+144)
 A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Runtime.nativeLoad(Native method)
 A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Runtime.doLoad(Runtime.java:435)
 A/art: art/runtime/java_vm_ext.cc:410]   - locked <0x01b61a68> (a java.lang.Runtime)
 A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Runtime.loadLibrary(Runtime.java:370)
 A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.System.loadLibrary(System.java:1076)
 A/art: art/runtime/java_vm_ext.cc:410]   at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:597)
 A/art: art/runtime/java_vm_ext.cc:410]   at org.bytedeco.javacpp.Loader.load(Loader.java:438)
 A/art: art/runtime/java_vm_ext.cc:410]   at org.bytedeco.javacpp.Loader.load(Loader.java:381)
 A/art: art/runtime/java_vm_ext.cc:410]   at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10)
 A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Class.classForName!(Native method)
 A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Class.forName(Class.java:324)
 A/art: art/runtime/java_vm_ext.cc:410]   at org.bytedeco.javacpp.Loader.load(Loader.java:413)
 A/art: art/runtime/java_vm_ext.cc:410]   at com.google.android.apps.watchme.recorder.ScreenRecorder.<init>(ScreenRecorder.java:116)
 A/art: art/runtime/java_vm_ext.cc:410]   at com.recorder.Recorder.prepareMediaRecorder(Recorder.java:496)
 A/art: art/runtime/java_vm_ext.cc:410]   at com.recorder.Recorder.run(Recorder.java:268)
 A/art: art/runtime/java_vm_ext.cc:410]   at com.recorder.Recorder.cleanStart(Recorder.java:149)
 A/art: art/runtime/java_vm_ext.cc:410]   at com.recorder.Recorder.<init>(Recorder.java:139)
 A/art: art/runtime/java_vm_ext.cc:410]   at com.view.activity.MainActivity.startRecording(MainActivity.java:331)
 A/art: art/runtime/java_vm_ext.cc:410]   at com.view.activity.MainActivity.onActivityResult(MainActivity.java:272)
 A/art: art/runtime/java_vm_ext.cc:410]   at android.app.Activity.dispatchActivityResult(Activity.java:6428)
 A/art: art/runtime/java_vm_ext.cc:410]   at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
 A/art: art/runtime/java_vm_ext.cc:410]   at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
 A/art: art/runtime/java_vm_ext.cc:410]   at android.app.ActivityThread.-wrap16(ActivityThread.java:-1)
 A/art: art/runtime/java_vm_ext.cc:410]   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
 A/art: art/runtime/java_vm_ext.cc:410]   at android.os.Handler.dispatchMessage(Handler.java:102)
 A/art: art/runtime/java_vm_ext.cc:410]   at android.os.Looper.loop(Looper.java:148)
 A/art: art/runtime/java_vm_ext.cc:410]   at android.app.ActivityThread.main(ActivityThread.java:5417)
 A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.reflect.Method.invoke!(Native method)
 A/art: art/runtime/java_vm_ext.cc:410]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 A/art: art/runtime/java_vm_ext.cc:410]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by saudet** [comment] 2016-02-20 03:47
This is probably the same as https://github.com/bytedeco/javacv/issues/245 and something that needs to be fixed in the native binaries.

**Comment by arthurpalves** [comment] 2016-02-20 14:29
I don't have any clue on this :/

**Comment by saudet** [comment] 2016-02-20 14:33
Well, please try the SNAPSHOT binaries I uploaded:
https://github.com/bytedeco/javacv/issues/245#issuecomment-186540961

**Comment by marwfair** [comment] 2016-04-29 02:20
Did you ever get this working? I am facing the same problem and have tried the new binaries.

**Comment by marwfair** [comment] 2016-05-11 04:13
@saudet I tried using your new binaries again, but now I am getting this error
```
libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 26399 (AsyncTask #4)
```
Maybe I am using the binaries wrong. I replaced ffmpeg.jar, javacpp.jar, javacv.jar, and opencv.jar in my libs directory with the new ones. I also tried the ones from the javacv-1.2 binary. Do I also need to replace the .so files in my armeabi and armeabi-v7a directories? I didn't see any of the android binaries.

Thank you so much for your help. I have a feeling that I'm just missing a step. Everything worked fine before updating to sdk 23.

**Comment by saudet** [comment] 2016-05-11 04:48
@marwfair In FaceRecognizer? Seems to be a problem with OpenCV: https://github.com/bytedeco/javacv/issues/400

**Comment by marwfair** [comment] 2016-05-11 05:01
@saudet No, I'm not using FaceRecognizer. It is happening when I initialize FFmpegFrameGrabber or FFmpegFrameRecorder.

**Comment by saudet** [comment] 2016-05-11 06:55
Of course you need to replace all the binaries...

**Comment by marwfair** [comment] 2016-05-11 07:38
@saudet Well, I just replaced all of the binaries again with the new ones and now everything seems to work! Thanks again for your help!

**Comment by saudet** [comment] 2016-05-13 08:07
Closing as duplicate of bytedeco/javacv#245.

**Closed by saudet** 2016-05-13 08:07 UTC
Labels: bug, duplicate
