### ISSUE TITLE
linux-arm presets

### ISSUE THREAD

**Issue by robertoandrade** [bytedeco/javacpp-presets#94] opened 2015-10-05 21:34 UTC
How can one go about compiling the .sos for linux-arm architecture and include in the presets? Was this ever attempted? I see there's a mention of it in the README about needing contributions on that but I'm not sure if there's a set of instructions already about how to compile and contribute the changes back into this project (if that was not done still).

**Comment by saudet** [comment] 2015-10-06 13:47
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/37. There's some info there that will help you. Some people have tried yes, but no one has contributed anything yet. Maybe you can ask them if they have any suggestions about how to proceed. Basically we need to add `linux-arm` entries to the `cppbuild.sh` scripts first. When you get those in, just send me a pull request, and I will be glad to add them to this repository. Thanks for considering making a contribution!

**Closed by saudet** 2015-10-06 13:47 UTC
Labels: duplicate, enhancement
