### ISSUE TITLE
macosx-arm64 for TensorFlow Lite 

### ISSUE THREAD

**Issue by Vane101** [bytedeco/javacpp-presets#1477] opened 2024-02-24 17:05 UTC
Thank you, this is a great repo. I am working on a Macbook M1 and wondering if there was a way of getting a macosx-arm64.jar for tensorflow-lite. Found nothing on the snapshot builds

**Comment by saudet** [comment] 2024-02-25 02:36
Contributions are welcome!

**Comment by saudet** [comment] 2024-02-25 02:36
Duplicate of #1069

**Closed by saudet** 2024-02-25 02:36 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2024-11-22 08:05
I've added macosx-arm64 to the builds for TensorFlow Lite.
Please give it a try with the snapshots: http://bytedeco.org/builds/
