### ISSUE TITLE
have ffmpeg linux arm exist?

### ISSUE THREAD

**Issue by arliweng** [bytedeco/javacpp-presets#139] opened 2016-01-18 21:11 UTC
where i can download the ffmpeg-linux-arm.jar? the error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:390)
	at org.bytedeco.javacpp.Loader.load(Loader.java:358)
	at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2539)
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:383)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:377)
	at javacvTest.MP4.main(MP4.java:47)
```
or i can build from source? in https://github.com/bytedeco/javacpp-presets/blob/master/ffmpeg/cppbuild.sh i not found the linux-arm script..

btw: my device is Raspberry PI 2, and os is archlinux-arm-i686

**Comment by saudet** [comment] 2016-01-19 11:10
Not that I know of. Closing as duplicate of https://github.com/bytedeco/javacpp-presets/issues/37 but please consider making a contribution! Thank you

**Comment by saudet** [comment] 2016-01-19 11:11
Ok, looks like that issue closed automatically, so let's keep this one opened.

**Comment by saudet** [comment] 2016-05-19 05:44
With the release of version 1.2, yes they do! Thanks to @vb216 :)
https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/ffmpeg/3.0.2-1.2/ffmpeg-3.0.2-1.2-linux-armhf.jar

**Closed by saudet** 2016-05-19 05:44 UTC
Labels: enhancement, help wanted
