### ISSUE TITLE
caffe: mvn doesn't contain the windows binaries for master-1.2

### ISSUE THREAD

**Issue by twak** [bytedeco/javacpp-presets#271] opened 2016-08-16 15:09 UTC
Sorry if this is the wrong location to report this:

The central mvn repro doesn't contain the caffe window's binaries for the latest release.
http://central.maven.org/maven2/org/bytedeco/javacpp-presets/caffe/master-1.2/

Unfortunately this means the examples in javaccpp caffe readme don't work out of the box. The previous release contains the windows bins:
http://central.maven.org/maven2/org/bytedeco/javacpp-presets/caffe/rc3-1.2/

**Comment by saudet** [comment] 2016-08-21 07:00
No it doesn't, it never has. Those that are there are empty JAR.

Marking as duplicate of #34

**Closed by saudet** 2016-08-21 07:00 UTC
Labels: duplicate, enhancement
