### ISSUE TITLE
UnsatisfiedLinkError While using Tesseract and leptonica-platform maven in Java project (M1 Chip mac)

### ISSUE THREAD

**Issue by bhuveshkumaroracle** [bytedeco/javacpp-presets#1188] opened 2022-06-13 02:26 UTC
**What I am trying to do**: I am using Tsseract and leptonica-platform maven repository in one of my Java programs to do some OCR operations.

**Issue**: This code is working with almost all the JDKs on my Dell machine (Oracle linux 8 OS), my windows machine (windows 10) and OCI computer instances (Oracle linux 8 - with just simple java jdk installation), But this code throws an error (UnsatisfiedLinkError) when I try to run it on Mac Apple M1 chip laptop with JDK above 1.8.

I have been trying to resolve this error for a few days now, but none of the solutions from the internet seem to be working.
I would really appreciate any comments, directions or suggestions. 

**Expectation**: I want to be able to use these libraries for my Java project and run the code successfully on M1 Chip mac using JDK 17.

Attaching my pom.xml, the Error message

### pom.xml file
```


    <dependencies>
        <dependency>
            <groupId>net.sourceforge.tess4j</groupId>
            <artifactId>tess4j</artifactId>
            <version>5.2.1</version>
        </dependency>

        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>tesseract</artifactId>
            <version>4.1.0-1.5.2</version>
        </dependency>



        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>leptonica-platform</artifactId>
            <version>1.82.0-1.5.7</version>
        </dependency>

        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>5.7.0</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/net.java.dev.jna/jna-platform -->
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna-platform</artifactId>
            <version>5.11.0</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.5.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.boofcv</groupId>
            <artifactId>boofcv-core</artifactId>
            <version>0.40.1</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.github.downgoon/marvin -->
        <dependency>
            <groupId>com.github.downgoon</groupId>
            <artifactId>MarvinPlugins</artifactId>
            <version>1.5.5</version>
        </dependency>

        <dependency>
            <groupId>com.github.downgoon</groupId>
            <artifactId>MarvinFramework</artifactId>
            <version>1.5.5</version>
        </dependency>

    </dependencies>

```

## Error message

```
/Users/bhuvesh/Library/Java/JavaVirtualMachines/openjdk-17.0.2/Contents/Home/bin/java -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=60081:/Applications/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Users/bhuvesh/Downloads/ss/target/classes:/Users/bhuvesh/.m2/repository/net/sourceforge/tess4j/tess4j/5.2.1/tess4j-5.2.1.jar:/Users/bhuvesh/.m2/repository/com/github/jai-imageio/jai-imageio-core/1.4.0/jai-imageio-core-1.4.0.jar:/Users/bhuvesh/.m2/repository/org/apache/pdfbox/pdfbox/2.0.26/pdfbox-2.0.26.jar:/Users/bhuvesh/.m2/repository/org/apache/pdfbox/fontbox/2.0.26/fontbox-2.0.26.jar:/Users/bhuvesh/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/Users/bhuvesh/.m2/repository/org/apache/pdfbox/pdfbox-tools/2.0.26/pdfbox-tools-2.0.26.jar:/Users/bhuvesh/.m2/repository/org/apache/pdfbox/pdfbox-debugger/2.0.26/pdfbox-debugger-2.0.26.jar:/Users/bhuvesh/.m2/repository/org/apache/pdfbox/jbig2-imageio/3.0.4/jbig2-imageio-3.0.4.jar:/Users/bhuvesh/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:/Users/bhuvesh/.m2/repository/net/sourceforge/lept4j/lept4j/1.16.1/lept4j-1.16.1.jar:/Users/bhuvesh/.m2/repository/org/jboss/jboss-vfs/3.2.16.Final/jboss-vfs-3.2.16.Final.jar:/Users/bhuvesh/.m2/repository/org/jboss/logging/jboss-logging/3.1.4.GA/jboss-logging-3.1.4.GA.jar:/Users/bhuvesh/.m2/repository/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/tesseract/4.1.0-1.5.2/tesseract-4.1.0-1.5.2.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/leptonica/1.78.0-1.5.2/leptonica-1.78.0-1.5.2.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp/1.5.2/javacpp-1.5.2.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/leptonica-platform/1.82.0-1.5.7/leptonica-platform-1.82.0-1.5.7.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-platform/1.5.7/javacpp-platform-1.5.7.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp/1.5.7/javacpp-1.5.7-android-arm.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp/1.5.7/javacpp-1.5.7-android-arm64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp/1.5.7/javacpp-1.5.7-android-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp/1.5.7/javacpp-1.5.7-android-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp/1.5.7/javacpp-1.5.7-ios-arm64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp/1.5.7/javacpp-1.5.7-ios-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp/1.5.7/javacpp-1.5.7-linux-armhf.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp/1.5.7/javacpp-1.5.7-linux-arm64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp/1.5.7/javacpp-1.5.7-linux-ppc64le.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp/1.5.7/javacpp-1.5.7-linux-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp/1.5.7/javacpp-1.5.7-linux-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp/1.5.7/javacpp-1.5.7-macosx-arm64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp/1.5.7/javacpp-1.5.7-macosx-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp/1.5.7/javacpp-1.5.7-windows-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp/1.5.7/javacpp-1.5.7-windows-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/leptonica/1.82.0-1.5.7/leptonica-1.82.0-1.5.7-android-arm.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/leptonica/1.82.0-1.5.7/leptonica-1.82.0-1.5.7-android-arm64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/leptonica/1.82.0-1.5.7/leptonica-1.82.0-1.5.7-android-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/leptonica/1.82.0-1.5.7/leptonica-1.82.0-1.5.7-android-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/leptonica/1.82.0-1.5.7/leptonica-1.82.0-1.5.7-linux-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/leptonica/1.82.0-1.5.7/leptonica-1.82.0-1.5.7-linux-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/leptonica/1.82.0-1.5.7/leptonica-1.82.0-1.5.7-linux-armhf.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/leptonica/1.82.0-1.5.7/leptonica-1.82.0-1.5.7-linux-arm64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/leptonica/1.82.0-1.5.7/leptonica-1.82.0-1.5.7-linux-ppc64le.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/leptonica/1.82.0-1.5.7/leptonica-1.82.0-1.5.7-macosx-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/leptonica/1.82.0-1.5.7/leptonica-1.82.0-1.5.7-windows-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/leptonica/1.82.0-1.5.7/leptonica-1.82.0-1.5.7-windows-x86_64.jar:/Users/bhuvesh/.m2/repository/net/java/dev/jna/jna/5.7.0/jna-5.7.0.jar:/Users/bhuvesh/.m2/repository/net/java/dev/jna/jna-platform/5.11.0/jna-platform-5.11.0.jar:/Users/bhuvesh/.m2/repository/org/boofcv/boofcv-core/0.40.1/boofcv-core-0.40.1.jar:/Users/bhuvesh/.m2/repository/org/georegression/georegression/0.24/georegression-0.24.jar:/Users/bhuvesh/.m2/repository/org/ddogleg/ddogleg/0.21/ddogleg-0.21.jar:/Users/bhuvesh/.m2/repository/org/ejml/ejml-core/0.41/ejml-core-0.41.jar:/Users/bhuvesh/.m2/repository/org/ejml/ejml-fdense/0.41/ejml-fdense-0.41.jar:/Users/bhuvesh/.m2/repository/org/ejml/ejml-ddense/0.41/ejml-ddense-0.41.jar:/Users/bhuvesh/.m2/repository/org/ejml/ejml-simple/0.41/ejml-simple-0.41.jar:/Users/bhuvesh/.m2/repository/org/ejml/ejml-cdense/0.41/ejml-cdense-0.41.jar:/Users/bhuvesh/.m2/repository/org/ejml/ejml-zdense/0.41/ejml-zdense-0.41.jar:/Users/bhuvesh/.m2/repository/org/ejml/ejml-fsparse/0.41/ejml-fsparse-0.41.jar:/Users/bhuvesh/.m2/repository/org/ejml/ejml-dsparse/0.41/ejml-dsparse-0.41.jar:/Users/bhuvesh/.m2/repository/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar:/Users/bhuvesh/.m2/repository/org/boofcv/boofcv-feature/0.40.1/boofcv-feature-0.40.1.jar:/Users/bhuvesh/.m2/repository/org/boofcv/boofcv-geo/0.40.1/boofcv-geo-0.40.1.jar:/Users/bhuvesh/.m2/repository/org/boofcv/boofcv-io/0.40.1/boofcv-io-0.40.1.jar:/Users/bhuvesh/.m2/repository/org/yaml/snakeyaml/1.23/snakeyaml-1.23.jar:/Users/bhuvesh/.m2/repository/org/boofcv/boofcv-ip/0.40.1/boofcv-ip-0.40.1.jar:/Users/bhuvesh/.m2/repository/org/boofcv/boofcv-ip-multiview/0.40.1/boofcv-ip-multiview-0.40.1.jar:/Users/bhuvesh/.m2/repository/org/boofcv/boofcv-learning/0.40.1/boofcv-learning-0.40.1.jar:/Users/bhuvesh/.m2/repository/org/boofcv/boofcv-recognition/0.40.1/boofcv-recognition-0.40.1.jar:/Users/bhuvesh/.m2/repository/org/deepboof/main/0.5.1/main-0.5.1.jar:/Users/bhuvesh/.m2/repository/org/deepboof/models/0.5.1/models-0.5.1.jar:/Users/bhuvesh/.m2/repository/org/deepboof/learning/0.5.1/learning-0.5.1.jar:/Users/bhuvesh/.m2/repository/org/deepboof/io/0.5.1/io-0.5.1.jar:/Users/bhuvesh/.m2/repository/com/google/protobuf/protobuf-java/3.17.3/protobuf-java-3.17.3.jar:/Users/bhuvesh/.m2/repository/org/rauschig/jarchivelib/1.1.0/jarchivelib-1.1.0.jar:/Users/bhuvesh/.m2/repository/org/apache/commons/commons-compress/1.20/commons-compress-1.20.jar:/Users/bhuvesh/.m2/repository/net/lingala/zip4j/zip4j/2.8.0/zip4j-2.8.0.jar:/Users/bhuvesh/.m2/repository/org/boofcv/boofcv-reconstruction/0.40.1/boofcv-reconstruction-0.40.1.jar:/Users/bhuvesh/.m2/repository/org/boofcv/boofcv-sfm/0.40.1/boofcv-sfm-0.40.1.jar:/Users/bhuvesh/.m2/repository/org/boofcv/boofcv-types/0.40.1/boofcv-types-0.40.1.jar:/Users/bhuvesh/.m2/repository/com/github/downgoon/MarvinPlugins/1.5.5/MarvinPlugins-1.5.5.jar:/Users/bhuvesh/.m2/repository/com/github/downgoon/MarvinFramework/1.5.5/MarvinFramework-1.5.5.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacv-platform/1.3/javacv-platform-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacv/1.3/javacv-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.1.0-1.3/opencv-3.1.0-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/3.2.1-1.3/ffmpeg-3.2.1-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/flycapture/2.9.3.43-1.3/flycapture-2.9.3.43-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/libdc1394/2.2.4-1.3/libdc1394-2.2.4-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/libfreenect/0.5.3-1.3/libfreenect-0.5.3-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/librealsense/1.9.6-1.3/librealsense-1.9.6-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/videoinput/0.200-1.3/videoinput-0.200-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/artoolkitplus/2.3.1-1.3/artoolkitplus-2.3.1-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/flandmark/1.07-1.3/flandmark-1.07-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/opencv-platform/3.1.0-1.3/opencv-platform-3.1.0-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.1.0-1.3/opencv-3.1.0-1.3-android-arm.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.1.0-1.3/opencv-3.1.0-1.3-android-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.1.0-1.3/opencv-3.1.0-1.3-linux-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.1.0-1.3/opencv-3.1.0-1.3-linux-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.1.0-1.3/opencv-3.1.0-1.3-linux-armhf.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.1.0-1.3/opencv-3.1.0-1.3-linux-ppc64le.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.1.0-1.3/opencv-3.1.0-1.3-macosx-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.1.0-1.3/opencv-3.1.0-1.3-windows-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.1.0-1.3/opencv-3.1.0-1.3-windows-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg-platform/3.2.1-1.3/ffmpeg-platform-3.2.1-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/3.2.1-1.3/ffmpeg-3.2.1-1.3-android-arm.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/3.2.1-1.3/ffmpeg-3.2.1-1.3-android-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/3.2.1-1.3/ffmpeg-3.2.1-1.3-linux-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/3.2.1-1.3/ffmpeg-3.2.1-1.3-linux-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/3.2.1-1.3/ffmpeg-3.2.1-1.3-linux-armhf.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/3.2.1-1.3/ffmpeg-3.2.1-1.3-linux-ppc64le.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/3.2.1-1.3/ffmpeg-3.2.1-1.3-macosx-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/3.2.1-1.3/ffmpeg-3.2.1-1.3-windows-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/3.2.1-1.3/ffmpeg-3.2.1-1.3-windows-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/flycapture-platform/2.9.3.43-1.3/flycapture-platform-2.9.3.43-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/flycapture/2.9.3.43-1.3/flycapture-2.9.3.43-1.3-linux-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/flycapture/2.9.3.43-1.3/flycapture-2.9.3.43-1.3-linux-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/flycapture/2.9.3.43-1.3/flycapture-2.9.3.43-1.3-linux-armhf.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/flycapture/2.9.3.43-1.3/flycapture-2.9.3.43-1.3-windows-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/flycapture/2.9.3.43-1.3/flycapture-2.9.3.43-1.3-windows-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/libdc1394-platform/2.2.4-1.3/libdc1394-platform-2.2.4-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/libdc1394/2.2.4-1.3/libdc1394-2.2.4-1.3-linux-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/libdc1394/2.2.4-1.3/libdc1394-2.2.4-1.3-linux-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/libdc1394/2.2.4-1.3/libdc1394-2.2.4-1.3-linux-armhf.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/libdc1394/2.2.4-1.3/libdc1394-2.2.4-1.3-linux-ppc64le.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/libdc1394/2.2.4-1.3/libdc1394-2.2.4-1.3-macosx-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/libdc1394/2.2.4-1.3/libdc1394-2.2.4-1.3-windows-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/libdc1394/2.2.4-1.3/libdc1394-2.2.4-1.3-windows-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/libfreenect-platform/0.5.3-1.3/libfreenect-platform-0.5.3-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/libfreenect/0.5.3-1.3/libfreenect-0.5.3-1.3-linux-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/libfreenect/0.5.3-1.3/libfreenect-0.5.3-1.3-linux-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/libfreenect/0.5.3-1.3/libfreenect-0.5.3-1.3-linux-armhf.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/libfreenect/0.5.3-1.3/libfreenect-0.5.3-1.3-linux-ppc64le.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/libfreenect/0.5.3-1.3/libfreenect-0.5.3-1.3-macosx-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/libfreenect/0.5.3-1.3/libfreenect-0.5.3-1.3-windows-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/libfreenect/0.5.3-1.3/libfreenect-0.5.3-1.3-windows-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/librealsense-platform/1.9.6-1.3/librealsense-platform-1.9.6-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/librealsense/1.9.6-1.3/librealsense-1.9.6-1.3-linux-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/librealsense/1.9.6-1.3/librealsense-1.9.6-1.3-linux-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/videoinput-platform/0.200-1.3/videoinput-platform-0.200-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/videoinput/0.200-1.3/videoinput-0.200-1.3-windows-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/videoinput/0.200-1.3/videoinput-0.200-1.3-windows-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/artoolkitplus-platform/2.3.1-1.3/artoolkitplus-platform-2.3.1-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/artoolkitplus/2.3.1-1.3/artoolkitplus-2.3.1-1.3-android-arm.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/artoolkitplus/2.3.1-1.3/artoolkitplus-2.3.1-1.3-android-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/artoolkitplus/2.3.1-1.3/artoolkitplus-2.3.1-1.3-linux-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/artoolkitplus/2.3.1-1.3/artoolkitplus-2.3.1-1.3-linux-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/artoolkitplus/2.3.1-1.3/artoolkitplus-2.3.1-1.3-linux-armhf.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/artoolkitplus/2.3.1-1.3/artoolkitplus-2.3.1-1.3-linux-ppc64le.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/artoolkitplus/2.3.1-1.3/artoolkitplus-2.3.1-1.3-macosx-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/artoolkitplus/2.3.1-1.3/artoolkitplus-2.3.1-1.3-windows-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/artoolkitplus/2.3.1-1.3/artoolkitplus-2.3.1-1.3-windows-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/flandmark-platform/1.07-1.3/flandmark-platform-1.07-1.3.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/flandmark/1.07-1.3/flandmark-1.07-1.3-android-arm.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/flandmark/1.07-1.3/flandmark-1.07-1.3-android-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/flandmark/1.07-1.3/flandmark-1.07-1.3-linux-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/flandmark/1.07-1.3/flandmark-1.07-1.3-linux-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/flandmark/1.07-1.3/flandmark-1.07-1.3-linux-armhf.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/flandmark/1.07-1.3/flandmark-1.07-1.3-linux-ppc64le.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/flandmark/1.07-1.3/flandmark-1.07-1.3-macosx-x86_64.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/flandmark/1.07-1.3/flandmark-1.07-1.3-windows-x86.jar:/Users/bhuvesh/.m2/repository/org/bytedeco/javacpp-presets/flandmark/1.07-1.3/flandmark-1.07-1.3-windows-x86_64.jar Main /Users/bhuvesh/Downloads/ss/screenshots/
Current JVM version - 17.0.2
Printing names of all the content in the selected directory...
 -> output
 -> java
 -> Screenshot 2022-05-26 at 11.46.17 AM.png
 -> Screenshot 2022-05-26 at 11.49.16 AM.png
Processing image /Users/bhuvesh/Downloads/ss/screenshots/Screenshot 2022-05-26 at 11.46.17 AM.png
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnilept in java.library.path: /Users/bhuvesh/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1543)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1192)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1042)
	at org.bytedeco.leptonica.global.lept.<clinit>(lept.java:12)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1109)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1042)
	at org.bytedeco.tesseract.TessBaseAPI.<clinit>(TessBaseAPI.java:25)
	at OcrAnalyser.extractWordsFromImage(OcrAnalyser.java:42)
	at Main.blurTheSensitiveData(Main.java:113)
	at Main.main(Main.java:96)
Caused by: java.lang.UnsatisfiedLinkError: no lept in java.library.path: /Users/bhuvesh/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1543)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1143)
	... 10 more

Process finished with exit code 1

```

**Comment by bhuveshkumaroracle** [comment] 2022-06-13 02:28
![image](https://user-images.githubusercontent.com/101088913/173268741-be9168ab-feed-47fa-b39f-a5bd8908edae.png)
Image of my testing of Same java project on different OS with different JDK versions

**Comment by saudet** [comment] 2022-06-13 02:45
There isn't yet a release version with support for macosx-arm64, but it's available in the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment] 2022-06-13 02:46
Duplicate of #1069

**Closed by saudet** 2022-06-13 02:46 UTC
Labels: duplicate, enhancement
