### ISSUE TITLE
ONNX for Mac M1 Silicon

### ISSUE THREAD

**Issue by OuYuBin** [bytedeco/javacpp-presets#1336] opened 2023-03-16 07:20 UTC
I am an IDE plug-in developer and have tried to build the corresponding graph editor through the ONNX API, 
[ONNX4IDEA](https://plugins.jetbrains.com/plugin/19368-onnx4idea)
![](https://plugins.jetbrains.com/files/19368/screenshot_e76f1bab-e326-407b-8da2-c1c73ca3c991)
But I found that it does not work under Mac M1 Silicon, 
```
Plugin 'cn.shanghai.oyb.onnx' failed to initialize and will be disabled. Please restart IntelliJ IDEA.
java.lang.UnsatisfiedLinkError: no jnionnx in java.library.path: [/Users/ouyubin/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
```
Can provide a wrapper for the corresponding library? Thank you。

**Comment by saudet** [comment] 2023-03-16 07:45
Sure! Contributions are welcome. However, I think we can more simply use the protobuf file itself.
@EmergentOrder What do you think?

**Comment by saudet** [comment] 2023-03-16 07:46
Duplicate of #1069

**Comment by OuYuBin** [comment] 2023-03-16 07:54
> Sure! Contributions are welcome. However, I think we can more simply use the protobuf file itself. @EmergentOrder What do you think?
Well, I tried to do the assignment directly through protobuf object reflection mechanism and serialize it, but many people thought it was unreliable, such as things like changing the opset version to define an op differently in different opsets and having to express it in another way. So... Calling the native implementation directly is more reassuring. 😄

**Comment by saudet** [comment] 2023-03-16 08:03
I see, if you have any questions about builds for macosx-arm64, please ask over at issue #1069.

**Closed by saudet** 2023-03-16 08:03 UTC
Labels: duplicate, enhancement

**Comment by OuYuBin** [comment] 2023-03-16 11:38
> I see, if you have any questions about builds for macosx-arm64, please ask over at issue #1069.

Oh，You're going to update the packaging script or whatever, and we are going to download it in the repo eventually, right?

**Comment by saudet** [comment] 2023-03-16 11:58
I don't plan on doing it myself no.

**Comment by OuYuBin** [comment] 2023-03-16 11:59
> I don't plan on doing it myself no.

understand

**Comment by saudet** [comment] 2024-11-22 08:09
I've added macosx-arm64 to the builds for ONNX.
Please give it a try with the snapshots: http://bytedeco.org/builds/
