### ISSUE TITLE
NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avcodec

### ISSUE THREAD

**Issue by xsjzf** [bytedeco/javacpp-presets#985] opened 2020-12-16 02:03 UTC
Error is reported in Windows server2012 system, other systems are in normal use

**Comment by xsjzf** [comment] 2020-12-16 02:03
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avcodec
        at java.lang.Class.forName0(Native Method) ~[na:1.8.0_271]
        at java.lang.Class.forName(Unknown Source) ~[na:1.8.0_271]
        at org.bytedeco.javacpp.Loader.load(Loader.java:1190) ~[javacpp-1.5.4.jar!/:1.5.4]
        at org.bytedeco.javacpp.Loader.load(Loader.java:1123) ~[javacpp-1.5.4.jar!/:1.5.4]
        at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.<clinit>(Read_packet_Pointer_BytePointer_int
.java:45) ~[ffmpeg-4.3.1-1.5.4.jar!/:4.3.1-1.5.4]
        at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:355) ~[javacv-1.5.4.jar!/:1.5.4]
        at com.onvif.java.JavaOnvifApplication.run(JavaOnvifApplication.java:32) [classes!/:0.0.1-SNAPSHOT]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) [spring-boot-2.3.0.RELEASE.
jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) [spring-boot-2.3.0.RELEASE
.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.3.0.RELEASE.jar!/:2
.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.0.RELEASE.jar!/:
2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.0.RELEASE.jar!/:
2.3.0.RELEASE]
        at com.onvif.java.JavaOnvifApplication.main(JavaOnvifApplication.java:24) [classes!/:0.0.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_271]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_271]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_271]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_271]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [javaOnvif-0.0.1-SNAPSHOT.jar:
0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) [javaOnvif-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSH
OT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [javaOnvif-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHO
T]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [javaOnvif-0.0.1-SNAPSHOT.jar:0.0.1-SNA
PSHOT]

**Comment by saudet** [comment] 2020-12-16 03:02
Please make sure that Media Foundation is installed like this:
https://github.com/bytedeco/javacv/blob/master/.travis.yml#L64

**Comment by saudet** [comment] 2020-12-16 03:02
Duplicate of #940

**Closed by saudet** 2020-12-16 03:02 UTC
Labels: duplicate, question
