### ISSUE TITLE
Failed to execute JavaCPP Builder: Could not parse "libavutil/avutil.h": File does not exist

### ISSUE THREAD

**Issue by zmingchun** [bytedeco/javacpp-presets#50] opened 2015-05-03 09:43 UTC
Hi, @saudet , 
I run the commandline as README.md 's Build Instructions:
```
 mvn install --projects ,opencv,ffmpeg
```
got the error on ubuntu15.04-server-64bit  as below :

```
Failed to execute JavaCPP Builder: Could not parse "libavutil/avutil.h": File does not exist -> [Help 1]
```
And I fix it by
```
 mvn install -Pandroid-arm -Dplatform.root=/home/pete/Downloads/android-ndk-r10c/ --projects ,opencv,ffmpeg
```
Maybe  the README.md 's Build Instructions should enrich?

**Comment by saudet** [comment] 2015-05-03 10:12
Of course the instructions could be more specific for each platform. IMO
the best is to put such special non-general information in wiki pages. You
should have write access to the wiki, so if you would like to make a
contribution, please feel free to create a new page! And let's add a link
to the README.md file.

**Comment by zmingchun** [comment] 2015-05-03 12:15
Sure，My pleasure. Maybe later, cause now I still in trouble with use opencv+ffmpeg  on android-arm. I will create new issue.

**Comment by saudet** [comment] 2015-07-04 03:50
Duplicate of #37

Please post information about linux-arm builds over there, thank you!

**Closed by saudet** 2015-07-04 03:50 UTC
Labels: duplicate, enhancement, help wanted
