### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnicaffe in java.library.path

### ISSUE THREAD

**Issue by zqr688** [bytedeco/javacpp-presets#431] opened 2017-06-16 06:54 UTC
## Classifying a single image using the JavaCPP presets for caffe throw Exception on linux
`Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnicaffe in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
	at org.bytedeco.javacpp.Loader.load(Loader.java:613)
	at org.bytedeco.javacpp.Loader.load(Loader.java:530)
	at org.bytedeco.javacpp.caffe.<clinit>(caffe.java:17)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.bytedeco.javacpp.Loader.load(Loader.java:585)
	at org.bytedeco.javacpp.Loader.load(Loader.java:530)
	at org.bytedeco.javacpp.caffe$FloatNet.<clinit>(caffe.java:23480)
	at caffe.CaffeTool.classify(CaffeTool.java:486)
	at caffe.CaffeTool.main(CaffeTool.java:419)
Caused by: java.lang.UnsatisfiedLinkError: no caffe in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
	at org.bytedeco.javacpp.Loader.load(Loader.java:604)
	... 9 more
`

**Comment by saudet** [comment] 2017-06-16 07:43
I'm assuming you are running this on Windows. There are no binaries for Windows, yet. You'll need to build from source. Duplicate of #34

**Closed by saudet** 2017-06-16 07:43 UTC
Labels: duplicate, enhancement

**Comment by zqr688** [comment] 2017-06-16 10:06
## It seems missing caffe-master-1.3-linux-x86_64.jar , now I find it ,But it throws another Exception
`Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/lib64/libjnicaffe.so: libcudart.so.8.0: Unable to open shared object file: no that file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1854)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
	at org.bytedeco.javacpp.Loader.load(Loader.java:613)
	at org.bytedeco.javacpp.Loader.load(Loader.java:530)
	at org.bytedeco.javacpp.caffe.<clinit>(caffe.java:17)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:585)
	at org.bytedeco.javacpp.Loader.load(Loader.java:530)
	at org.bytedeco.javacpp.caffe$Caffe.<clinit>(caffe.java:3926)
	at caffe.CaffeTool.classify(CaffeTool.java:485)
	at caffe.CaffeTool.main(CaffeTool.java:423)
Caused by: java.lang.UnsatisfiedLinkError: /usr/lib/libjnicaffe.so: libcudart.so.8.0: Unable to open shared object file: no that file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:784)
`
## Does CUDA must install?

**Comment by saudet** [comment] 2017-06-17 10:34
For the most recent binaries, yes, but you are free to build from source however you want. Contributions are also welcome!

**Comment by zqr688** [comment] 2017-06-19 03:16
Oh, I see, Thanks!
