### ISSUE TITLE
There is no such file libpostproc.57.dylib in version 6.0-1.5.9.

### ISSUE THREAD

**Issue by hehuipu** [bytedeco/javacpp-presets#1378] opened 2023-06-30 01:38 UTC
As the title, my MacPC got below error:

dyld[6156]: Library not loaded: @rpath/libpostproc.57.dylib
  Referenced from: <43FD77F2-09EE-396B-A8B5-928F33368871>/.javacpp/cache/ffmpeg-6.0-1.5.9-macosx-x86_64-gpl.jar/org/bytedeco/ffmpeg/macosx-x86_64-gpl/ffmpeg
  Reason: tried: '/.javacpp/cache/ffmpeg-6.0-1.5.9-macosx-x86_64-gpl.jar/org/bytedeco/ffmpeg/macosx-x86_64-gpl/libpostproc.57.dylib' (no such file), '/.javacpp/cache/ffmpeg-6.0-1.5.9-macosx-x86_64-gpl.jar/org/bytedeco/ffmpeg/macosx-x86_64-gpl/libpostproc.57.dylib' (no such file), '/usr/local/lib/libpostproc.57.dylib' (no such file), '/usr/lib/libpostproc.57.dylib' (no such file, not in dyld cache)

I have confirm the below list, but really no such file [libpostproc.57.dylib], which is in version 5.1.2-1.5.8 named [libpostproc.56.dylib].

ffmpeg
ffprobe
libavcodec.60.dylib
libavdevice.60.dylib
libavfilter.9.dylib
libavformat.60.dylib
libavutil.58.dylib
libjniavcodec.dylib
libjniavdevice.dylib
libjniavfilter.dylib
libjniavformat.dylib
libjniavutil.dylib
libjnipostproc.dylib
libjniswresample.dylib
libjniswscale.dylib
libpostproc.dylib
libswresample.4.dylib
libswscale.7.dylib

**Comment by saudet** [comment] 2023-06-30 02:59
Duplicate of https://github.com/bytedeco/javacv/issues/2039

**Comment by saudet** [comment] 2023-06-30 03:00
Please try again with the snapshots: http://bytedeco.org/builds/

**Closed by saudet** 2023-06-30 02:59 UTC
Labels: bug, duplicate
