### ISSUE TITLE
how to build arm64 for android ?

### ISSUE THREAD

**Issue by luorenjin** [bytedeco/javacpp-presets#338] opened 2016-12-20 12:08 UTC
hi, 
I hope to be able to run in android 64-bit system above, but the current version of the compiler does not arm64, I would like to ask how do?

**Comment by saudet** [comment] 2016-12-20 12:16
Add a new entry "android-arm64" to the cppbuild.sh file and it should work.

**Comment by luorenjin** [comment] 2016-12-21 04:40
hi,
I followed the [Building on Windows](https://github.com/bytedeco/javacpp-presets/wiki/Building-on-Windows)

**cd  javacpp-presets
bash cppbuild.sh -platform android-arm install opencv**

![image](https://cloud.githubusercontent.com/assets/7892385/21377463/ace457d4-c779-11e6-993a-122726f7076f.png)

thinks!

**Comment by saudet** [comment] 2016-12-22 10:52
Duplicate of #52

**Closed by saudet** 2016-12-22 10:52 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2018-02-27 03:09
64-bit builds for Android (as the "android-arm64" and "android-x86_64" platforms) are now available, so please give it a try! Binaries for 1.4.1-SNAPSHOT can be downloaded from the snapshot repository: http://bytedeco.org/builds/
