### ISSUE TITLE
Converting BufferedImage to PIX image

### ISSUE THREAD

**Issue by emara-geek** [bytedeco/javacpp-presets#517] opened 2018-01-30 21:13 UTC
I use javac with tesseract in my app, and I want to convert BufferedImage to PIX image to use it like the BasicExample.java, 
```
PIX image = pixRead(args.length > 0 ? args[0] : "/usr/src/tesseract/testing/phototest.tif");
        api.SetImage(image);
        // Get OCR result
        outText = api.GetUTF8Text();
```

I tried this, but did not work.

```
Pix image=null; 
        try {
        image = LeptUtils.convertImageToPix(img);
        } catch (IOException ex) {
        Logger.getLogger(OCR.class.getName()).log(Level.SEVERE, null, ex);
        }
api.SetImage(image); 
```

I searched a lot, but can figure out anything.
Thanks in advance.

**Comment by saudet** [comment] 2018-01-31 01:29
Duplicate of issue #224.

Until someone (you?) contributes a `LeptonicaFrameConverter`, you can find code for that here that converts to `Mat`:
https://github.com/deeplearning4j/DataVec/blob/master/datavec-data/datavec-data-image/src/main/java/org/datavec/image/loader/NativeImageLoader.java#L159
Which we can then convert to `BufferedImage` with `OpenCVFrameConverter` and `Java2DFrameConverter`: 
http://bytedeco.org/news/2015/04/04/javacv-frame-converters/
Or less efficiently with `Java2DFrameUtils`:
http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/Java2DFrameUtils.html

**Closed by saudet** 2018-01-31 01:29 UTC
Labels: duplicate, enhancement, question

**Comment by emara-geek** [comment] 2018-02-01 10:59
Ok, Thank you.

**Comment by saudet** [comment] 2018-02-07 05:18
BTW, if you end up creating the equivalent of a `LeptonicaFrameConverter`, please consider making a contribution. If you encounter any issues doing that, let me know and I will help. Thanks!

**Comment by saudet** [comment] 2018-05-21 02:04
I've finally implemented `LeptonicaFrameConverter` so we can now do something like this to convert efficiently an `BufferedImage` into a `PIX` for Tesseract:
```java
    Java2DFrameConverter converter = new Java2DFrameConverter();
    LeptonicaFrameConverter converter2 = new LeptonicaFrameConverter();

    PIX pix = converter2.convert(converter.convert(img));
```
Please give it a try with the snapshots (http://bytedeco.org/builds/) and let me know if you encounter any issues with it! Thanks

**Comment by saudet** [comment] 2019-01-31 07:01
@kev2316 See issue https://github.com/bytedeco/javacv/issues/1115.

**Comment by adam-osusky** [comment] 2024-02-29 12:30
> ```java
>     Java2DFrameConverter converter = new Java2DFrameConverter();
>     LeptonicaFrameConverter converter2 = new LeptonicaFrameConverter();
> 
>     PIX pix = converter2.convert(converter.convert(img));
> ```

This works.
