### ISSUE TITLE
Why OpenCV needs OpenBLAS ?

### ISSUE THREAD

**Issue by n-kai-cj** [bytedeco/javacpp-presets#943] opened 2020-09-11 14:59 UTC
I have questions.
1. Why javacpp+opencv doesn't work without openblas?
2. Is there any way to work javacpp+opencv without openblas?

**Comment by saudet** [comment] 2020-09-11 15:30
Duplicate of https://github.com/bytedeco/javacv/issues/1329

**Closed by saudet** 2020-09-11 15:30 UTC
Labels: duplicate, question

**Comment by n-kai-cj** [comment] 2020-09-11 15:47
Ah I understand. Thank you and sorry for duplicate.

**Comment by saudet** [comment] 2020-09-11 15:56
The reason is that operations such as GEMM used by many algorithms are a lot faster with OpenBLAS/MKL:
https://jamesbowley.co.uk/build-opencv-4-0-0-with-cuda-10-0-and-intel-mkl-tbb-in-windows/
