### ISSUE TITLE
Docker deployment in Scala no jniopencv_highgui in java.library.path (headless)

### ISSUE THREAD

**Issue by campin11** [bytedeco/javacpp-presets#1223] opened 2022-09-02 10:36 UTC
I'm using Scala, I've trouble deploying javacv in a docker using sbt DockerPlugin , is there a way to get the headless build without manually building the javaccp.

not sure why it gets the library from non existent folder "/home/{USER}/.javacpp/cache/" and using jniopencv_highgui , I believe is due to linking with all the other opencv libraries.

```
Exception in thread "io-compute-2" java.lang.UnsatisfiedLinkError: no jniopencv_highgui in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
        at java.lang.Runtime.loadLibrary0(Runtime.java:871)
        at java.lang.System.loadLibrary(System.java:1124)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1825)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1416)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1227)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1203)
        at org.bytedeco.opencv.global.opencv_highgui.<clinit>(opencv_highgui.java:23)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1282)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1227)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1203)
        at org.bytedeco.opencv.opencv_text.IntVector.<clinit>(IntVector.java:35)
        at example.backend.vision.DetectorOpenCV.postprocess(DetectorOpenCV.scala:82)
        at example.backend.vision.DetectorOpenCV.get(DetectorOpenCV.scala:182)
        at example.backend.vision.FrameReader$.testDetect$1(FrameReader.scala:81)
        at example.backend.vision.FrameReader$.$anonfun$testRun$2(FrameReader.scala:89)
        at example.backend.vision.FrameReader$.$anonfun$testRun$2$adapted(FrameReader.scala:89)
        at example.backend.vision.FrameReader.$anonfun$runProcess$3(FrameReader.scala:36)
        at example.backend.vision.FrameReader.$anonfun$runProcess$3$adapted(FrameReader.scala:35)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1279)
        at example.backend.vision.FrameReader.runProcess(FrameReader.scala:35)
        at example.backend.vision.FrameReader$.testRun(FrameReader.scala:89)
        at example.backend.Routes$$anonfun$routes$1.applyOrElse(Routes.scala:31)
        at example.backend.Routes$$anonfun$routes$1.applyOrElse(Routes.scala:27)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:313)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:309)
        at org.http4s.HttpRoutes$.$anonfun$of$2(HttpRoutes.scala:80)
        at cats.syntax.FlatMapOps$.$anonfun$$greater$greater$1(flatMap.scala:54)
        at cats.effect.IOFiber.next$2(IOFiber.scala:398)
        at cats.effect.IOFiber.runLoop(IOFiber.scala:409)
        at cats.effect.IOFiber.execR(IOFiber.scala:1332)
        at cats.effect.IOFiber.run(IOFiber.scala:139)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:461)
Caused by: java.lang.UnsatisfiedLinkError: /home/demiourgos728/.javacpp/cache/org.bytedeco.opencv-4.6.0-1.5.8-SNAPSHOT-linux-arm64.jar/org/bytedeco/opencv/linux-arm64/libjniopencv_highgui.so: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
        at java.lang.Runtime.load0(Runtime.java:810)
        at java.lang.System.load(System.java:1088)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1772)
        ... 33 more
java.lang.UnsatisfiedLinkError: no jniopencv_highgui in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
        at java.lang.Runtime.loadLibrary0(Runtime.java:871)
        at java.lang.System.loadLibrary(System.java:1124)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1825)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1416)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1227)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1203)
        at org.bytedeco.opencv.global.opencv_highgui.<clinit>(opencv_highgui.java:23)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1282)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1227)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1203)
        at org.bytedeco.opencv.opencv_text.IntVector.<clinit>(IntVector.java:35)
        at example.backend.vision.DetectorOpenCV.postprocess(DetectorOpenCV.scala:82)
        at example.backend.vision.DetectorOpenCV.get(DetectorOpenCV.scala:182)
        at example.backend.vision.FrameReader$.testDetect$1(FrameReader.scala:81)
        at example.backend.vision.FrameReader$.$anonfun$testRun$2(FrameReader.scala:89)
        at example.backend.vision.FrameReader$.$anonfun$testRun$2$adapted(FrameReader.scala:89)
        at example.backend.vision.FrameReader.$anonfun$runProcess$3(FrameReader.scala:36)
        at example.backend.vision.FrameReader.$anonfun$runProcess$3$adapted(FrameReader.scala:35)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1279)
        at example.backend.vision.FrameReader.runProcess(FrameReader.scala:35)
        at example.backend.vision.FrameReader$.testRun(FrameReader.scala:89)
        at example.backend.Routes$$anonfun$routes$1.applyOrElse(Routes.scala:31)
        at example.backend.Routes$$anonfun$routes$1.applyOrElse(Routes.scala:27)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:313)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:309)
        at org.http4s.HttpRoutes$.$anonfun$of$2(HttpRoutes.scala:80)
        at cats.syntax.FlatMapOps$.$anonfun$$greater$greater$1(flatMap.scala:54)
        at cats.effect.IOFiber.next$2(IOFiber.scala:398)
        at cats.effect.IOFiber.runLoop(IOFiber.scala:409)
        at cats.effect.IOFiber.execR(IOFiber.scala:1332)
        at cats.effect.IOFiber.run(IOFiber.scala:139)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:461)
Caused by: java.lang.UnsatisfiedLinkError: /home/demiourgos728/.javacpp/cache/org.bytedeco.opencv-4.6.0-1.5.8-SNAPSHOT-linux-arm64.jar/org/bytedeco/opencv/linux-arm64/libjniopencv_highgui.so: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
        at java.lang.Runtime.load0(Runtime.java:810)
        at java.lang.System.load(System.java:1088)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1772)
        ... 33 more
```

this is my sbt dependencies.

 ```
val javacppVersion = "1.5.8-SNAPSHOT"
val cpuPlatform = "linux-arm64"
val opencv           = "4.5.5"
val opencvPlatform   = "4.5.5-1.5.7"
val ffmpeg           = "5.0"
val ffmpegPlatform   = "5.0-1.5.7"
val openblas         = "0.3.19"
 
 lazy val presetLibs = Seq(
    "opencv" -> V.opencv
  ).flatMap { case (lib, ver) =>
    Seq(
      "org.bytedeco" % lib % s"$ver-${Project.javacppVersion}",
      "org.bytedeco" % lib % s"$ver-${Project.javacppVersion}" classifier Project.cpuPlatform
    )
  }

  lazy val presetLibs2 = Seq(
    "ffmpeg"   -> V.ffmpeg,
    "openblas" -> V.openblas
    //"openblas-platform" -> V.openblas
  ).flatMap { case (lib, ver) =>
    Seq(
      "org.bytedeco" % lib % s"$ver-1.5.7",
      "org.bytedeco" % lib % s"$ver-1.5.7" classifier Project.cpuPlatform
    )
  }

  lazy val backend: Seq[Def.Setting[_]] = common ++ Seq(
    resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots",
    libraryDependencies ++=
      http4sModules.map("org.http4s" %% _ % V.http4s) ++
        Seq(
          "org.bytedeco"                % "javacpp"            % Project.javacppVersion,
          "org.bytedeco"                % "javacpp"            % Project.javacppVersion classifier Project.cpuPlatform,
          "org.bytedeco"                % "javacv"             % Project.javacppVersion,
          "org.scala-lang.modules"     %% "scala-swing"        % V.scalaSwing,
          "org.scalafx"                %% "scalafx"            % V.scalafx,
          "org.scalafx"                %% "scalafx-extras"     % V.scalafxExtras,
          "org.bytedeco"                % "ffmpeg-platform"    % V.ffmpegPlatform,
          "org.bytedeco"                % "opencv-platform"    % V.opencvPlatform,
        ) ++ presetLibs ++ presetLibs2,
    dependencyOverrides ++= Seq("org.typelevel" % "cats-effect_2.13" % "3.3.12")
  )
```

help will be very much appreciated!

**Comment by saudet** [comment] 2022-09-02 10:42
Duplicate of #593

**Closed by saudet** 2022-09-02 10:42 UTC
Labels: duplicate, enhancement
