### ISSUE TITLE
Windows jar for 0.9.0

### ISSUE THREAD

**Issue by silvanheller** [bytedeco/javacpp-presets#284] opened 2016-09-13 10:47 UTC
There is no windows jar for the 0.9.0 version in the [maven repo](http://central.maven.org/maven2/org/bytedeco/javacpp-presets/tensorflow/0.9.0-1.2/)

**Comment by saudet** [comment] 2016-09-13 10:51
No, there isn't. Contributions welcome! Marking as duplicate of #111

**Closed by saudet** 2016-09-13 10:51 UTC
Labels: duplicate, enhancement
