### ISSUE TITLE
UnsatisfiedLinkError: no jniopencv_core in java.library.path

### ISSUE THREAD

**Issue by nobleson** [bytedeco/javacpp-presets#584] opened 2018-07-05 03:03 UTC
I am working with OpenCV 3.4.1 and Javacv1.4
I want to handle Opencv Mat and Javacv Mat respectively, and since i could not find a direct casting, i resolved to do some Conversions (normal with javacv):
javacv Mat -> IplImage && IplImage -> BufferedImage
Then i can write the BufferedImage using ImageIO library.
Anything wrong with this?
Okay My problems come from the conversion and i have the error above.
I tried using dependency walker as suggested by Samuel but it looks like an old time idea.
because Load(class) is removed [Javacv-Presset](http://bytedeco.org/javacpp/apidocs/index.html?org/bytedeco/javacpp/class-use/Loader.html) 
All i need is to seamlessly port Opencv Mat with Javacv Mat
Help please.

**Comment by saudet** [comment] 2018-07-05 03:18
That's a duplicate of https://github.com/bytedeco/javacpp/issues/38, see the solution here: https://github.com/bytedeco/javacpp/issues/38#issuecomment-140728812

**Closed by saudet** 2018-07-05 03:18 UTC
Labels: duplicate, question

**Comment by nobleson** [comment] 2018-07-05 03:30
Saudet , I have come across that but please i am not good at C++ and little idea of JNI (lazy Dude).
Here is what i manage to do. if you can suggest something better.
`    import java.awt.image.BufferedImage;

import org.bytedeco.javacpp.opencv_core.IplImage;
import org.bytedeco.javacpp.opencv_core.Mat;
import org.bytedeco.javacv.Frame;
import org.bytedeco.javacv.Java2DFrameConverter;
import org.bytedeco.javacv.OpenCVFrameConverter;

public class ImageConverter {

    public static IplImage toIplImage(BufferedImage src) {
    	  Java2DFrameConverter bimConverter = new Java2DFrameConverter();
    	  OpenCVFrameConverter.ToIplImage iplConverter = new OpenCVFrameConverter.ToIplImage();
    	  Frame frame = bimConverter.convert(src);
    	  IplImage img = iplConverter.convert(frame);
    	  IplImage result = img.clone();
    	  img.release();
    	  return result;
    	}
    public static IplImage toIplImage(Mat src) {
    	 OpenCVFrameConverter.ToIplImage iplConverter = new OpenCVFrameConverter.ToIplImage();
    	 OpenCVFrameConverter.ToMat  matConverter = new OpenCVFrameConverter.ToMat();
    	 Frame frame =  matConverter.convert(src);
    	 IplImage img = iplConverter.convert(frame);
    	 IplImage result = img.clone();
    	 img.release();
    	 return result;
    	}
    
    public static BufferedImage IplImageToBufferedImage(IplImage src) {
        OpenCVFrameConverter.ToIplImage grabberConverter = new OpenCVFrameConverter.ToIplImage();
        Java2DFrameConverter paintConverter = new Java2DFrameConverter();
        Frame frame = grabberConverter.convert(src);
        return paintConverter.getBufferedImage(frame,1);
    }
    
}
    `

**Comment by saudet** [comment] 2018-07-05 04:48
The `UnsatisfiedLinkError` isn't related to your Java code, it's related to the dependencies. Make sure to put all the JAR files of JavaCV in your class path, or add the `javacv-platform` dependency to your project file: https://github.com/bytedeco/javacv/#downloads
