### ISSUE TITLE
How about LLVM Cpp Bindings ?

### ISSUE THREAD

**Issue by lfkdsk** [bytedeco/javacpp-presets#767] opened 2019-07-23 07:08 UTC
Have we considered provide LLVM Cpp Bindings?

**Comment by saudet** [comment] 2019-07-23 07:09
Duplicate of #594

**Closed by saudet** 2019-07-23 07:09 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2019-07-24 00:46
To answer your question, yes, one of the main goals I want to achieve is to be able to parse the C++ API for LLVM and Clang. If you would like to participate, that would be great! Please tell us more about what interests you in one of the already opened threads. Thanks
