### ISSUE TITLE
Cant build with gradle from snapshot

### ISSUE THREAD

**Issue by sammerry** [bytedeco/javacpp-presets#183] opened 2016-03-19 00:13 UTC
When building with gradle i get the following error. However building with maven works.
```
Could not resolve all dependencies for configuration ':runtime'.
> Could not find javacpp-presets-${os.name}-${os.arch}.jar (org.bytedeco:javacpp-presets:1.2-SNAPSHOT).
  Searched in the following locations:
      file:/Users/samuelmerry/.m2/repository/org/bytedeco/javacpp-presets/1.2-SNAPSHOT/javacpp-presets-1.2-SNAPSHOT-${os.name}-${os.arch}.jar
```

gradle dependencies from mavenLocal()
```
dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.11'
    compile group: 'org.bytedeco', name: 'javacpp', version: '1.2-SNAPSHOT'
    compile group: 'org.bytedeco.javacpp-presets', name: 'tesseract', version: '3.04-1.2-SNAPSHOT'
    compile group: 'org.bytedeco.javacpp-presets', name: 'leptonica', version: '1.72-1.2-SNAPSHOT'
}
```

any suggestions?

**Comment by saudet** [comment] 2016-03-19 00:22
Sounds like a bug in Gradle. `${os.name}-${os.arch}` should have been expanded. Could you try to get the opinion of the Gradle developers?

**Comment by saudet** [comment] 2016-05-19 06:08
Marking as duplicate of https://github.com/bytedeco/javacv/issues/395  The workaround is to include this in your `gradle.build` file:
```groovy
configurations {
    all*.exclude group: 'org.bytedeco', module: 'javacpp-presets'
}
```

**Closed by saudet** 2016-05-19 06:08 UTC
Labels: bug, duplicate
