### ISSUE TITLE
can't build with gradle

### ISSUE THREAD

**Issue by pedroSG94** [bytedeco/javacpp-presets#216] opened 2016-05-10 14:16 UTC
This is the error:

Error:Failed to resolve: org.bytedeco.javacpp-presets:ffmpeg:3.0.2-1.2-SNAPSHOT
Error:Failed to resolve: org.bytedeco:javacv:1.2-SNAPSHOT

Gradle code:

```
dependencies {
  compile group: 'org.bytedeco', name: 'javacv', version: '1.2-SNAPSHOT'
  compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.0.2-1.2-SNAPSHOT', classifier: 'android-arm'
}
```
any idea?

**Comment by saudet** [comment] 2016-05-11 04:53
Unfortunately, for now, we need to do things manually with Gradle:
https://github.com/bytedeco/javacv/wiki/Configuring-Proguard-for-JavaCV#gradle-settings

Duplicate of https://github.com/bytedeco/javacv/issues/395: A contribution would be most welcome!

Also, make sure you have compiled 1.2-SNAPSHOT from source:
https://github.com/bytedeco/javacpp-presets/#build-instructions

**Closed by saudet** 2016-05-11 04:53 UTC
Labels: duplicate, enhancement, question
