### ISSUE TITLE
[hwaccel]How to enable hardware acceleration in ffmpeg of javacv

### ISSUE THREAD

**Issue by Cesareans** [bytedeco/javacpp-presets#708] opened 2019-04-04 04:36 UTC

**Comment by saudet** [comment] 2019-04-04 04:44
Duplicate of https://github.com/bytedeco/javacv/issues/1154 and https://github.com/bytedeco/javacv/issues/1163

Call something like `setOption("hwaccel", "cuvid")`, `setOption("hwaccel", "h264_videotoolbox")`, etc.

**Closed by saudet** 2019-04-04 04:44 UTC
Labels: duplicate, question

**Comment by Cesareans** [comment] 2019-04-04 05:05
Thks, I just tried and the effect seems awesome. But there are another problem that are if i can use CUDA or  other to give javacv full GPU acceleration.

**Comment by saudet** [comment] 2019-04-04 05:08
If you need encoding, we can use "h264_cuvid", for example, see issue https://github.com/bytedeco/javacv/issues/1154.

**Comment by Cesareans** [comment] 2019-04-04 05:32
Actually i need both encoding and decoding. Can i still use "h264_cuvid" for codec of both are not ".h264", "vp8" in encoding for example.

**Comment by saudet** [comment] 2019-04-04 05:35
All details about what is supported are here:
https://trac.ffmpeg.org/wiki/HWAccelIntro

**Comment by Cesareans** [comment] 2019-04-04 05:40
Oh, i see. And the last problem, is recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264) the same with grab.setVideoCodecName("h264_cuvid");

**Comment by saudet** [comment] 2019-04-21 13:01
`setVideoCodecName()` overrides `setVideoCodec()`, so we don't need to set the latter, but you can leave it there if that's convenient.
