### ISSUE TITLE
no jniopencv_core and gomp in path on Jetson TX2

### ISSUE THREAD

**Issue by StarlightNL** [bytedeco/javacpp-presets#769] opened 2019-07-25 12:31 UTC
I finaly got cuda and opencv to compile on my Jetson TX2 but when I run it the program says it cannot find jniopencv_core and gomp but they are in the jar file opencv-4.0.1-1.5-linux-arm64-gpu.jar 
![image](https://user-images.githubusercontent.com/7126102/61874484-cdce3600-aee8-11e9-9962-2a07e0fda329.png)

What am I doing wrong?

**Comment by saudet** [comment] 2019-07-25 12:39
Duplicate of #735

**Comment by saudet** [comment] 2019-07-25 12:40
I'll let @kwatters answer that one. :)

**Closed by saudet** 2019-07-25 12:39 UTC
Labels: duplicate, enhancement, question

**Comment by kwatters** [comment] 2019-07-26 00:32
I haven't built opencv with gpu support yet ...but.. I do have the arm64 jars for javacv / opencv 1.5 here.  

http://repo.myrobotlab.org/artifactory/webapp/#/artifacts/browse/tree/General/myrobotlab/org/bytedeco

These aren't official builds, but they do work with the Nano.    

I have a feeling that cuda & opencv is a bit of a deeper topic...  as far as I can tell, Intel GPUs are pretty well supported in OpenCV.. but I can't say the same for Cuda.

Anyway, grab the javacv arm64 jars there and you'll get the dependency you are looking for to get opencv / javacv working on the arm64 ( jetson ) boards.

**Comment by saudet** [comment] 2019-07-26 00:36
Ah, I see. We'll need to add `linux-arm64` and `linux-ppc64le` at least here:
https://github.com/bytedeco/javacpp-presets/blob/master/opencv/src/main/java/org/bytedeco/opencv/presets/opencv_core.java#L88

**Comment by StarlightNL** [comment] 2019-07-26 07:33
@kwatters You are right that Cuda and opencv are a bit more of a deep topic, but to do it on a Intel GPu beats the advantage of cuda. What needs to be done is to allow to choose the cuda version. It will be more work but it may be easier to support the Jetson line in a whole. Not just the Jetson Nano.

@saudet I will try to compile it with those things added and an other line since it does not exist on the cuda-100 branch. I will report back when it's done compiling

**Comment by StarlightNL** [comment] 2019-07-26 09:49
@saudet You sir, are a genius. That was the problem. When I added that single bit it just launched. The only problem now is that it won't find opencv_cuda. In the screenshot below everthing with cuda
![image](https://user-images.githubusercontent.com/7126102/61942285-658b5d00-af99-11e9-94de-dcbbb750b7b3.png)

the error is:
```
[26-07-2019 11:47:34:138] WARNING:      nl.ideax.farmbot.camera.CameraHandler.streamFrameHandler(167)   java.lang.RuntimeException: OpenCV(4.0.1) /home/farmbotcamera/sourcebuilding/javacpp-presets/opencv/cppbuild/linux-arm64-gpu/opencv-4.0.1/modules/core/src/matrix_wrap.cpp:359: error: (-213:The function/feature is not implemented) getGpuMat is available only for cuda::GpuMat and cuda::HostMem in function 'getGpuMat'

        at org.bytedeco.opencv.opencv_core.GpuMat.copyTo(Native Method)
        at nl.ideax.farmbot.moduleresources.opencv.OpenCVHelpers.createBufferedImage(OpenCVHelpers.java:57)
        at nl.ideax.farmbot.moduleresources.opencv.Camera.nextBufferedImage(Camera.java:59)
        at nl.ideax.farmbot.camera.CameraHandler.streamFrameHandler(CameraHandler.java:127)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

Below is the output from loading the java app with opencv
```
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_cudev.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_core.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_imgproc.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_core.so
Loading class org.bytedeco.opencv.global.opencv_core
Registering org.bytedeco.opencv.opencv_core.CvSlice[address=0x7f8c657a40,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f8c657a40,deallocatorAddress=0x7f64538c68]]
Registering org.bytedeco.opencv.opencv_core.CvSlice[address=0x7f8c4d45b0,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f8c4d45b0,deallocatorAddress=0x7f64538c68]]
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_imgproc.so
Loading class org.bytedeco.opencv.global.opencv_imgcodecs
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_imgcodecs
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_imgcodecs.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_imgcodecs.so
Loading class org.bytedeco.opencv.global.opencv_videoio
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_imgcodecs
Loading class org.bytedeco.opencv.global.opencv_videoio
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_videoio.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_videoio.so
Loading class org.bytedeco.opencv.global.opencv_highgui
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_imgcodecs
Loading class org.bytedeco.opencv.global.opencv_videoio
Loading class org.bytedeco.opencv.global.opencv_highgui
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_highgui.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_highgui.so
Loading class org.bytedeco.opencv.global.opencv_flann
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_flann
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_flann.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_flann.so
Loading class org.bytedeco.opencv.global.opencv_features2d
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_imgcodecs
Loading class org.bytedeco.opencv.global.opencv_videoio
Loading class org.bytedeco.opencv.global.opencv_highgui
Loading class org.bytedeco.opencv.global.opencv_flann
Loading class org.bytedeco.opencv.global.opencv_features2d
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_features2d.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_features2d.so
Loading class org.bytedeco.opencv.global.opencv_calib3d
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_imgcodecs
Loading class org.bytedeco.opencv.global.opencv_videoio
Loading class org.bytedeco.opencv.global.opencv_highgui
Loading class org.bytedeco.opencv.global.opencv_flann
Loading class org.bytedeco.opencv.global.opencv_features2d
Loading class org.bytedeco.opencv.global.opencv_calib3d
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_calib3d.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_calib3d.so
Loading class org.bytedeco.opencv.global.opencv_aruco
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_imgcodecs
Loading class org.bytedeco.opencv.global.opencv_videoio
Loading class org.bytedeco.opencv.global.opencv_highgui
Loading class org.bytedeco.opencv.global.opencv_flann
Loading class org.bytedeco.opencv.global.opencv_features2d
Loading class org.bytedeco.opencv.global.opencv_calib3d
Loading class org.bytedeco.opencv.global.opencv_aruco
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_aruco.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_aruco.so
Loading class org.bytedeco.opencv.global.opencv_video
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_imgcodecs
Loading class org.bytedeco.opencv.global.opencv_videoio
Loading class org.bytedeco.opencv.global.opencv_highgui
Loading class org.bytedeco.opencv.global.opencv_flann
Loading class org.bytedeco.opencv.global.opencv_features2d
Loading class org.bytedeco.opencv.global.opencv_calib3d
Loading class org.bytedeco.opencv.global.opencv_video
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_video.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_video.so
Loading class org.bytedeco.opencv.global.opencv_bgsegm
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_imgcodecs
Loading class org.bytedeco.opencv.global.opencv_videoio
Loading class org.bytedeco.opencv.global.opencv_highgui
Loading class org.bytedeco.opencv.global.opencv_flann
Loading class org.bytedeco.opencv.global.opencv_features2d
Loading class org.bytedeco.opencv.global.opencv_calib3d
Loading class org.bytedeco.opencv.global.opencv_video
Loading class org.bytedeco.opencv.global.opencv_bgsegm
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_bgsegm.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_bgsegm.so
Loading class org.bytedeco.opencv.global.opencv_bioinspired
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_imgcodecs
Loading class org.bytedeco.opencv.global.opencv_videoio
Loading class org.bytedeco.opencv.global.opencv_highgui
Loading class org.bytedeco.opencv.global.opencv_bioinspired
[26-07-2019 11:30:22:509] INFO:         nl.ideax.farmbot.applications.Main.main(75)     Started Module Applications
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_bioinspired.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_bioinspired.so
Loading class org.bytedeco.opencv.global.opencv_objdetect
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_imgcodecs
Loading class org.bytedeco.opencv.global.opencv_videoio
Loading class org.bytedeco.opencv.global.opencv_highgui
Loading class org.bytedeco.opencv.global.opencv_flann
Loading class org.bytedeco.opencv.global.opencv_features2d
Loading class org.bytedeco.opencv.global.opencv_calib3d
Loading class org.bytedeco.opencv.global.opencv_objdetect
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_objdetect.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_objdetect.so
Loading class org.bytedeco.opencv.global.opencv_photo
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_photo
Loading library opencv_cuda
Failed to load for opencv_cuda@.4.0: java.lang.UnsatisfiedLinkError: no opencv_cuda in java.library.path: [., /usr/local/cuda-10.0/lib64, /usr/local/lib, /usr/java/packages/lib, /usr/lib/aarch64-linux-gnu/jni, /lib/aarch64-linux-gnu, /usr/lib/aarch64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_cudaarithm.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_cudaimgproc.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_photo.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_photo.so
Loading class org.bytedeco.opencv.global.opencv_face
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_imgcodecs
Loading class org.bytedeco.opencv.global.opencv_videoio
Loading class org.bytedeco.opencv.global.opencv_highgui
Loading class org.bytedeco.opencv.global.opencv_flann
Loading class org.bytedeco.opencv.global.opencv_features2d
Loading class org.bytedeco.opencv.global.opencv_calib3d
Loading class org.bytedeco.opencv.global.opencv_objdetect
Loading class org.bytedeco.opencv.global.opencv_photo
Loading class org.bytedeco.opencv.global.opencv_face
Loading library opencv_cuda
Failed to load for opencv_cuda@.4.0: java.lang.UnsatisfiedLinkError: no opencv_cuda in java.library.path: [., /usr/local/cuda-10.0/lib64, /usr/local/lib, /usr/java/packages/lib, /usr/lib/aarch64-linux-gnu/jni, /lib/aarch64-linux-gnu, /usr/lib/aarch64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_face.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_face.so
Loading class org.bytedeco.opencv.global.opencv_img_hash
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_img_hash
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_img_hash.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_img_hash.so
Loading class org.bytedeco.opencv.global.opencv_phase_unwrapping
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_phase_unwrapping
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_phase_unwrapping.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_phase_unwrapping.so
Loading class org.bytedeco.opencv.global.opencv_structured_light
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_phase_unwrapping
Loading class org.bytedeco.opencv.global.opencv_imgcodecs
Loading class org.bytedeco.opencv.global.opencv_videoio
Loading class org.bytedeco.opencv.global.opencv_highgui
Loading class org.bytedeco.opencv.global.opencv_flann
Loading class org.bytedeco.opencv.global.opencv_features2d
Loading class org.bytedeco.opencv.global.opencv_calib3d
Loading class org.bytedeco.opencv.global.opencv_structured_light
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_structured_light.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_structured_light.so
Loading class org.bytedeco.opencv.global.opencv_dnn
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_dnn
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_dnn.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_dnn.so
Loading class org.bytedeco.opencv.global.opencv_ml
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_ml
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_ml.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_ml.so
Loading class org.bytedeco.opencv.global.opencv_text
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_dnn
Loading class org.bytedeco.opencv.global.opencv_imgcodecs
Loading class org.bytedeco.opencv.global.opencv_videoio
Loading class org.bytedeco.opencv.global.opencv_highgui
Loading class org.bytedeco.opencv.global.opencv_flann
Loading class org.bytedeco.opencv.global.opencv_features2d
Loading class org.bytedeco.opencv.global.opencv_ml
Loading class org.bytedeco.opencv.global.opencv_text
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_text.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_text.so
Loading class org.bytedeco.opencv.global.opencv_plot
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_plot
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_plot.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_plot.so
Loading class org.bytedeco.opencv.global.opencv_tracking
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_plot
Loading class org.bytedeco.opencv.global.opencv_imgcodecs
Loading class org.bytedeco.opencv.global.opencv_videoio
Loading class org.bytedeco.opencv.global.opencv_highgui
Loading class org.bytedeco.opencv.global.opencv_flann
Loading class org.bytedeco.opencv.global.opencv_features2d
Loading class org.bytedeco.opencv.global.opencv_calib3d
Loading class org.bytedeco.opencv.global.opencv_video
Loading class org.bytedeco.opencv.global.opencv_dnn
Loading class org.bytedeco.opencv.global.opencv_tracking
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_tracking.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_tracking.so
Loading class org.bytedeco.opencv.global.opencv_shape
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_imgcodecs
Loading class org.bytedeco.opencv.global.opencv_videoio
Loading class org.bytedeco.opencv.global.opencv_highgui
Loading class org.bytedeco.opencv.global.opencv_flann
Loading class org.bytedeco.opencv.global.opencv_features2d
Loading class org.bytedeco.opencv.global.opencv_calib3d
Loading class org.bytedeco.opencv.global.opencv_shape
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_shape.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_shape.so
Loading class org.bytedeco.opencv.global.opencv_xfeatures2d
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_ml
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_imgcodecs
Loading class org.bytedeco.opencv.global.opencv_videoio
Loading class org.bytedeco.opencv.global.opencv_highgui
Loading class org.bytedeco.opencv.global.opencv_flann
Loading class org.bytedeco.opencv.global.opencv_features2d
Loading class org.bytedeco.opencv.global.opencv_calib3d
Loading class org.bytedeco.opencv.global.opencv_shape
Loading class org.bytedeco.opencv.global.opencv_xfeatures2d
Loading library opencv_cuda
Failed to load for opencv_cuda@.4.0: java.lang.UnsatisfiedLinkError: no opencv_cuda in java.library.path: [., /usr/local/cuda-10.0/lib64, /usr/local/lib, /usr/java/packages/lib, /usr/lib/aarch64-linux-gnu/jni, /lib/aarch64-linux-gnu, /usr/lib/aarch64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_xfeatures2d.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_xfeatures2d.so
Loading class org.bytedeco.opencv.global.opencv_ximgproc
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_imgcodecs
Loading class org.bytedeco.opencv.global.opencv_videoio
Loading class org.bytedeco.opencv.global.opencv_highgui
Loading class org.bytedeco.opencv.global.opencv_flann
Loading class org.bytedeco.opencv.global.opencv_features2d
Loading class org.bytedeco.opencv.global.opencv_calib3d
Loading class org.bytedeco.opencv.global.opencv_ximgproc
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_ximgproc.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_ximgproc.so
Loading class org.bytedeco.opencv.global.opencv_xphoto
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_photo
Loading class org.bytedeco.opencv.global.opencv_xphoto
Loading library opencv_cuda
Failed to load for opencv_cuda@.4.0: java.lang.UnsatisfiedLinkError: no opencv_cuda in java.library.path: [., /usr/local/cuda-10.0/lib64, /usr/local/lib, /usr/java/packages/lib, /usr/lib/aarch64-linux-gnu/jni, /lib/aarch64-linux-gnu, /usr/lib/aarch64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_xphoto.so.4.0
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_xphoto.so
Loading library opencv_cuda
Failed to load for opencv_cuda@.4.0: java.lang.UnsatisfiedLinkError: no opencv_cuda in java.library.path: [., /usr/local/cuda-10.0/lib64, /usr/local/lib, /usr/java/packages/lib, /usr/lib/aarch64-linux-gnu/jni, /lib/aarch64-linux-gnu, /usr/lib/aarch64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
Loading /root/.javacpp/cache/opencv-4.0.1-1.5-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libopencv_java.so
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.global.opencv_imgproc
Loading class org.bytedeco.opencv.global.opencv_imgcodecs
Loading class org.bytedeco.opencv.global.opencv_videoio
Registering org.bytedeco.opencv.opencv_videoio.VideoCapture[address=0x7f8cf5d0f0,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f8cf5d0f0,deallocatorAddress=0x7f7400d138]]
Loading class org.bytedeco.opencv.global.opencv_core
Registering org.bytedeco.opencv.opencv_core.GpuMat[address=0x7f8cf5fc70,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f8cf5fc70,deallocatorAddress=0x7f645382b8]]
Registering org.bytedeco.opencv.opencv_core.GpuMat[address=0x7f8cf60700,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f8cf60700,deallocatorAddress=0x7f645382b8]]
Registering org.bytedeco.opencv.opencv_core.GpuMat[address=0x7f8d4feee0,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f8d4feee0,deallocatorAddress=0x7f645382b8]]
Registering org.bytedeco.opencv.opencv_core.GpuMat[address=0x7f8d4ff860,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f8d4ff860,deallocatorAddress=0x7f645382b8]]
Registering org.bytedeco.opencv.opencv_videoio.VideoCapture[address=0x7f8ec02af0,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f8ec02af0,deallocatorAddress=0x7f7400d138]]
Registering org.bytedeco.opencv.opencv_core.GpuMat[address=0x7f8ec02b20,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f8ec02b20,deallocatorAddress=0x7f645382b8]]

```

when the cmake command finished it did say that cuda was being used. What could be wrong now? At this point

**Comment by saudet** [comment] 2019-07-27 14:45
`opencv_cuda` doesn't exist as a module anymore. We can probably remove it...

**Comment by StarlightNL** [comment] 2019-07-29 07:07
Is it just a case of removing the places where it loads opencv_cuda or do I need to do some more things?
Will that also fix the other issue of that GpuMat cannot be used because of the error
```
getGpuMat is available only for cuda::GpuMat and cuda::HostMem in function 'getGpuMat'
```

**Comment by saudet** [comment] 2019-07-29 07:11
We can remove the `opencv_cuda` entries, but it's not going to fix anything, no. It just looks like `getGpuMat()` isn't implemented, but you'll need to ask the developers of OpenCV to be sure.

**Comment by StarlightNL** [comment] 2019-07-29 07:31
Ok, thanks for the help. Then I will open a issue on the opencv repo. 
The only problem I will get is that they will not implement it on 4.0.1 and I do not know if the wrappers will work on any build version and configuration of 4.1.0. 
Is it also possible to contact you an other way or are github issues fine for further problems?

**Comment by saudet** [comment] 2019-07-29 07:34
Unless you plan to implement `getGpuMat()` yourself, they'll probably recommend to use something like `copyTo` I assume... In any case, of course, please let me know if you encounter any other issues.
