### ISSUE TITLE
Linker Issue: cannot find shared library

### ISSUE THREAD

**Issue by benshiffman** [bytedeco/javacpp-presets#1202] opened 2022-07-25 19:11 UTC
Hello,

Upon running "mvn clean install -Djavacpp.platform.host" to attempt to build a simple test library named "shared," I am getting an error stating, "/usr/bin/ld: cannot find -llibshared.so". I've checked to make sure that libshared.so is in fact in the linked directory, has the correct name, that ld and g++ are both up to date.

Has anyone encountered this before?

For reference, I'm running this on Ubuntu through WSL 1.

Please find command output [here](https://github.com/bytedeco/javacpp-presets/files/9184072/output.txt).

Edit:
Interestingly, I'm getting the exact same error when using the method on JavaCPP's [Mapping Recipes](https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes) page.

**Comment by saudet** [comment] 2022-07-26 00:20
Duplicate of https://github.com/bytedeco/javacpp/issues/594

**Closed by saudet** 2022-07-26 00:20 UTC
Labels: duplicate, question
