### ISSUE TITLE
Approximate release of 1.5.10?

### ISSUE THREAD

**Issue by blueberry** [bytedeco/javacpp-presets#1429] opened 2023-10-27 23:34 UTC
Is there any rough target date for 1.5.10?
There are a few major library versions that were updated since the last release, and are still only available in JavaCPP snapshots.

**Comment by mkitti** [comment] 2023-10-30 15:16
It's usually been 6+ months between releases.

**Comment by blueberry** [comment] 2023-10-30 15:44
The most reliable pattern I've noticed is two releases a year.  That's why I hope there is one in the next month or two.

**Comment by saudet** [comment] 2023-10-31 09:07
Duplicate of #1351

**Closed by saudet** 2023-10-31 09:07 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2023-11-26 01:08
@blueberry BTW, Mac isn't supported by MKL anymore, so if you need it you'll need to find an alternative: https://www.intel.com/content/www/us/en/docs/onemkl/developer-guide-macos/2024-0/overview.html

**Comment by blueberry** [comment] 2023-11-26 09:54
Thanks for notifying me. It is what it is. I don't need it personally, but for the mac users I'll have to find a replacement anyway (eventually) for Apple sillicon based machines. I suppose we'll have to provide something along these lines in JavaCPP (eventually!).

**Comment by saudet** [comment] 2023-12-10 11:13
OpenBLAS already works fine on all platforms. There is no need for MKL, expect as an optimization for Intel CPUs

**Comment by blueberry** [comment] 2023-12-10 14:17
Except for many non-blas operations and statistical fonctions available in
MKL...

**Comment by saudet** [comment] 2023-12-17 11:09
GSL seems to be pretty complete for that, and works on all platforms as well, again not as optimized as MKL on Intel processors, but that's pretty much what MKL is only useful for

**Comment by saudet** [comment] 2023-12-17 11:15
FYI: https://www.gnu.org/software/gsl/doc/html/statistics.html

**Comment by saudet** [comment] 2023-12-25 05:55
@blueberry In any case, please make sure I didn't miss anything for MKL in commit https://github.com/bytedeco/javacpp-presets/commit/6e36cac407af28bfac011cd0b99352f16adf3bee

**Comment by blueberry** [comment] 2023-12-27 15:08
I'll test it in a few days and keep you posted.

**Comment by blueberry** [comment] 2024-01-11 17:35
@saudet Both MKL  2024.0 and DNNL 3.3.3 work for me.
