### ISSUE TITLE
Adding libraries to cppbuild.sh

### ISSUE THREAD

**Issue by peardox** [bytedeco/javacpp-presets#763] opened 2019-07-16 23:10 UTC
Hi

I'm (trying) to build JavaCPP-Presets on my Jetson Nano and have an issue with CUDA

It dies at this point...

```
[INFO] g++ -I/usr/local/cuda-10.0/include/ -I/usr/lib/jvm/java-8-openjdk-arm64/include -I/usr/lib/jvm/java-8-openjdk-arm64/include/linux /home/simon/src/jcpp/1.4.2/javacpp-presets/cuda/target/classes/org/bytedeco/javacpp/jnicufft.cpp /home/simon/src/jcpp/1.4.2/javacpp-presets/cuda/target/classes/jnijavacpp.cpp -O3 -s -Wl,-rpath,$ORIGIN/ -Wl,-z,noexecstack -Wl,-Bsymbolic -Wall -fPIC -shared -o libjnicufft.so -lcufft -lcuda -lcudart
In file included from /usr/local/cuda-10.0/include/driver_functions.h:54:0,
                 from /home/simon/src/jcpp/1.4.2/javacpp-presets/cuda/target/classes/org/bytedeco/javacpp/jnicufft.cpp:99:
/usr/local/cuda-10.0/include/crt/host_defines.h:54:2: warning: #warning "crt/host_defines.h is an internal header file and must not be used directly.  Please use cuda_runtime_api.h or cuda_runtime.h instead." [-Wcpp]
 #warning "crt/host_defines.h is an internal header file and must not be used directly.  Please use cuda_runtime_api.h or cuda_runtime.h instead."
  ^~~~~~~
/usr/bin/ld: cannot find -lcufft
```

If I cut + paste the command used to compile and add `-L/usr/local/cuda-10.0/targets/aarch64-linux/lib` to that one it works

So, given this...

```
linux-arm64)
        if [[ ! -d "/usr/local/cuda/" ]]; then
            echo "Please install CUDA under the default installation directory"
            exit 1
        fi
        ;;
```

How do I add my "-L/usr/local/cuda-10.0/targets/aarch64-linux/lib" to it so it gets passed thru?

**Comment by saudet** [comment] 2019-07-16 23:27
Duplicate of #735

**Comment by saudet** [comment] 2019-07-16 23:27
You'll need to use the "cuda100" branch as there are no CUDA 10.1 yet available for Jetson.

**Closed by saudet** 2019-07-16 23:27 UTC
Labels: duplicate, enhancement

**Comment by peardox** [comment] 2019-07-16 23:34
I'm using the version from 1.4.4 inside 1.4.2

All I want to know is how to include the lib in the g++ statement...

It says it's 10.0 all the way through the snippet above

**Comment by saudet** [comment] 2019-07-16 23:44
The right directories are already all there:
https://github.com/bytedeco/javacpp-presets/blob/cuda100/cuda/src/main/java/org/bytedeco/cuda/presets/cudart.java#L41
Even for 1.4.4 and 1.4.2:
https://github.com/bytedeco/javacpp-presets/blob/1.4.4/cuda/src/main/java/org/bytedeco/javacpp/presets/cuda.java#L41
https://github.com/bytedeco/javacpp-presets/blob/1.4.2/cuda/src/main/java/org/bytedeco/javacpp/presets/cuda.java#L40
You can modify those if you need though.

**Comment by peardox** [comment] 2019-07-17 02:05
Thanks

Just added linux-arm64 and it went thru smootly
