### ISSUE TITLE
Is ptx backend support in LLVM preset?

### ISSUE THREAD

**Issue by oneengineer** [bytedeco/javacpp-presets#981] opened 2020-12-08 17:19 UTC
I am using `llvm-platform 10.0.0-1.5.3`

I got error when calling 
`LLVMGetTargetFromTriple`
return error code: 1 
error string: `No available targets are compatible with triple "nvptx64-nvidia-cuda"`

I wonder whether it is supported in LLVM presets(maybe when you compile the LLVM with some flags on) or not.

Myself compiled LLVM's tool llc can compile "nvptx64-nvidia-cuda" triple target code.

For the detail check: https://llvm.org/docs/NVPTXUsage.html

**Comment by supergrecko** [comment] 2020-12-08 17:21
This was an issue which was resolved in #937 which requires version 10.0.1-1.5.4 or higher.

**Comment by saudet** [comment] 2020-12-09 00:38
Duplicate of #932

**Closed by saudet** 2020-12-09 00:38 UTC
Labels: duplicate, enhancement, question
