### ISSUE TITLE
[GSL] Could not found "libgnustl_static.so"

### ISSUE THREAD

**Issue by houxg** [bytedeco/javacpp-presets#178] opened 2016-03-09 09:31 UTC
Hi, I was using javacpp-presets/gsl project, It works fine in most of device. However I get this error message while running on LG G3(Android 5.0.1)

```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "gsl_nan" referenced by "libjnigsl.so"...
                                                                                          at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                                                          at java.lang.System.loadLibrary(System.java:989)
                                                                                          at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:632)
                                                                                          at org.bytedeco.javacpp.Loader.load(Loader.java:470)
                                                                                          at org.bytedeco.javacpp.Loader.load(Loader.java:407)
                                                                                          at org.bytedeco.javacpp.gsl.<clinit>(gsl.java:10)`

`Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.misfitwearables.prometheus.debug-2/base.apk"],nativeLibraryDirectories=[/data/app/com.misfitwearables.prometheus.debug-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libgnustl_static.so"
                                                                                          at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                                          at java.lang.System.loadLibrary(System.java:989)
                                                                                          at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:632)
                                                                                          at org.bytedeco.javacpp.Loader.load(Loader.java:461)
                                                                                          at org.bytedeco.javacpp.Loader.load(Loader.java:407) 
                                                                                          at org.bytedeco.javacpp.gsl.<clinit>(gsl.java:10) 
```

**Comment by saudet** [comment] 2016-03-09 10:30
What version of JavaCPP?

**Comment by houxg** [comment] 2016-03-09 11:29
It's not the latest version, the sha of commit is 802fc48. Have the latest version solved this problem?

**Comment by houxg** [comment] 2016-03-09 12:09
Using the latest version but still get the same error.

` java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "gsl_complex_rect" referenced by "libjnigsl.so"...
                                                                                        at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                                                        at java.lang.System.loadLibrary(System.java:989)
                                                                                        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:632)
                                                                                        at org.bytedeco.javacpp.Loader.load(Loader.java:470)
                                                                                        at org.bytedeco.javacpp.Loader.load(Loader.java:407)
                                                                                        at org.bytedeco.javacpp.gsl.<clinit>(gsl.java:10)`

'Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.misfitwearables.prometheus.debug-2/base.apk"],nativeLibraryDirectories=[/data/app/com.misfitwearables.prometheus.debug-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libgnustl_static.so"
                                                                                        at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                                        at java.lang.System.loadLibrary(System.java:989)
                                                                                        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:632)
                                                                                        at org.bytedeco.javacpp.Loader.load(Loader.java:461)
                                                                                        at org.bytedeco.javacpp.Loader.load(Loader.java:407) 
                                                                                        at org.bytedeco.javacpp.gsl.<clinit>(gsl.java:10) '

**Comment by saudet** [comment] 2016-03-09 12:51
Right now, you're the only person with this problem.

How did you build your binaries for GSL using the latest version of JavaCPP?

**Comment by houxg** [comment] 2016-03-09 13:13
I follow what wiki says and running these script on Mac OSX
`cd javacpp`
`sudo mvn clean install`
`cd ../javacpp-presets/gsl`
`sudo ./cppbuild.sh -platform android-arm install`
`sudo mvn clean install -Djavacpp.platform=android-arm -Djavacpp.platform.root=~/Android/android-ndk -Djavacpp.platform.compiler=~/Android/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++`

I put the generated javacpp.jar and gsl.jar into the project/libs folder. Then extract the .so file from gsl-android.jar and put them into the project/libs/armeabi, project/armeabi-v7a folder.

Curiously, this error only happen on LG G3. I have tested the app in other phones, it works fine.

**Comment by saudet** [comment] 2016-03-09 13:49
If you get text relocations, this might be related to https://github.com/bytedeco/javacv/issues/245

**Comment by houxg** [comment] 2016-03-10 15:00
I found that the app works fine in my Nexus 6P. But before the .so files were loaded, I got these message:
`03-10 22:32:08.122 4518-4518/org.houxg.gsldemo W/linker: /data/app/org.houxg.gsldemo-1/lib/arm/libgsl.so: unused DT entry: type 0x1d arg 0x1b57f`
`03-10 22:32:08.134 4518-4518/org.houxg.gsldemo W/linker: /data/app/org.houxg.gsldemo-1/lib/arm/libjnigsl.so: unused DT entry: type 0x1d arg 0xd2e19`
`03-10 22:32:08.134 4518-4518/org.houxg.gsldemo W/linker: /data/app/org.houxg.gsldemo-1/lib/arm/libjnigsl.so: is missing DT_SONAME will use basename as a replacement: "libjnigsl.so"`
 
Is this cause by the text relocations?

**Comment by saudet** [comment] 2016-03-11 01:54
I don't think so, no. BTW, some devices don't install native libraries properly:
https://medium.com/keepsafe-engineering/the-perils-of-loading-native-libraries-on-android-befa49dce2db
Make sure this isn't happening.

**Comment by saudet** [comment] 2016-05-19 06:00
Are you still having issues with this? If so, could you try again? I've just released version 1.2 and it might make things better.

**Comment by iamyellow** [comment] 2016-06-02 18:27
hey! actually he's not the only user facing this problem :(
but the crash in our case happens w/ javacv. we manually installed the jars and .so files as like @houxg described. we downloaded the binaries from javacv github repo home links. i guess they're updated (1.2), right?
the thing is we've started to test our app in a Nexus 4, and everything worked like a charm. but after a few days a ton of things (like setting target sdk to 22) we're not able to find a solution, always the stacktrace crash:

06-02 19:20:09.211: E/AndroidRuntime(14662): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNK2cv14DefaultDeleterI13CvFileStorageEclEPS1_" referenced by "libjniopencv_core.so"...
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at java.lang.System.loadLibrary(System.java:989)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:654)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at org.bytedeco.javacpp.Loader.load(Loader.java:492)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at org.bytedeco.javacpp.Loader.load(Loader.java:409)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at java.lang.Class.classForName(Native Method)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at java.lang.Class.forName(Class.java:308)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at org.bytedeco.javacpp.Loader.load(Loader.java:464)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at org.bytedeco.javacpp.Loader.load(Loader.java:409)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at org.bytedeco.javacpp.helper.opencv_core$AbstractArray.<clinit>(opencv_core.java:109)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at es.ipsa.cloudcheck.scanner.CameraPreview.onPreviewFrame(CameraPreview.java:337)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1160)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at android.os.Looper.loop(Looper.java:145)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at es.ipsa.cloudcheck.scanner.CameraPreview$2.run(CameraPreview.java:169)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at java.lang.Thread.run(Thread.java:818)
06-02 19:20:09.211: E/AndroidRuntime(14662): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/es.ipsa.cloudcheckar-1/base.apk"],nativeLibraryDirectories=[/data/app/es.ipsa.cloudcheckar-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libgnustl_static.so"
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at java.lang.System.loadLibrary(System.java:989)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:654)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	at org.bytedeco.javacpp.Loader.load(Loader.java:483)
06-02 19:20:09.211: E/AndroidRuntime(14662): 	... 13 more

any hint on this? thanks in advance!

**Comment by saudet** [comment] 2016-06-03 01:34
@iamyellow Please make sure your device is installing JNI libraries properly:
The Perils of Loading Native Libraries on Android
https://medium.com/keepsafe-engineering/the-perils-of-loading-native-libraries-on-android-befa49dce2db

**Comment by xiaos** [comment] 2016-11-19 03:48
I just update javacv to 1.2, and I got a similar issue.



Exception java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZTIN2cv16MinProblemSolver8FunctionE" referenced by "libjniopencv_core.so"...
java.lang.Runtime.loadLibrary (Runtime.java:372)
java.lang.System.loadLibrary (System.java:988)
org.bytedeco.javacpp.Loader.loadLibrary (Loader.java:784)
org.bytedeco.javacpp.Loader.load (Loader.java:586)
org.bytedeco.javacpp.Loader.load (Loader.java:503)
org.bytedeco.javacpp.opencv_core.<clinit> (opencv_core.java:10)
java.lang.Class.classForName (Class.java)
java.lang.Class.forName (Class.java:309)
org.bytedeco.javacpp.Loader.load (Loader.java:558)
org.bytedeco.javacpp.Loader.load (Loader.java:503)
org.bytedeco.javacpp.helper.opencv_core$AbstractArray.<clinit> (opencv_core.java:109)
org.bytedeco.javacv.OpenCVFrameConverter.convertToIplImage (OpenCVFrameConverter.java:91)
org.bytedeco.javacv.OpenCVFrameConverter$ToIplImage.convert (OpenCVFrameConverter.java:44)


Caused by java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.test.javacv-1/base.apk"],nativeLibraryDirectories=[/data/app/com.test.javacv-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libgnustl_static.so" 

java.lang.Runtime.loadLibrary (Runtime.java:367)
java.lang.System.loadLibrary (System.java:988)
org.bytedeco.javacpp.Loader.loadLibrary (Loader.java:784)
org.bytedeco.javacpp.Loader.load (Loader.java:577)
org.bytedeco.javacpp.Loader.load (Loader.java:503)
org.bytedeco.javacpp.opencv_core.<clinit> (opencv_core.java:10)
java.lang.Class.classForName (Class.java)
java.lang.Class.forName (Class.java:309)
org.bytedeco.javacpp.Loader.load (Loader.java:558)
org.bytedeco.javacpp.Loader.load (Loader.java:503)
org.bytedeco.javacpp.helper.opencv_core$AbstractArray.<clinit> (opencv_core.java:109)
org.bytedeco.javacv.OpenCVFrameConverter.convertToIplImage (OpenCVFrameConverter.java:91)
org.bytedeco.javacv.OpenCVFrameConverter$ToIplImage.convert (OpenCVFrameConverter.java:44)

**Comment by saudet** [comment] 2016-11-19 04:02
Duplicate of https://github.com/bytedeco/javacv/issues/386

This is a bug in some Android devices. See this wiki page for a workaround:
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29

**Closed by saudet** 2016-11-19 04:02 UTC
Labels: duplicate
