### ISSUE TITLE
On Win10 AS: A problem occurred when gradle is building...

### ISSUE THREAD

**Issue by 1994711** [bytedeco/javacpp-presets#222] opened 2016-05-16 13:46 UTC
here is the error:
Error:A problem occurred configuring project ':app'.
> Could not find javacpp-presets-Windows 8.1-amd64.jar (org.bytedeco:javacpp-presets:1.2).
  Searched in the following locations:
      https://jcenter.bintray.com/org/bytedeco/javacpp-presets/1.2/javacpp-presets-1.2-Windows 8.1-amd64.jar

and my gradle:

 ```
compile 'org.bytedeco:javacv:+'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version:  '2.4.10-0.10', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version:  '2.5.1-0.10', classifier: 'android-arm'

```
```
packagingOptions{
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.xml'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.xml'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.properties'
    }
```
On Win10 AS ,it report this error. Three days ago, i used the same gradle configurations,it worked well.
Please give me some help.thanks.

**Comment by saudet** [comment] 2016-05-16 13:48
Duplicate of #220

**Closed by saudet** 2016-05-16 13:48 UTC
Labels: duplicate, question

**Comment by 1994711** [comment] 2016-05-16 13:51
i have tried both ways.android-x86 or android-arm. it don't works for me.
