### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jniRealSense in java.library.path

### ISSUE THREAD

**Issue by pierre03** [bytedeco/javacpp-presets#447] opened 2017-07-31 21:49 UTC
Hello,
I created a project maven and added the dependency:
<dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>librealsense-platform</artifactId>
            <version>1.9.6-1.3</version>
</dependency>
then, i added the example TestConnection.java, but i have always the error no jniRealSense in java.library.path
Can you tell me how to solve the error, please?

**Comment by saudet** [comment] 2017-07-31 23:04
If you're trying this on Windows, there are no builds available yet.
Contributions welcome though! Let me know if you encounter any issues with
the build and I'll help.

**Comment by pierre03** [comment] 2017-08-01 06:54
Thank you very much, i did this on my Mac, 
Mac+Intellij+Maven
Compile is ok, only when i run the main method, the error appears:

"/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/java -Didea.launcher.port=7534 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/lib/tools.jar:/Users/ding/flyinstinct/sensorhub/realsensecontroller/target/classes:/Users/ding/.m2/repository/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar:/Users/ding/.m2/repository/ch/qos/logback/logback-core/1.1.3/logback-core-1.1.3.jar:/Users/ding/.m2/repository/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar:/Users/ding/.m2/repository/org/bytedeco/javacpp/1.3.3/javacpp-1.3.3.jar:/Users/ding/.m2/repository/org/bytedeco/javacpp-presets/librealsense-platform/1.9.6-1.3/librealsense-platform-1.9.6-1.3.jar:/Users/ding/.m2/repository/org/bytedeco/javacpp-presets/librealsense/1.9.6-1.3/librealsense-1.9.6-1.3.jar:/Users/ding/.m2/repository/org/bytedeco/javacpp-presets/librealsense/1.9.6-1.3/librealsense-1.9.6-1.3-linux-x86.jar:/Users/ding/.m2/repository/org/bytedeco/javacpp-presets/librealsense/1.9.6-1.3/librealsense-1.9.6-1.3-linux-x86_64.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain com.flyinstinct.sensorhub.realsensecontroller.TestConnection -Djavacpp.platform=macosx-x86_64
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniRealSense in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1119)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:777)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.bytedeco.javacpp.RealSense.<clinit>(RealSense.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at org.bytedeco.javacpp.Loader.load(Loader.java:739)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.bytedeco.javacpp.RealSense$context.<clinit>(RealSense.java:1566)
	at com.flyinstinct.sensorhub.realsensecontroller.TestConnection.main(TestConnection.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Process finished with exit code 1"

**Comment by saudet** [comment] 2017-08-01 06:59
What is the rest of the stack trace with the cause of the error?

**Comment by pierre03** [comment] 2017-08-01 07:00
I found this link, someone have the same error, but i can not understand.
[https://stackoverflow.com/questions/43208145/how-to-use-javacpp-presets-binaries]

**Comment by pierre03** [comment] 2017-08-01 07:11
The detailMessage in the cause is "no jniRealSense in java.library.path
but i see that the loadedLibraries's length is 0, the jniRealSense lib maybe the first one to load.

**Comment by pierre03** [comment] 2017-08-01 07:12
Is there any parameter i should configure in the pom?

**Comment by saudet** [comment] 2017-08-01 07:18
Well, if there are no causes, then that file really isn't in your class
path. Check the sample pom.xml file for how to do this.

**Comment by saudet** [comment] 2017-08-01 07:22
I've just remembered, there are no binaries for Mac either, yet:
https://github.com/bytedeco/javacpp-presets/blob/master/librealsense/platform/pom.xml
Contributions are welcome though! Let me know if you encounter any problems with the build and I will help.

**Comment by pierre03** [comment] 2017-08-01 08:56
So, i have to develop and run my program juste on Linux?

**Comment by pierre03** [comment] 2017-08-01 09:08
I downloaded the binaries from maven repository, can you tell me when you could upload the new complete version, please?

**Comment by saudet** [comment] 2017-08-01 10:13
No, we can build binaries for Mac and Windows as well, but someone has to take the time to do it.

**Comment by pierre03** [comment] 2017-08-01 13:29
Thank you, i'll wait for it.

**Comment by saudet** [comment] 2017-12-07 13:48
I've added support for Mac and Windows in the latest commit above. Enjoy!

**Comment by saudet** [comment] 2018-01-17 12:11
And they have now been released with version 1.4:
http://search.maven.org/#search%7Cga%7C1%7Cbytedeco%20librealsense
Thank you for your patience!

**Closed by saudet** 2018-01-17 12:11 UTC
Labels: enhancement
