### ISSUE TITLE
how to just include arm lib use gradle

### ISSUE THREAD

**Issue by xiedeacc** [bytedeco/javacpp-presets#835] opened 2020-01-05 16:35 UTC
android studio use gradle ,not maven, so how to exclude x86... lib when compile and pack

**Comment by saudet** [comment] 2020-01-06 01:36
We have to do it manually as explained on this page:
https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies

**Comment by saudet** [comment] 2020-01-06 01:39
Duplicate of https://github.com/bytedeco/javacpp/issues/65

**Comment by saudet** [comment] 2020-01-06 01:39
In the case of Android though, this kind of functionality would be available if we had AAR artifacts...

**Comment by saudet** [comment] 2020-01-06 01:40
Duplicate of https://github.com/bytedeco/javacv/issues/1117

**Closed** 2020-01-06 01:40 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2020-06-27 01:01
There is now a plugin for Gradle to exclude by platform names:
https://github.com/bytedeco/gradle-javacpp#the-platform-plugin
If you try it out and find anything missing, please let me know!
