### ISSUE TITLE
Embedded FFmpeg permission error on Android Q

### ISSUE THREAD

**Issue by GZaccaroni** [bytedeco/javacpp-presets#1055] opened 2021-06-12 08:59 UTC
When I execute the following code:
```
String ffmpeg = Loader.load(org.bytedeco.ffmpeg.ffmpeg.class); 
ProcessBuilder pb = new ProcessBuilder(ffmpeg, "-i", "/path/to/input.mp4", "-vcodec", "h264", "/path/to/output.mp4");
 ```

I get:
```
Exception
    java.io.IOException: Cannot run program "/data/data/com.lumyer.app/cache/.javacpp-root/cache/base.apk/lib/arm64-v8a/ffmpeg": error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
```

Do you know if a fix exists?

**Comment by saudet** [comment] 2021-06-12 09:35
Newer APIs of Android don't support executables. Make sure to build for an older version of Android.

**Comment by saudet** [comment] 2021-06-12 09:35
Duplicate of #1410

**Closed by saudet** 2021-06-12 09:35 UTC
Labels: duplicate, question
