### ISSUE TITLE
Error loading class org/bytedeco/javacpp/presets/caffe$ActionCallback. Exception in thread "main" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by avdheshyadav** [bytedeco/javacpp-presets#100] opened 2015-10-10 07:37 UTC
`System.load("/home/avdhesh/Desktop/caffe_libs/libjnicaffe.so");`
causes following Error...
Please help
```
Error loading class org/bytedeco/javacpp/presets/caffe$ActionCallback.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at CaffeWrapperMain.main(CaffeWrapperMain.java:17)
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
	at java.lang.Class.isAnnotationPresent(Class.java:3425)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:132)
	at org.bytedeco.javacpp.Loader.loadProperties(Loader.java:207)
	at org.bytedeco.javacpp.Loader.load(Loader.java:395)
	at org.bytedeco.javacpp.Loader.load(Loader.java:377)
	at org.bytedeco.javacpp.presets.caffe$ActionCallback.<clinit>(caffe.java:153)
	... 6 more
```

**Comment by saudet** [comment] 2015-10-10 08:03
Please try to build from source the latest version. Does the same thing happen?

**Comment by avdheshyadav** [comment] 2015-10-10 11:24
Yes I was testing on  build from the latest version of both javacpp and javacpp-present...I was able to build successfully javacpp, opencv and caffe-master etc.. But during testing I tried to load the genererated libjnicaffe.so  System.load("/home/avdhesh/Desktop/caffe_libs/libjnicaffe.so"); 
Got following error
Error loading class org/bytedeco/javacpp/presets/caffe$ActionCallback.
Exception in thread "main" java.lang.ExceptionInInitializerError
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
    at java.lang.Runtime.load0(Runtime.java:809)
    at java.lang.System.load(System.java:1086)
    at CaffeWrapperMain.main(CaffeWrapperMain.java:17)
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
    at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
    at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
    at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
    at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
    at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
    at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
    at java.lang.Class.createAnnotationData(Class.java:3521)
    at java.lang.Class.annotationData(Class.java:3510)
    at java.lang.Class.getAnnotation(Class.java:3415)
    at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
    at java.lang.Class.isAnnotationPresent(Class.java:3425)
    at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:132)
    at org.bytedeco.javacpp.Loader.loadProperties(Loader.java:207)
    at org.bytedeco.javacpp.Loader.load(Loader.java:395)
    at org.bytedeco.javacpp.Loader.load(Loader.java:377)
    at org.bytedeco.javacpp.presets.caffe$ActionCallback.<clinit>(caffe.java:153)
    ... 6 more

**Comment by saudet** [comment] 2015-10-10 11:26
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/97. That just means your system is trying to use some old code from somewhere for some reason. Just make sure to clean, rebuild, and reinstall everything.

**Closed by saudet** 2015-10-10 11:26 UTC
Labels: duplicate, question

**Comment by avdheshyadav** [comment] 2015-10-10 11:28
Ok.. I will try clean, rebuild and then let you know..Thanks

**Comment by avdheshyadav** [comment] 2015-10-12 06:07
Hi
getting same error after clean, rebuild and reinstall...

Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at CaffeWrapperMain.main(CaffeWrapperMain.java:21)
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
	at java.lang.Class.isAnnotationPresent(Class.java:3425)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:132)
	at org.bytedeco.javacpp.Loader.loadProperties(Loader.java:210)
	at org.bytedeco.javacpp.Loader.load(Loader.java:398)
	at org.bytedeco.javacpp.Loader.load(Loader.java:380)
	at org.bytedeco.javacpp.presets.caffe$ActionCallback.<clinit>(caffe.java:153)
	... 7 more

**Comment by saudet** [comment] 2015-10-12 06:09
Then you are not building the latest version of the source code. You need
to use the latest version of ALL modules, or it will NOT work.

**Comment by avdheshyadav** [comment] 2015-10-12 06:24
Steps I followed..
1) Re-installed ubuntu 14.04.03
2) check out latest javacpp
3) mvn clean install 
4) check out latest javacpp-present
5) ./cppbuild.sh install opencv
6) ./cppbuild.sh install caffe
7) mvn clean install --projects .,opencv,caffe -U

I am able to successfully build the opencv and caff-master and libjnicaffe.so

Next written following class to load the libjnicaffe.so and then I got the error...

public class CaffeWrapperMain 
{
	/** */
	private static final Logger logger = Logger.getLogger(CaffeWrapperMain.class.getSimpleName());
	
	public static void main(String[] args)
	{
		logger.setLevel(Level.ALL);
		System.load("/home/avdhesh/caffe_env/javacpp-presets/opencv/cppbuild/linux-x86_64/lib/libopencv_imgproc.so.3.0");
		System.load("/home/avdhesh/caffe_env/javacpp-presets/opencv/cppbuild/linux-x86_64/lib/libopencv_core.so.3.0");
		System.load("/home/avdhesh/Desktop/caffe_libs/libcaffe.so");
		System.load("/home/avdhesh/Desktop/caffe_libs/libjnicaffe.so");
	}
}

**Comment by saudet** [comment] 2015-10-12 06:41
What happens if you don't call System.load()?

**Comment by avdheshyadav** [comment] 2015-10-12 06:56
Exception in thread "main" java.lang.ExceptionInInitializerError
	at TrainBrewFunction.command(TrainBrewFunction.java:47)
	at CaffeWrapper.executeCommand(CaffeWrapper.java:65)
	at CaffeWrapperMain.main(CaffeWrapperMain.java:22)
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.createAnnotationData(Class.java:3526)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
	at java.lang.Class.isAnnotationPresent(Class.java:3425)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:132)
	at org.bytedeco.javacpp.Loader.loadProperties(Loader.java:210)
	at org.bytedeco.javacpp.Loader.load(Loader.java:398)
	at org.bytedeco.javacpp.Loader.load(Loader.java:380)
	at org.bytedeco.javacpp.caffe$SolverParameter.<clinit>(caffe.java:1907)
	... 3 more

**Comment by saudet** [comment] 2015-10-12 07:18
Why do you need to use the -U option with mvn? What error do you get if you
do not use it?

**Comment by avdheshyadav** [comment] 2015-10-17 06:18
Hi,
Retried again with latest maven (3.3.3)and this time I am able to successfully run train, test commands etc...Thanks for awesome library..

**Comment by saudet** [comment] 2015-10-17 06:59
Great :) Thanks for the feedback!
