### ISSUE TITLE
Tesseract crashes with multiple requests

### ISSUE THREAD

**Issue by icarusfire** [bytedeco/javacpp-presets#64] opened 2015-06-27 22:24 UTC
My web app with Tesseract was working fine(using the code of sample basic example), so I decided to make a very small load test and see how it reacts. I created a scenario that there will be 2 requests per second for 1 minute. And my Tomcat immidiatly crashed after  5 seconds, with this error below,

```
to_blocks->empty():Error:Assert failed:in file textord.cpp, line 292
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fdb30f24f40, pid=5569, tid=140577835312896
#
# JRE version: Java(TM) SE Runtime Environment (8.0_45-b14) (build 1.8.0_45-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libtesseract.so.3+0x251f40]  ERRCODE::error(char const*, TessErrorLogCode, char const*, ...) const+0x190
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /usr/share/apache-tomcat-7.0.62/bin/hs_err_pid5569.log
[thread 140579387172608 also had an error]
[thread 140577833207552 also had an error]
[thread 140579793233664 also had an error]
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by saudet** [comment] 2015-06-28 06:42
It might be something that gets deallocated when it shouldn't. Try to keep
references in fields...

**Comment by saudet** [comment] 2015-07-17 14:08
BTW, it looks like Tesseract is mostly thread safe, but we need to make sure to create one instance per thread:

> Thread-safety! Moved all critical globals and statics to members of the appropriate class. Tesseract is now thread-safe (multiple instances can be used in parallel in multiple threads.) with the minor exception that some control parameters are still global and affect all threads.

https://code.google.com/p/tesseract-ocr/wiki/ReleaseNotes

**Comment by saudet** [comment] 2015-10-12 01:40
So, does using only one instance per thread fixes your issue?

**Comment by icarusfire** [comment] 2015-10-12 07:22
I am not on it since we talked last time. But I could say yes it helped. But still crash if more than 50 req per sec

**Comment by saudet** [comment] 2015-10-12 07:30
It might be because of resources allocated in one thread, but released in
another by the garbage collector. It might be worth trying to deallocate
everything manually. I've added some logging to Pointer to help track
remaining leaks.

**Comment by icarusfire** [comment] 2015-10-12 08:23
Thanks for the update. Once I get back on project I will try it.

**Comment by saudet** [comment] 2015-10-17 13:52
I've found a race condition that would cause SIGSEGV in some multithreaded code I was trying to use recently: https://github.com/bytedeco/javacpp/commit/ed752d299900fc92ebd639a1b5b7139f6902b8db
It's quite possible that this could also be the cause of this issue...

**Comment by saudet** [comment] 2016-05-19 04:04
I've just released version 1.2. Have you had the chance to test this since?

**Comment by pacop** [comment] 2017-05-11 10:25
I continue having problem:

documents.foreach(_.parse) --> works perfectly fine
documents.par.foreach(_.parse) -> does not work

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f6cedee8614, pid=2767, tid=0x00007f6c8aeb7700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x7c614]  cfree+0x14
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/paco/nss/SCALA/hs_err_pid2767.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
/usr/share/sbt/bin/sbt-launch-lib.bash: línea 58:  2767 Abortado                "$@"

```
With tesseract 3.04.01 and JavaCPP 1.3. Scala 2.11

Thanks.

**Comment by saudet** [comment] 2017-05-11 10:32
Try to create one Tesseract context per thread.

**Comment by pacop** [comment] 2017-05-11 10:51
Yep, it works! Thanks.

**Comment by saudet** [comment] 2017-05-11 11:47
Awesome, thanks for confirming!

**Closed by saudet** 2017-05-11 11:47 UTC
Labels: bug
