### ISSUE TITLE
javacv1.2-opencv3.1.0 compilation

### ISSUE THREAD

**Issue by talregev** [bytedeco/javacpp-presets#227] opened 2016-05-21 04:42 UTC
I compile Android app with android studio with gradle compilation on windows 10. 
First compile javacv1.1-opencv3.0.0 compilation with this two commands:
- compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.0.0' + '-1.1'
- compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.0.0' + '-1.1', classifier: 'android-arm'

My Android app is compiling and running.
I want to switch to javacv1.2-opencv3.1.0 compilation.
I switch the compilation with this two commands:
- compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.1.0' + '-1.2'
- compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.1.0' + '-1.2', classifier: 'android-arm'

but when I compile it looking for:
```gradle
 https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/1.2/javacpp-presets-1.2-Windows 10-amd64.jar.
```
Clearly it looking the os and arch from where i compile, not to where it should deploy. 
it create this ivy.xml file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0" xmlns:m="http://ant.apache.org/ivy/maven">
  <info organisation="org.bytedeco.javacpp-presets" module="opencv" revision="3.1.0-1.2" status="release" publication="20160521070138">
    <description homepage=""/>
  </info>
  <configurations>
    <conf name="default" visibility="public" description="runtime dependencies and master artifact can be used with this conf" extends="runtime,master"/>
    <conf name="master" visibility="public" description="contains only the artifact published by this module itself, with no transitive dependencies"/>
    <conf name="compile" visibility="public" description="this is the default scope, used if none is specified. Compile dependencies are available in all classpaths."/>
    <conf name="provided" visibility="public" description="this is much like compile, but indicates you expect the JDK or a container to provide it. It is only available on the compilation classpath, and is not transitive."/>
    <conf name="runtime" visibility="public" description="this scope indicates that the dependency is not required for compilation, but is for execution. It is in the runtime and test classpaths, but not the compile classpath." extends="compile"/>
    <conf name="test" visibility="private" description="this scope indicates that the dependency is not required for normal use of the application, and is only available for the test compilation and execution phases." extends="runtime"/>
    <conf name="system" visibility="public" description="this scope is similar to provided except that you have to provide the JAR which contains it explicitly. The artifact is always available and is not looked up in a repository."/>
    <conf name="sources" visibility="public" description="this configuration contains the source artifact of this module, if any."/>
    <conf name="javadoc" visibility="public" description="this configuration contains the javadoc artifact of this module, if any."/>
    <conf name="optional" visibility="public" description="contains all optional dependencies"/>
  </configurations>
  <publications/>
  <dependencies>
    <dependency org="org.bytedeco" name="javacpp" rev="1.2" force="true" conf="compile-&gt;compile(*),master(*);runtime-&gt;runtime(*)"/>
    <dependency org="org.bytedeco" name="javacpp-presets" rev="1.2" force="true" conf="compile-&gt;compile(*),master(*);runtime-&gt;runtime(*)">
      <artifact name="javacpp-presets" type="jar" ext="jar" conf="" m:classifier="${os.name}-${os.arch}"/>
    </dependency>
  </dependencies>
</ivy-module>
```

the problematic lines here:
```xml
    <dependency org="org.bytedeco" name="javacpp-presets" rev="1.2" force="true" conf="compile-&gt;compile(*),master(*);runtime-&gt;runtime(*)">
      <artifact name="javacpp-presets" type="jar" ext="jar" conf="" m:classifier="${os.name}-${os.arch}"/>
    </dependency>
```
**If I remove this dependency it work fine!
The program are compile and run!**
Also at javacv1.1-opencv3.0.0 compilation ivy.xml file it look like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0" xmlns:m="http://ant.apache.org/ivy/maven">
  <info organisation="org.bytedeco.javacpp-presets" module="opencv" revision="3.0.0-1.1" status="release" publication="20160116014427">
    <description homepage=""/>
  </info>
  <configurations>
    <conf name="default" visibility="public" description="runtime dependencies and master artifact can be used with this conf" extends="runtime,master"/>
    <conf name="master" visibility="public" description="contains only the artifact published by this module itself, with no transitive dependencies"/>
    <conf name="compile" visibility="public" description="this is the default scope, used if none is specified. Compile dependencies are available in all classpaths."/>
    <conf name="provided" visibility="public" description="this is much like compile, but indicates you expect the JDK or a container to provide it. It is only available on the compilation classpath, and is not transitive."/>
    <conf name="runtime" visibility="public" description="this scope indicates that the dependency is not required for compilation, but is for execution. It is in the runtime and test classpaths, but not the compile classpath." extends="compile"/>
    <conf name="test" visibility="private" description="this scope indicates that the dependency is not required for normal use of the application, and is only available for the test compilation and execution phases." extends="runtime"/>
    <conf name="system" visibility="public" description="this scope is similar to provided except that you have to provide the JAR which contains it explicitly. The artifact is always available and is not looked up in a repository."/>
    <conf name="sources" visibility="public" description="this configuration contains the source artifact of this module, if any."/>
    <conf name="javadoc" visibility="public" description="this configuration contains the javadoc artifact of this module, if any."/>
    <conf name="optional" visibility="public" description="contains all optional dependencies"/>
  </configurations>
  <publications/>
  <dependencies>
    <dependency org="org.bytedeco" name="javacpp" rev="1.1" force="true" conf="compile-&gt;compile(*),master(*);runtime-&gt;runtime(*)"/>
  </dependencies>
</ivy-module>
 
```

I am not sure how to fix it, but you can see the problem, and at javacv1.1-opencv3.0.0 compilation it work great. 

Thanks for your hard work, and for time for reading this, and understand the problem.
Tal.

**Comment by saudet** [comment] 2016-05-21 05:55
Duplicate of https://github.com/bytedeco/javacv/issues/395

**Closed by saudet** 2016-05-21 05:55 UTC
Labels: bug, duplicate
