### ISSUE TITLE
[ffmpeg] avformat_find_stream_info crashes with Read_packet_Pointer_BytePointer_int

### ISSUE THREAD

**Issue by nanguantong** [bytedeco/javacpp-presets#732] opened 2019-05-23 06:58 UTC
warning: Unexpected size of section `.reg-xstate/49454' in core file.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/resources/'.
Program terminated with signal SIGABRT, Aborted.

warning: Unexpected size of section `.reg-xstate/49454' in core file.
#0  0x00007f4ec8a65428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f4e6b5f5700 (LWP 49454))]
(gdb) bt
#0  0x00007f4ec8a65428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f4ec8a6702a in __GI_abort () at abort.c:89
#2  0x00007f4ec835f365 in os::abort(bool) ()
   from /resources/jdk8/jre/lib/amd64/server/libjvm.so
#3  0x00007f4ec8503403 in VMError::report_and_die() ()
   from /resources/jdk8/jre/lib/amd64/server/libjvm.so
#4  0x00007f4ec836565f in JVM_handle_linux_signal ()
   from /resources/jdk8/jre/lib/amd64/server/libjvm.so
#5  0x00007f4ec835b683 in signalHandler(int, siginfo*, void*) ()
   from /resources/jdk8/jre/lib/amd64/server/libjvm.so
#6  <signal handler called>
#7  0x00007f4ec810ab1f in jni_invoke_nonstatic(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*) ()
   from /resources/jdk8/jre/lib/amd64/server/libjvm.so
#8  0x00007f4ec811079d in jni_CallIntMethodA ()
   from /resources/jdk8/jre/lib/amd64/server/libjvm.so
#9  0x00007f4e50327c5c in ?? () from /root/.javacpp/cache/ffmpeg-4.1.3-1.5-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavformat.so
#10 0x00007f4e4ba83ab6 in avformat_find_stream_info ()
   from /root/.javacpp/cache/ffmpeg-4.1.3-1.5-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavformat.so.58

**Comment by nanguantong** [comment] 2019-05-24 03:16
it crashes when multi-stream opened with buffer callback

**Comment by saudet** [comment] 2019-05-24 03:34
This is something that's been fixed recently. Please give it a try with the
snapshots:
http://bytedeco.org/builds/

**Comment by saudet** [comment] 2019-05-24 08:33
Duplicate of #683

**Closed by saudet** 2019-05-24 08:33 UTC
Labels: duplicate, enhancement

**Comment by nanguantong** [comment] 2019-05-25 04:39
> Duplicate of #683

It's different with #683

**Comment by saudet** [comment] 2019-05-25 04:48
Make sure to use the snapshots:
http://bytedeco.org/builds/

**Comment by saudet** [comment] 2019-05-27 00:46
Some codecs are also known to have issues with threads: https://github.com/bytedeco/javacv/issues/1139
You'll need to provide synchronization in Java to work around those issues.

**Comment by nanguantong** [comment] 2019-05-28 06:39
> Some codecs are also known to have issues with threads: [bytedeco/javacv#1139](https://github.com/bytedeco/javacv/issues/1139)
> You'll need to provide synchronization in Java to work around those issues.

The stream is only wraped rtp with h264 codec

**Comment by saudet** [comment] 2019-06-12 10:22
If synchronization at the Java level is unacceptable, make sure to report this issue upstream!
