### ISSUE TITLE
Conflict with armeabi-v7a.

### ISSUE THREAD

**Issue by DTHeaven** [bytedeco/javacpp-presets#71] opened 2015-07-14 08:20 UTC
When I use with other any .so file in armeabi-v7a, some of ffmpeg .so files(e.g. libavcodec.so) won't copied to local libs dirs.
How can I solve this problem?
Thanks.

**Comment by saudet** [comment] 2015-07-14 13:44
My guess is that we should just put everything manually in the `jniLibs` folder, as shown, for example, in https://github.com/bytedeco/javacv/issues/133, but I'm unsure if Google has any better methods for that. Could you check this out and most likely ask them for me? It would help a lot, because it's really hard to figure out what they want us to do.

**Comment by DTHeaven** [comment] 2015-07-15 07:16
I put those .so files in jniLibs/armeabi-v7a, it seems work.

Another question,
what's the difference between JavaCV & JavaFFMpeg, is there something JavaFFMpeg can do but JavaCV not?

**Comment by DTHeaven** [comment] 2015-07-15 07:19
Thanks.

**Comment by saudet** [comment] 2015-07-15 13:50
I don't know of any project named "JavaFFMpeg". Could you also provide a URL so that I may have a look? Thanks

**Comment by DTHeaven** [comment] 2015-07-15 14:54
I mean javacpp-presets(ffmpeg). ~_~!
Now I have unsderstood, JavaCv is a collection, it contains OpenCv & FFmpeg.
Javacpp-presets(ffmpeg) only contains FFMpeg.
Thank you very much.

**Comment by saudet** [comment] 2016-05-19 04:07
Marking as duplicate of https://github.com/bytedeco/javacv/issues/133

**Closed by saudet** 2016-05-19 04:07 UTC
Labels: duplicate
