### ISSUE TITLE
Tesseract 4.0 support

### ISSUE THREAD

**Issue by asevans48** [bytedeco/javacpp-presets#385] opened 2017-02-24 23:41 UTC
Tesseract 4.0 is feature complete (https://github.com/tesseract-ocr/tesseract/wiki/4.0%20Accuracy%20and%20Performance). Any chance of an update to the java-cpp presets? 

Keep up the great work.

**Comment by saudet** [comment] 2017-02-24 23:53
Sure, mind giving it a try yourself?

**Comment by asevans48** [comment] 2017-02-24 23:59
I'll see if I can find the time. I know its intensive. Right now I am starting to write for a blog, trying get a company going, and doing the whole 9-5/6pm thing.

**Comment by shengc** [comment] 2017-08-03 20:29
would be really helpful if presets can upgrade the supported version of tesseract to 4.0, as it was trained with LSTM

On a separate note, I tried to resolve against 1.3.4-SNAPSHOT, but got a few resolution errors for dependencies like,

    tesseract-3.05.01-1.3.4-20170801.192635-8-linux-x86_64.jar
    leptonica-1.74.4-1.3.4-20170801.192633-8-linux-x86_64.jar
    ...

Is this the right one to use?

    "org.bytedeco.javacpp-presets" % "tesseract-platform" % "3.05.01-1.3.4-SNAPSHOT"

Do I have to use a custom resolver ?

**Comment by saudet** [comment] 2017-08-03 21:24
Gradle has issues with SNAPSHOT artifacts, but it works if they are in
.m2/repository instead.

**Comment by shengc** [comment] 2017-08-03 21:50
Sorry, I am not sure if I follow. I am using sbt to resolve the dependencies. Do you actually mean that sbt has issue with SNAPSHOT artifacts ? And what exactly does "but it works if they are in
.m2/repository instead" mean ?

**Comment by saudet** [comment] 2017-08-03 22:02
Sorry, I meant sbt as well as Gradle. If the artifacts are available in .m2/repository and ask Gradle or sbt to pick the up from there, it works.

**Comment by saudet** [comment] 2017-08-08 14:43
Could you please report this issue upstream so the guys working on sbt can get this working properly? That would be great.

**Comment by amalow** [comment] 2018-02-04 23:35
+1 on this issue, Tesseract 4.0.0 support would be much appreciated.

**Comment by saudet** [comment] 2018-02-04 23:41
@amalow Please try to update the presets! If you encounter any issues, I will help you out.

**Comment by amalow** [comment] 2018-02-05 01:39
This could be my bad, able to build Leptonica successfully but when building Tesseract mvn install is crashing at:

`libtool: warning: library '/Users/adam/.javacpp/cache/leptonica-1.74.4-1.4.1-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/javacpp/macosx-x86_64/lib//liblept.la' was moved.
grep: /Users/travis/build/bytedeco/javacpp-presets/leptonica/cppbuild/macosx-x86_64/lib/libjpeg.la: No such file or directory
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -I../ccstruct -I../ccutil -I../viewer -DUSE_STD_NAMESPACE -I/Users/adam/.javacpp/cache/leptonica-1.74.4-1.4.1-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/javacpp/macosx-x86_64/include/ -I/Users/adam/.javacpp/cache/leptonica-1.74.4-1.4.1-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/javacpp/macosx-x86_64/include/leptonica/ -I/usr/local/Cellar/pango/1.40.7/include/pango-1.0 -I/usr/local/Cellar/glib/2.52.3/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.3/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.41/include -I/usr/local/Cellar/cairo/1.14.10/include/cairo -I/usr/local/Cellar/glib/2.52.3/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.3/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.41/include -I/usr/local/Cellar/pixman/0.34.0_1/include/pixman-1 -I/usr/local/Cellar/fontconfig/2.12.4/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/libpng/1.6.34/include/libpng16 -g -O2 -std=c++11 -MT intsimdmatrix.lo -MD -MP -MF .deps/intsimdmatrix.Tpo -c intsimdmatrix.cpp -o intsimdmatrix.o >/dev/null 2>&1
sed: /Users/travis/build/bytedeco/javacpp-presets/leptonica/cppbuild/macosx-x86_64/lib/libjpeg.la: No such file or directory
libtool:   error: '/Users/travis/build/bytedeco/javacpp-presets/leptonica/cppbuild/macosx-x86_64/lib/libjpeg.la' is not a valid libtool archive
make[3]: *** [libtesseract_avx.la] Error 1
make[3]: *** Waiting for unfinished jobs....
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -I../ccstruct -I../ccutil -I../viewer -DUSE_STD_NAMESPACE -I/Users/adam/.javacpp/cache/leptonica-1.74.4-1.4.1-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/javacpp/macosx-x86_64/include/ -I/Users/adam/.javacpp/cache/leptonica-1.74.4-1.4.1-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/javacpp/macosx-x86_64/include/leptonica/ -I/usr/local/Cellar/pango/1.40.7/include/pango-1.0 -I/usr/local/Cellar/glib/2.52.3/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.3/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.41/include -I/usr/local/Cellar/cairo/1.14.10/include/cairo -I/usr/local/Cellar/glib/2.52.3/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.3/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.41/include -I/usr/local/Cellar/pixman/0.34.0_1/include/pixman-1 -I/usr/local/Cellar/fontconfig/2.12.4/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/libpng/1.6.34/include/libpng16 -g -O2 -std=c++11 -MT simddetect.lo -MD -MP -MF .deps/simddetect.Tpo -c simddetect.cpp -o simddetect.o >/dev/null 2>&1
mv -f .deps/libtesseract_avx2_la-intsimdmatrixavx2.Tpo .deps/libtesseract_avx2_la-intsimdmatrixavx2.Plo
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2`


I had a brief look through the project search and couldn't find anything related to Travis, may be an issue within Tesseract?

**Comment by saudet** [comment] 2018-02-05 02:43
Tesseract requires libtool to build. Make sure to follow these instructions before attempting a build on your Mac: https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#mac-os-x-x86_64

**Comment by amalow** [comment] 2018-02-05 03:06
All of those tools are present on my system, I've built Tesseract from source previously

The above output was with -X on mvn, this is what is produced without that flag

```
grep: /Users/travis/build/bytedeco/javacpp-presets/leptonica/cppbuild/macosx-x86_64/lib/libjpeg.la: No such file or directory
grep: /Users/travis/build/bytedeco/javacpp-presets/leptonica/cppbuild/macosx-x86_64/lib/libjpeg.la: No such file or directory
grep: /Users/travis/build/bytedeco/javacpp-presets/leptonica/cppbuild/macosx-x86_64/lib/libjpeg.la: No such file or directory
sed: /Users/travis/build/bytedeco/javacpp-presets/leptonica/cppbuild/macosx-x86_64/lib/libjpeg.la: No such file or directory
grep: /Users/travis/build/bytedeco/javacpp-presets/leptonica/cppbuild/macosx-x86_64/lib/libjpeg.la: No such file or directory
sed: /Users/travis/build/bytedeco/javacpp-presets/leptonica/cppbuild/macosx-x86_64/lib/libjpeg.la: No such file or directory
sed: /Users/travis/build/bytedeco/javacpp-presets/leptonica/cppbuild/macosx-x86_64/lib/libjpeg.la: No such file or directory
sed: /Users/travis/build/bytedeco/javacpp-presets/leptonica/cppbuild/macosx-x86_64/lib/libjpeg.la: No such file or directory
libtool:   error: '/Users/travis/build/bytedeco/javacpp-presets/leptonica/cppbuild/macosx-x86_64/lib/libjpeg.la' is not a valid libtool archive
libtool:   error: '/Users/travis/build/bytedeco/javacpp-presets/leptonica/cppbuild/macosx-x86_64/lib/libjpeg.la' is not a valid libtool archive
libtool:   error: '/Users/travis/build/bytedeco/javacpp-presets/leptonica/cppbuild/macosx-x86_64/lib/libjpeg.la' is not a valid libtool archive

```

**Comment by saudet** [comment] 2018-02-05 03:11
Well it works fine on my system and on Travis Ci, so something is off with your machine I'm afraid.

**Comment by saudet** [comment] 2018-02-05 03:13
It looks like it's trying to use builds of Leptonica from Travis CI, and Mac is known to have issues with changing directories yes. This just means it's not finding your build of Leptonica. Don't try to build them separately. Build them together as per the instructions in the README.md file.

**Comment by amalow** [comment] 2018-02-06 06:22
I've updated the presets (seemed like there were only a couple changes) and am installing successfully, my clang++ on OSX is being difficult (strange as it can compile tesseract just fine) when i'm trying to mvn package Tesseract, currently working on compiling for Linux.

**Comment by saudet** [comment] 2018-02-06 06:43
Great, send a pull request and we'll see if Travis CI has issues! Thanks

**Comment by toranaga** [comment] 2018-02-06 15:05
Any plans when would be available ?

**Comment by saudet** [comment] 2018-02-07 03:01
@toranaga It's already available at pull https://github.com/bytedeco/javacpp-presets/pull/522.

I'll mark this as a duplicate of the pull request. Let's continue this thread over there! Thanks

**Closed by saudet** 2018-02-07 03:01 UTC
Labels: duplicate, enhancement
