### ISSUE TITLE
build ffmpeg with

### ISSUE THREAD

**Issue by mifritscher** [bytedeco/javacpp-presets#443] opened 2017-07-16 17:12 UTC
Thanks for your work!
It would be nice to build the ffmpeg libraries with libfreetype so I can e.g. use the drawtext option :-)

Luckily, it works for now by simple exchanging the dlls with the statically built ones from ffmpeg.org ;-)

**Comment by saudet** [comment] 2017-07-16 22:52
Duplicate of https://github.com/bytedeco/javacv/issues/254

Contributions are welcome!

**Closed by saudet** 2017-07-16 22:52 UTC
Labels: duplicate, enhancement
