### ISSUE TITLE
OpenBLAS/LAPACK support on M1 Macs

### ISSUE THREAD

**Issue by LeoYulinLi** [bytedeco/javacpp-presets#1198] opened 2022-07-08 02:04 UTC
Hello,

I am getting this error when trying to invoke a lapack function:

```
'int org.bytedeco.openblas.global.openblas.LAPACKE_dsyevd(int, byte, byte, int, java.nio.DoubleBuffer, int, java.nio.DoubleBuffer)'
java.lang.UnsatisfiedLinkError: 'int org.bytedeco.openblas.global.openblas.LAPACKE_dsyevd(int, byte, byte, int, java.nio.DoubleBuffer, int, java.nio.DoubleBuffer)'
	at org.bytedeco.openblas.global.openblas.LAPACKE_dsyevd(Native Method)
	at smile.math.blas.openblas.OpenBLAS.syevd(OpenBLAS.java:629)
	at smile.math.matrix.Matrix.eigen(Matrix.java:1628)
	at smile.projection.PCA.fit(PCA.java:176)
...
```

I tried both `0.3.19-1.5.7` and `0.3.20-1.5.8-SNAPSHOT` with azul JDK 17.0.3 and was still getting the same error.

These are my javacpp dependencies:
```
        implementation group: 'org.bytedeco', name: 'javacpp', version: '1.5.8-SNAPSHOT'
        implementation group: 'org.bytedeco', name: 'openblas', version: '0.3.20-1.5.8-SNAPSHOT'
        implementation group: 'org.bytedeco', name: 'openblas-platform', version: '0.3.20-1.5.8-SNAPSHOT'
        implementation group: 'org.bytedeco', name: 'arpack-ng', version: '3.8.0-1.5.8-SNAPSHOT'
        implementation group: 'org.bytedeco', name: 'arpack-ng-platform', version: '3.8.0-1.5.8-SNAPSHOT'
```

Any idea on what might have caused this?

Thanks!

Leo

**Comment by saudet** [comment] 2022-07-08 02:06
Duplicate of #1171

**Closed by saudet** 2022-07-08 02:06 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2022-08-11 00:57
This has been fixed! Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by LeoYulinLi** [comment] 2022-08-11 01:29
> This has been fixed! Please give it a try with the snapshots: http://bytedeco.org/builds/

It works! Thanks!
