### ISSUE TITLE
Error When Creating Bundles

### ISSUE THREAD

**Issue by nikunjramani** [bytedeco/javacpp-presets#930] opened 2020-08-18 14:21 UTC
hii I am Keep getting this error when i Create A Bundle

File 'root/lib/arm64-v8a/include/opencv2/core/base.hpp' uses reserved file or directory name 'lib'.

Here My Dependencies
implementation 'org.bytedeco:javacv:1.4.4'
    implementation 'org.bytedeco.javacpp-presets:opencv:4.0.1-1.4.4:android-arm64'
    implementation 'org.bytedeco.javacpp-presets:ffmpeg:4.1-1.4.4:android-arm64'
    implementation 'org.bytedeco.javacpp-presets:opencv:4.0.1-1.4.4:android-arm'
    implementation 'org.bytedeco.javacpp-presets:ffmpeg:4.1-1.4.4:android-arm'
i also try to add external .jar files but I am still getting this error

**Comment by saudet** [comment] 2020-08-19 01:35
Duplicate of https://github.com/bytedeco/javacv/issues/1494

**Closed by saudet** 2020-08-19 01:35 UTC

**Comment by saudet** [comment] 2020-08-19 01:38
You'll need to exclude all the files from `lib/arm64-v8a/include`, etc.

**Comment by nikunjramani** [comment] 2020-08-19 05:23
I Am Getting Error When I Exclude Files


E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: www.facetagr.com.livenessmodeleval, PID: 16741
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/www.facetagr.com.livenessmodeleval--VdVpPvLrMAaqIzA5Q7X2g==/base.apk"],nativeLibraryDirectories=[/data/app/www.facetagr.com.livenessmodeleval--VdVpPvLrMAaqIzA5Q7X2g==/lib/arm64, /data/app/www.facetagr.com.livenessmodeleval--VdVpPvLrMAaqIzA5Q7X2g==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "libjniopencv_core.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1302)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1043)
        at org.bytedeco.javacpp.Loader.load(Loader.java:935)
        at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at org.bytedeco.javacpp.Loader.load(Loader.java:994)
        at org.bytedeco.javacpp.Loader.load(Loader.java:935)
        at org.bytedeco.javacpp.opencv_imgproc.<clinit>(opencv_imgproc.java:12)
        at org.bytedeco.javacpp.opencv_imgproc.createCLAHE(Native Method)
        at www.facetagr.com.LivenessModelEval.FaceTyckCore.onHandleWork(FaceTyckCore.java:90)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/www.facetagr.com.livenessmodeleval--VdVpPvLrMAaqIzA5Q7X2g==/base.apk"],nativeLibraryDirectories=[/data/app/www.facetagr.com.livenessmodeleval--VdVpPvLrMAaqIzA5Q7X2g==/lib/arm64, /data/app/www.facetagr.com.livenessmodeleval--VdVpPvLrMAaqIzA5Q7X2g==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "libopencv_imgproc.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1302)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1021)
        at org.bytedeco.javacpp.Loader.load(Loader.java:935) 
        at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10) 
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at org.bytedeco.javacpp.Loader.load(Loader.java:994) 
        at org.bytedeco.javacpp.Loader.load(Loader.java:935) 
        at org.bytedeco.javacpp.opencv_imgproc.<clinit>(opencv_imgproc.java:12) 
        at org.bytedeco.javacpp.opencv_imgproc.createCLAHE(Native Method) 
        at www.facetagr.com.LivenessModelEval.FaceTyckCore.onHandleWork(FaceTyckCore.java:90) 
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392) 
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383) 
        at android.os.AsyncTask$3.call(AsyncTask.java:378) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by saudet** [comment] 2020-08-19 05:30
You'll need to leave files like libopencv_imgproc.so.

**Comment by nikunjramani** [comment] 2020-08-19 05:47
i just exclude .hpp files from include/ folders i did not delete any .so files

**Comment by saudet** [comment] 2020-08-19 06:29
Make sure it's in your APK file.

**Comment by nikunjramani** [comment] 2020-08-19 06:39
yes it available in my apk file

**Comment by nikunjramani** [comment] 2020-08-19 06:49
It Says 
couldn't find "libjniopencv_core.so"

but this file already there

hey can you explain me what causing error

**Comment by saudet** [comment] 2020-08-19 07:24
That means the file doesn't exist. I can't think of any other interpretation. If the file does indeed exist, it's a bug in Android and you should report this upstream to your device manufacturer and/or Google.

**Comment by saudet** [comment] 2020-08-19 07:28
In any case, JavaCV 1.4.4 is pretty old. Please try again with at least the latest release version of 1.5.3.

**Comment by nikunjramani** [comment] 2020-08-19 18:15
Hey i have update javacv to 1.5.3
But when i exclude include/ files it will give error
Libopencv_imgproc.so not found

What use of include folder files do i need st runtime

**Comment by saudet** [comment] 2020-08-20 00:26
Like I said, you do not need the "include folder", you can exclude all the files in there.

BTW, one thing you could try to work around loading issues with Android is ReLinker:
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29

**Comment by nikunjramani** [comment] 2020-08-20 09:44
@saudet Thanks For Your Help
I Have Solved Error

Just Follow Below Step
Step 1 : Put All .so files opencv-arm64 to arm64-v8a and opecv-arm to armeabi-v7a folder
Step 2 : Add This Lines of Code Your build.gradle file
    sourceSets {
        main {
            jniLibs.srcDirs = ["libs"]
        }
    }
Step 3 : Rebuild Project And Create Bundles It Work Perfectly
