### ISSUE TITLE
arrow module - Downloading http://zlib.net/zlib-1.2.13.tar.gz http error 404

### ISSUE THREAD

**Issue by archenroot** [bytedeco/javacpp-presets#1450] opened 2023-12-27 17:34 UTC
The url in the script doesn't work, there is new working URL: https://www.zlib.net/fossils/zlib-1.2.13.tar.gz

**Comment by saudet** [comment] 2023-12-28 00:28
I'm not maintaining those presets myself, but you're welcome to provide a fix!

**Comment by saudet** [comment] 2023-12-28 00:29
Duplicate of #1451

**Closed by saudet** 2023-12-28 00:29 UTC
Labels: duplicate, enhancement

**Comment by archenroot** [comment] 2024-01-02 17:27
This one is not duplicate of #1451 - these are 2 different issues, I just fixed this one here: https://github.com/bytedeco/javacpp-presets/commit/869a41c4684086733ad7e0130be12eed9c5e2c8e

**Comment by saudet** [comment] 2024-01-02 18:01
That's fine, just open a pull request.
