### ISSUE TITLE
FastLineDetector is not implemented in opencv_ximgproc

### ISSUE THREAD

**Issue by Daniel-Alievsky** [bytedeco/javacpp-presets#991] opened 2020-12-27 15:39 UTC
Hello! I tried to use FastLineDetector instead of LineSegmentDetector, which was removed from OpenCV due to license issues.
However, I was surprised when didn't find FastLineDetector in org.bytedeco.opencv.opencv_ximgproc package. What is the reason? Will be it added in future versions?

At the same time, I found FastLineDetector in another package: org.opencv.ximgproc, which was also added inside standard JavaCPP opencv dependence (opencv-platform). Unfortunately, this implementation processes other Mat class: org.opencv.core.Mat, but all my other functions work with org.bytedeco.opencv.opencv_core.Mat. Maybe, is there some way to convert one class to another?

**Comment by saudet** [comment] 2020-12-28 01:20
That's been fixed in commit f69b146172e3ac33017b41f0261b6d910e6cd969. Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment] 2020-12-28 01:20
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/958

**Closed by saudet** 2020-12-28 01:20 UTC
Labels: duplicate, enhancement
