### ISSUE TITLE
FFMpeg: ffmpeg-6.0-1.5.9-windows-x86_64-gpl artifact misses avdevice-60.dll and jniavdevice.dll

### ISSUE THREAD

**Issue by edwinRNDR** [bytedeco/javacpp-presets#1406] opened 2023-08-26 14:24 UTC
When using the `ffmpeg:windows-x86_64-gpl:6.0-1.5.9` artefact.

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniavfilter in java.library.path:  [omitted] .
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1832)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1423)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
	at org.bytedeco.ffmpeg.global.avfilter.<clinit>(avfilter.java:26)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1289)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
	at org.bytedeco.ffmpeg.global.avdevice.<clinit>(avdevice.java:28)
	at org.openrndr.ffmpeg.VideoPlayerFFMPEG$Companion.listDeviceNames(VideoPlayerFFMPEG.kt:261)
	at TemplateProgramKt$main$1$2.invokeSuspend(TemplateProgram.kt:21)
	at TemplateProgramKt$main$1$2.invoke(TemplateProgram.kt)
	at TemplateProgramKt$main$1$2.invoke(TemplateProgram.kt)
	at org.openrndr.ApplicationBuilderJVM$program$1.setup(ApplicationBuilder.kt:116)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3$loop$15.invokeSuspend(ApplicationGLFWGL3.kt:871)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.loop(ApplicationGLFWGL3.kt:870)
	at org.openrndr.Application.run$openrndr_application(Application.kt:71)
	at org.openrndr.ApplicationBuilderKt.application(ApplicationBuilder.kt:89)
	at TemplateProgramKt.main(TemplateProgram.kt:11)
	at TemplateProgramKt.main(TemplateProgram.kt)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\[omitted]\.javacpp\cache\ffmpeg-6.0-1.5.9-windows-x86_64-gpl.jar\org\bytedeco\ffmpeg\windows-x86_64-gpl\jniavfilter.dll: Can't find dependent libraries
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1779)
	... 29 more
```

Note that the `ffmpeg-6.0-1.5.9-windows-x86_64` artifact does include said dlls and works without issues.

**Comment by saudet** [comment] 2023-08-27 00:26
Duplicate of https://github.com/bytedeco/javacv/issues/2039

**Comment by saudet** [comment] 2023-08-27 00:26
Please try again with the snapshots: http://bytedeco.org/builds/

**Closed by saudet** 2023-08-27 00:26 UTC
Labels: bug, duplicate
